export const conceptPools: Record<string, string[]> = {
  "this-core": ["this", "렉시컬 환경", "클로저", "프로토타입", "스코프", "생성자 함수"],
  "js-arrays": ["배열", "index", "push", "pop", "shift", "unshift"],
  "js-array-methods": ["map", "filter", "find", "slice", "splice", "배열 메서드"],
  "js-arrow-functions": [
    "=>",
    "화살표 함수",
    "암묵적 반환",
    "매개변수",
    "implicit return",
    "arrow function",
  ],
  "js-basics": ["script", "let", "const", "strict mode", "camelCase", "변수 선언"],
  "js-class-basic": ["class", "constructor", "new", "prototype", "method", "instance"],
  "js-class-inheritance": ["extends", "super", "super()", "상속", "부모 클래스", "파생 클래스"],
  "js-comparison": ["==", "===", "문자열 비교", "null", "undefined", "boolean"],
  "js-constructor-new": ["new", "생성자 함수", "this", "객체 생성", "return", "uppercase"],
  "js-conditionals": ["if", "else", "truthy", "falsy", "조건 연산자", "분기"],
  "js-date": ["Date", "timestamp", "getMonth", "getTime", "Date.now", "UTC"],
  "js-destructuring": ["구조 분해", "배열 구조 분해", "객체 구조 분해", "기본값", "rest", "별칭"],
  "js-error-handling": ["try", "catch", "finally", "throw", "Error", "runtime error"],
  "js-extend-natives": [
    "extends",
    "Array",
    "Error",
    "Symbol.species",
    "custom error",
    "내장 클래스",
  ],
  "js-garbage-collection": [
    "도달 가능성",
    "reachable",
    "unreachable",
    "루트",
    "참조",
    "가비지 컬렉션",
  ],
  "js-function-expressions": ["함수 표현식", "콜백", "호이스팅", "함수 값", "callback", "hoisting"],
  "js-function-prototype": [
    "F.prototype",
    "constructor",
    "new",
    "instance",
    "[[Prototype]]",
    "생성자",
  ],
  "js-functions": ["함수", "매개변수", "return", "지역 변수", "호출", "parameter"],
  "js-iterables": ["Symbol.iterator", "for...of", "iterator", "next", "done", "iterable"],
  "js-instanceof": [
    "instanceof",
    "prototype chain",
    "Symbol.hasInstance",
    "Array.isArray",
    "constructor",
    "class",
  ],
  "js-json": ["JSON.stringify", "JSON.parse", "toJSON", "replacer", "reviver", "직렬화"],
  "js-logical-operators": ["||", "&&", "!", "short-circuit", "truthy", "falsy"],
  "js-map-set": ["Map", "Set", "key-value", "size", "set", "has"],
  "js-mixins": ["mixin", "Object.assign", "prototype", "단일 상속", "composition", "재사용"],
  "js-native-prototypes": [
    "Array.prototype",
    "Object.prototype",
    "String.prototype",
    "polyfill",
    "래퍼 객체",
    "내장 프로토타입",
  ],
  "js-loops": ["while", "for", "break", "continue", "반복문", "loop"],
  "js-nullish": ["??", "null", "undefined", "기본값", "falsy", "default value"],
  "js-object-copy": [
    "참조",
    "얕은 복사",
    "깊은 복사",
    "Object.assign",
    "reference",
    "shallow copy",
  ],
  "js-object-keys-values-entries": [
    "Object.keys",
    "Object.values",
    "Object.entries",
    "Object.fromEntries",
    "key-value",
    "구조 분해",
  ],
  "js-objects": ["객체", "프로퍼티", "key", "value", "delete", "점 표기법"],
  "js-object-toprimitive": [
    "Symbol.toPrimitive",
    "toString",
    "valueOf",
    "string hint",
    "number hint",
    "원시형 변환",
  ],
  "js-optional-chaining": [
    "?.",
    "nullish",
    "undefined",
    "메서드 호출",
    "safe access",
    "optional chaining",
  ],
  "js-operators": ["+", "단항 +", "%", "**", "증가 연산자", "문자열 연결"],
  "js-private-protected": [
    "#private",
    "private field",
    "protected",
    "_field",
    "encapsulation",
    "접근 제한",
  ],
  "js-promise-api": [
    "AggregateError",
    "Promise.all",
    "Promise.allSettled",
    "Promise.any",
    "Promise.race",
    "Promise.resolve",
  ],
  "js-promise-errors": ["catch", "reject", "throw", "rethrow", "unhandledrejection", "rejection"],
  "js-promises": ["Promise", "resolve", "reject", "pending", "fulfilled", "rejected", "thenable"],
  "js-property-accessors": ["getter", "setter", "get", "set", "접근자", "설명자"],
  "js-property-descriptors": [
    "descriptor",
    "writable",
    "enumerable",
    "configurable",
    "defineProperty",
    "플래그",
  ],
  "js-prototype-inheritance": ["prototype", "__proto__", "상속", "체인", "this", "null"],
  "js-prototype-methods": [
    "Object.create",
    "Object.getPrototypeOf",
    "Object.setPrototypeOf",
    "__proto__",
    "null prototype",
    "dictionary object",
  ],
  "js-rest-spread": ["rest", "spread", "...", "args", "iterable", "전개 문법"],
  "js-static-properties-methods": [
    "static",
    "정적 메서드",
    "정적 프로퍼티",
    "ClassName.method",
    "factory method",
    "constructor",
  ],
  "js-switch": ["switch", "case", "default", "break", "fall-through", "==="],
  "js-symbols": ["Symbol", "고유값", "심볼 키", "Symbol.for", "전역 레지스트리", "열거"],
  "js-types": ["number", "string", "boolean", "null", "undefined", "typeof"],
  "js-variables": ["let", "const", "var", "상수", "재할당", "하드코딩"],
  "js-weakmap-weakset": ["WeakMap", "WeakSet", "약한 참조", "객체 키", "객체 값", "순회 불가"],
};
