export const conceptPools: Record<string, string[]> = {
  "this-core": ["this", "렉시컬 환경", "클로저", "프로토타입", "스코프", "생성자 함수"],
  "js-arrow-functions": [
    "=>",
    "화살표 함수",
    "암묵적 반환",
    "매개변수",
    "implicit return",
    "arrow function",
  ],
  "js-basics": ["script", "let", "const", "strict mode", "camelCase", "변수 선언"],
  "js-comparison": ["==", "===", "문자열 비교", "null", "undefined", "boolean"],
  "js-constructor-new": ["new", "생성자 함수", "this", "객체 생성", "return", "uppercase"],
  "js-conditionals": ["if", "else", "truthy", "falsy", "조건 연산자", "분기"],
  "js-garbage-collection": [
    "도달 가능성",
    "reachable",
    "unreachable",
    "루트",
    "참조",
    "가비지 컬렉션",
  ],
  "js-function-expressions": ["함수 표현식", "콜백", "호이스팅", "함수 값", "callback", "hoisting"],
  "js-functions": ["함수", "매개변수", "return", "지역 변수", "호출", "parameter"],
  "js-logical-operators": ["||", "&&", "!", "short-circuit", "truthy", "falsy"],
  "js-loops": ["while", "for", "break", "continue", "반복문", "loop"],
  "js-nullish": ["??", "null", "undefined", "기본값", "falsy", "default value"],
  "js-object-copy": [
    "참조",
    "얕은 복사",
    "깊은 복사",
    "Object.assign",
    "reference",
    "shallow copy",
  ],
  "js-objects": ["객체", "프로퍼티", "key", "value", "delete", "점 표기법"],
  "js-optional-chaining": [
    "?.",
    "nullish",
    "undefined",
    "메서드 호출",
    "safe access",
    "optional chaining",
  ],
  "js-operators": ["+", "단항 +", "%", "**", "증가 연산자", "문자열 연결"],
  "js-switch": ["switch", "case", "default", "break", "fall-through", "==="],
  "js-types": ["number", "string", "boolean", "null", "undefined", "typeof"],
  "js-variables": ["let", "const", "var", "상수", "재할당", "하드코딩"],
};
