import type { PokemonSpecies } from "./types";

// 1세대 일반 종 137 마리 (스타터 9 + 전설 5 제외)
// 라인 단위로 그룹핑. evolutionLine 은 라인 시작 → 마지막.
// 이브이는 분기 진화라 nextEvolutionSpeciesId 는 null, branchEvolutionSpeciesIds 에 3 진화체 명시.

export const gen1NormalSpecies: PokemonSpecies[] = [
  // === 캐터피 라인 (10-12) ===
  {
    speciesId: "caterpie",
    dexNumber: 10,
    nameKo: "캐터피",
    nameEn: "Caterpie",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["caterpie", "metapod", "butterfree"],
    nextEvolutionSpeciesId: "metapod",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "metapod",
    dexNumber: 11,
    nameKo: "단데기",
    nameEn: "Metapod",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["caterpie", "metapod", "butterfree"],
    nextEvolutionSpeciesId: "butterfree",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "butterfree",
    dexNumber: 12,
    nameKo: "버터플",
    nameEn: "Butterfree",
    category: "normal",
    isStarter: false,
    evolutionStage: 3,
    evolutionLine: ["caterpie", "metapod", "butterfree"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 뿔충이 라인 (13-15) ===
  {
    speciesId: "weedle",
    dexNumber: 13,
    nameKo: "뿔충이",
    nameEn: "Weedle",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["weedle", "kakuna", "beedrill"],
    nextEvolutionSpeciesId: "kakuna",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "kakuna",
    dexNumber: 14,
    nameKo: "딱충이",
    nameEn: "Kakuna",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["weedle", "kakuna", "beedrill"],
    nextEvolutionSpeciesId: "beedrill",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "beedrill",
    dexNumber: 15,
    nameKo: "독침붕",
    nameEn: "Beedrill",
    category: "normal",
    isStarter: false,
    evolutionStage: 3,
    evolutionLine: ["weedle", "kakuna", "beedrill"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 구구 라인 (16-18) ===
  {
    speciesId: "pidgey",
    dexNumber: 16,
    nameKo: "구구",
    nameEn: "Pidgey",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["pidgey", "pidgeotto", "pidgeot"],
    nextEvolutionSpeciesId: "pidgeotto",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "pidgeotto",
    dexNumber: 17,
    nameKo: "피죤",
    nameEn: "Pidgeotto",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["pidgey", "pidgeotto", "pidgeot"],
    nextEvolutionSpeciesId: "pidgeot",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "pidgeot",
    dexNumber: 18,
    nameKo: "피죤투",
    nameEn: "Pidgeot",
    category: "normal",
    isStarter: false,
    evolutionStage: 3,
    evolutionLine: ["pidgey", "pidgeotto", "pidgeot"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 꼬렛 라인 (19-20) ===
  {
    speciesId: "rattata",
    dexNumber: 19,
    nameKo: "꼬렛",
    nameEn: "Rattata",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["rattata", "raticate"],
    nextEvolutionSpeciesId: "raticate",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "raticate",
    dexNumber: 20,
    nameKo: "레트라",
    nameEn: "Raticate",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["rattata", "raticate"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 깨비참 라인 (21-22) ===
  {
    speciesId: "spearow",
    dexNumber: 21,
    nameKo: "깨비참",
    nameEn: "Spearow",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["spearow", "fearow"],
    nextEvolutionSpeciesId: "fearow",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "fearow",
    dexNumber: 22,
    nameKo: "깨비드릴조",
    nameEn: "Fearow",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["spearow", "fearow"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 아보 라인 (23-24) ===
  {
    speciesId: "ekans",
    dexNumber: 23,
    nameKo: "아보",
    nameEn: "Ekans",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["ekans", "arbok"],
    nextEvolutionSpeciesId: "arbok",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "arbok",
    dexNumber: 24,
    nameKo: "아보크",
    nameEn: "Arbok",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["ekans", "arbok"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 피카츄 라인 (25-26) ===
  {
    speciesId: "pikachu",
    dexNumber: 25,
    nameKo: "피카츄",
    nameEn: "Pikachu",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["pikachu", "raichu"],
    nextEvolutionSpeciesId: "raichu",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "raichu",
    dexNumber: 26,
    nameKo: "라이츄",
    nameEn: "Raichu",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["pikachu", "raichu"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 모래두지 라인 (27-28) ===
  {
    speciesId: "sandshrew",
    dexNumber: 27,
    nameKo: "모래두지",
    nameEn: "Sandshrew",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["sandshrew", "sandslash"],
    nextEvolutionSpeciesId: "sandslash",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "sandslash",
    dexNumber: 28,
    nameKo: "고지",
    nameEn: "Sandslash",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["sandshrew", "sandslash"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 니드런♀ 라인 (29-31) ===
  {
    speciesId: "nidoran-f",
    dexNumber: 29,
    nameKo: "니드런♀",
    nameEn: "Nidoran♀",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["nidoran-f", "nidorina", "nidoqueen"],
    nextEvolutionSpeciesId: "nidorina",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "nidorina",
    dexNumber: 30,
    nameKo: "니드리나",
    nameEn: "Nidorina",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["nidoran-f", "nidorina", "nidoqueen"],
    nextEvolutionSpeciesId: "nidoqueen",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "nidoqueen",
    dexNumber: 31,
    nameKo: "니드퀸",
    nameEn: "Nidoqueen",
    category: "normal",
    isStarter: false,
    evolutionStage: 3,
    evolutionLine: ["nidoran-f", "nidorina", "nidoqueen"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 니드런♂ 라인 (32-34) ===
  {
    speciesId: "nidoran-m",
    dexNumber: 32,
    nameKo: "니드런♂",
    nameEn: "Nidoran♂",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["nidoran-m", "nidorino", "nidoking"],
    nextEvolutionSpeciesId: "nidorino",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "nidorino",
    dexNumber: 33,
    nameKo: "니드리노",
    nameEn: "Nidorino",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["nidoran-m", "nidorino", "nidoking"],
    nextEvolutionSpeciesId: "nidoking",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "nidoking",
    dexNumber: 34,
    nameKo: "니드킹",
    nameEn: "Nidoking",
    category: "normal",
    isStarter: false,
    evolutionStage: 3,
    evolutionLine: ["nidoran-m", "nidorino", "nidoking"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 삐삐 라인 (35-36) ===
  {
    speciesId: "clefairy",
    dexNumber: 35,
    nameKo: "삐삐",
    nameEn: "Clefairy",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["clefairy", "clefable"],
    nextEvolutionSpeciesId: "clefable",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "clefable",
    dexNumber: 36,
    nameKo: "픽시",
    nameEn: "Clefable",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["clefairy", "clefable"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 식스테일 라인 (37-38) ===
  {
    speciesId: "vulpix",
    dexNumber: 37,
    nameKo: "식스테일",
    nameEn: "Vulpix",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["vulpix", "ninetales"],
    nextEvolutionSpeciesId: "ninetales",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "ninetales",
    dexNumber: 38,
    nameKo: "나인테일",
    nameEn: "Ninetales",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["vulpix", "ninetales"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 푸린 라인 (39-40) ===
  {
    speciesId: "jigglypuff",
    dexNumber: 39,
    nameKo: "푸린",
    nameEn: "Jigglypuff",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["jigglypuff", "wigglytuff"],
    nextEvolutionSpeciesId: "wigglytuff",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "wigglytuff",
    dexNumber: 40,
    nameKo: "푸크린",
    nameEn: "Wigglytuff",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["jigglypuff", "wigglytuff"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 주뱃 라인 (41-42) ===
  {
    speciesId: "zubat",
    dexNumber: 41,
    nameKo: "주뱃",
    nameEn: "Zubat",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["zubat", "golbat"],
    nextEvolutionSpeciesId: "golbat",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "golbat",
    dexNumber: 42,
    nameKo: "골뱃",
    nameEn: "Golbat",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["zubat", "golbat"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 뚜벅쵸 라인 (43-45) ===
  {
    speciesId: "oddish",
    dexNumber: 43,
    nameKo: "뚜벅쵸",
    nameEn: "Oddish",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["oddish", "gloom", "vileplume"],
    nextEvolutionSpeciesId: "gloom",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "gloom",
    dexNumber: 44,
    nameKo: "냄새꼬",
    nameEn: "Gloom",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["oddish", "gloom", "vileplume"],
    nextEvolutionSpeciesId: "vileplume",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "vileplume",
    dexNumber: 45,
    nameKo: "라플레시아",
    nameEn: "Vileplume",
    category: "normal",
    isStarter: false,
    evolutionStage: 3,
    evolutionLine: ["oddish", "gloom", "vileplume"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 파라스 라인 (46-47) ===
  {
    speciesId: "paras",
    dexNumber: 46,
    nameKo: "파라스",
    nameEn: "Paras",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["paras", "parasect"],
    nextEvolutionSpeciesId: "parasect",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "parasect",
    dexNumber: 47,
    nameKo: "파라섹트",
    nameEn: "Parasect",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["paras", "parasect"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 콘팡 라인 (48-49) ===
  {
    speciesId: "venonat",
    dexNumber: 48,
    nameKo: "콘팡",
    nameEn: "Venonat",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["venonat", "venomoth"],
    nextEvolutionSpeciesId: "venomoth",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "venomoth",
    dexNumber: 49,
    nameKo: "도나리",
    nameEn: "Venomoth",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["venonat", "venomoth"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 디그다 라인 (50-51) ===
  {
    speciesId: "diglett",
    dexNumber: 50,
    nameKo: "디그다",
    nameEn: "Diglett",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["diglett", "dugtrio"],
    nextEvolutionSpeciesId: "dugtrio",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "dugtrio",
    dexNumber: 51,
    nameKo: "닥트리오",
    nameEn: "Dugtrio",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["diglett", "dugtrio"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 나옹 라인 (52-53) ===
  {
    speciesId: "meowth",
    dexNumber: 52,
    nameKo: "나옹",
    nameEn: "Meowth",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["meowth", "persian"],
    nextEvolutionSpeciesId: "persian",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "persian",
    dexNumber: 53,
    nameKo: "페르시온",
    nameEn: "Persian",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["meowth", "persian"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 고라파덕 라인 (54-55) ===
  {
    speciesId: "psyduck",
    dexNumber: 54,
    nameKo: "고라파덕",
    nameEn: "Psyduck",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["psyduck", "golduck"],
    nextEvolutionSpeciesId: "golduck",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "golduck",
    dexNumber: 55,
    nameKo: "골덕",
    nameEn: "Golduck",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["psyduck", "golduck"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 망키 라인 (56-57) ===
  {
    speciesId: "mankey",
    dexNumber: 56,
    nameKo: "망키",
    nameEn: "Mankey",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["mankey", "primeape"],
    nextEvolutionSpeciesId: "primeape",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "primeape",
    dexNumber: 57,
    nameKo: "성원숭",
    nameEn: "Primeape",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["mankey", "primeape"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 가디 라인 (58-59) ===
  {
    speciesId: "growlithe",
    dexNumber: 58,
    nameKo: "가디",
    nameEn: "Growlithe",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["growlithe", "arcanine"],
    nextEvolutionSpeciesId: "arcanine",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "arcanine",
    dexNumber: 59,
    nameKo: "윈디",
    nameEn: "Arcanine",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["growlithe", "arcanine"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 발챙이 라인 (60-62) ===
  {
    speciesId: "poliwag",
    dexNumber: 60,
    nameKo: "발챙이",
    nameEn: "Poliwag",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["poliwag", "poliwhirl", "poliwrath"],
    nextEvolutionSpeciesId: "poliwhirl",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "poliwhirl",
    dexNumber: 61,
    nameKo: "슈륙챙이",
    nameEn: "Poliwhirl",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["poliwag", "poliwhirl", "poliwrath"],
    nextEvolutionSpeciesId: "poliwrath",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "poliwrath",
    dexNumber: 62,
    nameKo: "강챙이",
    nameEn: "Poliwrath",
    category: "normal",
    isStarter: false,
    evolutionStage: 3,
    evolutionLine: ["poliwag", "poliwhirl", "poliwrath"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 캐이시 라인 (63-65) ===
  {
    speciesId: "abra",
    dexNumber: 63,
    nameKo: "캐이시",
    nameEn: "Abra",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["abra", "kadabra", "alakazam"],
    nextEvolutionSpeciesId: "kadabra",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "kadabra",
    dexNumber: 64,
    nameKo: "윤겔라",
    nameEn: "Kadabra",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["abra", "kadabra", "alakazam"],
    nextEvolutionSpeciesId: "alakazam",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "alakazam",
    dexNumber: 65,
    nameKo: "후딘",
    nameEn: "Alakazam",
    category: "normal",
    isStarter: false,
    evolutionStage: 3,
    evolutionLine: ["abra", "kadabra", "alakazam"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 알통몬 라인 (66-68) ===
  {
    speciesId: "machop",
    dexNumber: 66,
    nameKo: "알통몬",
    nameEn: "Machop",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["machop", "machoke", "machamp"],
    nextEvolutionSpeciesId: "machoke",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "machoke",
    dexNumber: 67,
    nameKo: "근육몬",
    nameEn: "Machoke",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["machop", "machoke", "machamp"],
    nextEvolutionSpeciesId: "machamp",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "machamp",
    dexNumber: 68,
    nameKo: "괴력몬",
    nameEn: "Machamp",
    category: "normal",
    isStarter: false,
    evolutionStage: 3,
    evolutionLine: ["machop", "machoke", "machamp"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 모다피 라인 (69-71) ===
  {
    speciesId: "bellsprout",
    dexNumber: 69,
    nameKo: "모다피",
    nameEn: "Bellsprout",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["bellsprout", "weepinbell", "victreebel"],
    nextEvolutionSpeciesId: "weepinbell",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "weepinbell",
    dexNumber: 70,
    nameKo: "우츠동",
    nameEn: "Weepinbell",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["bellsprout", "weepinbell", "victreebel"],
    nextEvolutionSpeciesId: "victreebel",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "victreebel",
    dexNumber: 71,
    nameKo: "우츠보트",
    nameEn: "Victreebel",
    category: "normal",
    isStarter: false,
    evolutionStage: 3,
    evolutionLine: ["bellsprout", "weepinbell", "victreebel"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 왕눈해 라인 (72-73) ===
  {
    speciesId: "tentacool",
    dexNumber: 72,
    nameKo: "왕눈해",
    nameEn: "Tentacool",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["tentacool", "tentacruel"],
    nextEvolutionSpeciesId: "tentacruel",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "tentacruel",
    dexNumber: 73,
    nameKo: "독파리",
    nameEn: "Tentacruel",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["tentacool", "tentacruel"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 꼬마돌 라인 (74-76) ===
  {
    speciesId: "geodude",
    dexNumber: 74,
    nameKo: "꼬마돌",
    nameEn: "Geodude",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["geodude", "graveler", "golem"],
    nextEvolutionSpeciesId: "graveler",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "graveler",
    dexNumber: 75,
    nameKo: "데구리",
    nameEn: "Graveler",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["geodude", "graveler", "golem"],
    nextEvolutionSpeciesId: "golem",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "golem",
    dexNumber: 76,
    nameKo: "딱구리",
    nameEn: "Golem",
    category: "normal",
    isStarter: false,
    evolutionStage: 3,
    evolutionLine: ["geodude", "graveler", "golem"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 포니타 라인 (77-78) ===
  {
    speciesId: "ponyta",
    dexNumber: 77,
    nameKo: "포니타",
    nameEn: "Ponyta",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["ponyta", "rapidash"],
    nextEvolutionSpeciesId: "rapidash",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "rapidash",
    dexNumber: 78,
    nameKo: "날쌩마",
    nameEn: "Rapidash",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["ponyta", "rapidash"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 야돈 라인 (79-80) ===
  {
    speciesId: "slowpoke",
    dexNumber: 79,
    nameKo: "야돈",
    nameEn: "Slowpoke",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["slowpoke", "slowbro"],
    nextEvolutionSpeciesId: "slowbro",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "slowbro",
    dexNumber: 80,
    nameKo: "야도란",
    nameEn: "Slowbro",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["slowpoke", "slowbro"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 코일 라인 (81-82) ===
  {
    speciesId: "magnemite",
    dexNumber: 81,
    nameKo: "코일",
    nameEn: "Magnemite",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["magnemite", "magneton"],
    nextEvolutionSpeciesId: "magneton",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "magneton",
    dexNumber: 82,
    nameKo: "레어코일",
    nameEn: "Magneton",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["magnemite", "magneton"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 파오리 (83) — 무진화 ===
  {
    speciesId: "farfetchd",
    dexNumber: 83,
    nameKo: "파오리",
    nameEn: "Farfetch'd",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["farfetchd"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 두두 라인 (84-85) ===
  {
    speciesId: "doduo",
    dexNumber: 84,
    nameKo: "두두",
    nameEn: "Doduo",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["doduo", "dodrio"],
    nextEvolutionSpeciesId: "dodrio",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "dodrio",
    dexNumber: 85,
    nameKo: "두트리오",
    nameEn: "Dodrio",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["doduo", "dodrio"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 쥬쥬 라인 (86-87) ===
  {
    speciesId: "seel",
    dexNumber: 86,
    nameKo: "쥬쥬",
    nameEn: "Seel",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["seel", "dewgong"],
    nextEvolutionSpeciesId: "dewgong",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "dewgong",
    dexNumber: 87,
    nameKo: "쥬레곤",
    nameEn: "Dewgong",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["seel", "dewgong"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 질퍽이 라인 (88-89) ===
  {
    speciesId: "grimer",
    dexNumber: 88,
    nameKo: "질퍽이",
    nameEn: "Grimer",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["grimer", "muk"],
    nextEvolutionSpeciesId: "muk",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "muk",
    dexNumber: 89,
    nameKo: "질뻐기",
    nameEn: "Muk",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["grimer", "muk"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 셀러 라인 (90-91) ===
  {
    speciesId: "shellder",
    dexNumber: 90,
    nameKo: "셀러",
    nameEn: "Shellder",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["shellder", "cloyster"],
    nextEvolutionSpeciesId: "cloyster",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "cloyster",
    dexNumber: 91,
    nameKo: "파르셀",
    nameEn: "Cloyster",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["shellder", "cloyster"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 고오스 라인 (92-94) ===
  {
    speciesId: "gastly",
    dexNumber: 92,
    nameKo: "고오스",
    nameEn: "Gastly",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["gastly", "haunter", "gengar"],
    nextEvolutionSpeciesId: "haunter",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "haunter",
    dexNumber: 93,
    nameKo: "고우스트",
    nameEn: "Haunter",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["gastly", "haunter", "gengar"],
    nextEvolutionSpeciesId: "gengar",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "gengar",
    dexNumber: 94,
    nameKo: "팬텀",
    nameEn: "Gengar",
    category: "normal",
    isStarter: false,
    evolutionStage: 3,
    evolutionLine: ["gastly", "haunter", "gengar"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 롱스톤 (95) — 무진화 ===
  {
    speciesId: "onix",
    dexNumber: 95,
    nameKo: "롱스톤",
    nameEn: "Onix",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["onix"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 슬리프 라인 (96-97) ===
  {
    speciesId: "drowzee",
    dexNumber: 96,
    nameKo: "슬리프",
    nameEn: "Drowzee",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["drowzee", "hypno"],
    nextEvolutionSpeciesId: "hypno",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "hypno",
    dexNumber: 97,
    nameKo: "슬리퍼",
    nameEn: "Hypno",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["drowzee", "hypno"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 크랩 라인 (98-99) ===
  {
    speciesId: "krabby",
    dexNumber: 98,
    nameKo: "크랩",
    nameEn: "Krabby",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["krabby", "kingler"],
    nextEvolutionSpeciesId: "kingler",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "kingler",
    dexNumber: 99,
    nameKo: "킹크랩",
    nameEn: "Kingler",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["krabby", "kingler"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 찌리리공 라인 (100-101) ===
  {
    speciesId: "voltorb",
    dexNumber: 100,
    nameKo: "찌리리공",
    nameEn: "Voltorb",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["voltorb", "electrode"],
    nextEvolutionSpeciesId: "electrode",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "electrode",
    dexNumber: 101,
    nameKo: "붐볼",
    nameEn: "Electrode",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["voltorb", "electrode"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 아라리 라인 (102-103) ===
  {
    speciesId: "exeggcute",
    dexNumber: 102,
    nameKo: "아라리",
    nameEn: "Exeggcute",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["exeggcute", "exeggutor"],
    nextEvolutionSpeciesId: "exeggutor",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "exeggutor",
    dexNumber: 103,
    nameKo: "나시",
    nameEn: "Exeggutor",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["exeggcute", "exeggutor"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 탕구리 라인 (104-105) ===
  {
    speciesId: "cubone",
    dexNumber: 104,
    nameKo: "탕구리",
    nameEn: "Cubone",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["cubone", "marowak"],
    nextEvolutionSpeciesId: "marowak",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "marowak",
    dexNumber: 105,
    nameKo: "텅구리",
    nameEn: "Marowak",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["cubone", "marowak"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 시라소몬 (106) — 무진화 ===
  {
    speciesId: "hitmonlee",
    dexNumber: 106,
    nameKo: "시라소몬",
    nameEn: "Hitmonlee",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["hitmonlee"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 홍수몬 (107) — 무진화 ===
  {
    speciesId: "hitmonchan",
    dexNumber: 107,
    nameKo: "홍수몬",
    nameEn: "Hitmonchan",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["hitmonchan"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 내루미 (108) — 무진화 ===
  {
    speciesId: "lickitung",
    dexNumber: 108,
    nameKo: "내루미",
    nameEn: "Lickitung",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["lickitung"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 또가스 라인 (109-110) ===
  {
    speciesId: "koffing",
    dexNumber: 109,
    nameKo: "또가스",
    nameEn: "Koffing",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["koffing", "weezing"],
    nextEvolutionSpeciesId: "weezing",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "weezing",
    dexNumber: 110,
    nameKo: "또도가스",
    nameEn: "Weezing",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["koffing", "weezing"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 뿔카노 라인 (111-112) ===
  {
    speciesId: "rhyhorn",
    dexNumber: 111,
    nameKo: "뿔카노",
    nameEn: "Rhyhorn",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["rhyhorn", "rhydon"],
    nextEvolutionSpeciesId: "rhydon",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "rhydon",
    dexNumber: 112,
    nameKo: "코뿌리",
    nameEn: "Rhydon",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["rhyhorn", "rhydon"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 무진화 묶음 (113-115) ===
  {
    speciesId: "chansey",
    dexNumber: 113,
    nameKo: "럭키",
    nameEn: "Chansey",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["chansey"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "tangela",
    dexNumber: 114,
    nameKo: "덩쿠리",
    nameEn: "Tangela",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["tangela"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "kangaskhan",
    dexNumber: 115,
    nameKo: "캥카",
    nameEn: "Kangaskhan",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["kangaskhan"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 쏘드라 라인 (116-117) ===
  {
    speciesId: "horsea",
    dexNumber: 116,
    nameKo: "쏘드라",
    nameEn: "Horsea",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["horsea", "seadra"],
    nextEvolutionSpeciesId: "seadra",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "seadra",
    dexNumber: 117,
    nameKo: "시드라",
    nameEn: "Seadra",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["horsea", "seadra"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 콘치 라인 (118-119) ===
  {
    speciesId: "goldeen",
    dexNumber: 118,
    nameKo: "콘치",
    nameEn: "Goldeen",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["goldeen", "seaking"],
    nextEvolutionSpeciesId: "seaking",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "seaking",
    dexNumber: 119,
    nameKo: "왕콘치",
    nameEn: "Seaking",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["goldeen", "seaking"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 별가사리 라인 (120-121) ===
  {
    speciesId: "staryu",
    dexNumber: 120,
    nameKo: "별가사리",
    nameEn: "Staryu",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["staryu", "starmie"],
    nextEvolutionSpeciesId: "starmie",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "starmie",
    dexNumber: 121,
    nameKo: "아쿠스타",
    nameEn: "Starmie",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["staryu", "starmie"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 무진화 묶음 (122-128) ===
  {
    speciesId: "mr-mime",
    dexNumber: 122,
    nameKo: "마임맨",
    nameEn: "Mr. Mime",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["mr-mime"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "scyther",
    dexNumber: 123,
    nameKo: "스라크",
    nameEn: "Scyther",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["scyther"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "jynx",
    dexNumber: 124,
    nameKo: "루주라",
    nameEn: "Jynx",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["jynx"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "electabuzz",
    dexNumber: 125,
    nameKo: "에레브",
    nameEn: "Electabuzz",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["electabuzz"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "magmar",
    dexNumber: 126,
    nameKo: "마그마",
    nameEn: "Magmar",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["magmar"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "pinsir",
    dexNumber: 127,
    nameKo: "쁘사이저",
    nameEn: "Pinsir",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["pinsir"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "tauros",
    dexNumber: 128,
    nameKo: "켄타로스",
    nameEn: "Tauros",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["tauros"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 잉어킹 라인 (129-130) ===
  {
    speciesId: "magikarp",
    dexNumber: 129,
    nameKo: "잉어킹",
    nameEn: "Magikarp",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["magikarp", "gyarados"],
    nextEvolutionSpeciesId: "gyarados",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "gyarados",
    dexNumber: 130,
    nameKo: "갸라도스",
    nameEn: "Gyarados",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["magikarp", "gyarados"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 라프라스 (131) — 무진화 ===
  {
    speciesId: "lapras",
    dexNumber: 131,
    nameKo: "라프라스",
    nameEn: "Lapras",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["lapras"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 메타몽 (132) — 무진화 ===
  {
    speciesId: "ditto",
    dexNumber: 132,
    nameKo: "메타몽",
    nameEn: "Ditto",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["ditto"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 이브이 분기 (133-136) ===
  // 이브이는 nextEvolutionSpeciesId 가 null 이고 branchEvolutionSpeciesIds 에 3 진화체.
  // 분기 진화 처리는 별도 로직 (이번 PR 범위 외 — Phase E 에서 evolveOptions 추가 예정).
  {
    speciesId: "eevee",
    dexNumber: 133,
    nameKo: "이브이",
    nameEn: "Eevee",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["eevee"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: ["vaporeon", "jolteon", "flareon"],
  },
  {
    speciesId: "vaporeon",
    dexNumber: 134,
    nameKo: "샤미드",
    nameEn: "Vaporeon",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["eevee", "vaporeon"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "jolteon",
    dexNumber: 135,
    nameKo: "쥬피썬더",
    nameEn: "Jolteon",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["eevee", "jolteon"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "flareon",
    dexNumber: 136,
    nameKo: "부스터",
    nameEn: "Flareon",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["eevee", "flareon"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 폴리곤 (137) — 무진화 (1세대 기준) ===
  {
    speciesId: "porygon",
    dexNumber: 137,
    nameKo: "폴리곤",
    nameEn: "Porygon",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["porygon"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 암나이트 라인 (138-139) ===
  {
    speciesId: "omanyte",
    dexNumber: 138,
    nameKo: "암나이트",
    nameEn: "Omanyte",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["omanyte", "omastar"],
    nextEvolutionSpeciesId: "omastar",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "omastar",
    dexNumber: 139,
    nameKo: "암스타",
    nameEn: "Omastar",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["omanyte", "omastar"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 투구 라인 (140-141) ===
  {
    speciesId: "kabuto",
    dexNumber: 140,
    nameKo: "투구",
    nameEn: "Kabuto",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["kabuto", "kabutops"],
    nextEvolutionSpeciesId: "kabutops",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "kabutops",
    dexNumber: 141,
    nameKo: "투구푸스",
    nameEn: "Kabutops",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["kabuto", "kabutops"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 프테라 (142) — 무진화 ===
  {
    speciesId: "aerodactyl",
    dexNumber: 142,
    nameKo: "프테라",
    nameEn: "Aerodactyl",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["aerodactyl"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 잠만보 (143) — 무진화 ===
  {
    speciesId: "snorlax",
    dexNumber: 143,
    nameKo: "잠만보",
    nameEn: "Snorlax",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["snorlax"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },

  // === 미뇽 라인 (147-149) ===
  {
    speciesId: "dratini",
    dexNumber: 147,
    nameKo: "미뇽",
    nameEn: "Dratini",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["dratini", "dragonair", "dragonite"],
    nextEvolutionSpeciesId: "dragonair",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "dragonair",
    dexNumber: 148,
    nameKo: "신뇽",
    nameEn: "Dragonair",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["dratini", "dragonair", "dragonite"],
    nextEvolutionSpeciesId: "dragonite",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "dragonite",
    dexNumber: 149,
    nameKo: "망나뇽",
    nameEn: "Dragonite",
    category: "normal",
    isStarter: false,
    evolutionStage: 3,
    evolutionLine: ["dratini", "dragonair", "dragonite"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },
];
