import type { PokemonSpecies } from "./types";

// 1세대 무진화 일반 종 (점진 추가 batch 1)
// evolutionLine 길이 1 + nextEvolutionSpeciesId null
export const nonEvolvingSpecies: PokemonSpecies[] = [
  {
    speciesId: "chansey",
    dexNumber: 113,
    nameKo: "럭키",
    nameEn: "Chansey",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["chansey"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "kangaskhan",
    dexNumber: 115,
    nameKo: "캥카",
    nameEn: "Kangaskhan",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["kangaskhan"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "tauros",
    dexNumber: 128,
    nameKo: "켄타로스",
    nameEn: "Tauros",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["tauros"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "lapras",
    dexNumber: 131,
    nameKo: "라프라스",
    nameEn: "Lapras",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["lapras"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "snorlax",
    dexNumber: 143,
    nameKo: "잠만보",
    nameEn: "Snorlax",
    category: "normal",
    isStarter: false,
    evolutionStage: 1,
    evolutionLine: ["snorlax"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },
];
