import type { PokemonSpecies } from "./types";

export const starters: PokemonSpecies[] = [
  {
    speciesId: "bulbasaur",
    dexNumber: 1,
    nameKo: "이상해씨",
    nameEn: "Bulbasaur",
    category: "normal",
    isStarter: true,
    evolutionStage: 1,
    evolutionLine: ["bulbasaur", "ivysaur", "venusaur"],
    nextEvolutionSpeciesId: "ivysaur",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "ivysaur",
    dexNumber: 2,
    nameKo: "이상해풀",
    nameEn: "Ivysaur",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["bulbasaur", "ivysaur", "venusaur"],
    nextEvolutionSpeciesId: "venusaur",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "venusaur",
    dexNumber: 3,
    nameKo: "이상해꽃",
    nameEn: "Venusaur",
    category: "normal",
    isStarter: false,
    evolutionStage: 3,
    evolutionLine: ["bulbasaur", "ivysaur", "venusaur"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "charmander",
    dexNumber: 4,
    nameKo: "파이리",
    nameEn: "Charmander",
    category: "normal",
    isStarter: true,
    evolutionStage: 1,
    evolutionLine: ["charmander", "charmeleon", "charizard"],
    nextEvolutionSpeciesId: "charmeleon",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "charmeleon",
    dexNumber: 5,
    nameKo: "리자드",
    nameEn: "Charmeleon",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["charmander", "charmeleon", "charizard"],
    nextEvolutionSpeciesId: "charizard",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "charizard",
    dexNumber: 6,
    nameKo: "리자몽",
    nameEn: "Charizard",
    category: "normal",
    isStarter: false,
    evolutionStage: 3,
    evolutionLine: ["charmander", "charmeleon", "charizard"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "squirtle",
    dexNumber: 7,
    nameKo: "꼬부기",
    nameEn: "Squirtle",
    category: "normal",
    isStarter: true,
    evolutionStage: 1,
    evolutionLine: ["squirtle", "wartortle", "blastoise"],
    nextEvolutionSpeciesId: "wartortle",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "wartortle",
    dexNumber: 8,
    nameKo: "어니부기",
    nameEn: "Wartortle",
    category: "normal",
    isStarter: false,
    evolutionStage: 2,
    evolutionLine: ["squirtle", "wartortle", "blastoise"],
    nextEvolutionSpeciesId: "blastoise",
    branchEvolutionSpeciesIds: [],
  },
  {
    speciesId: "blastoise",
    dexNumber: 9,
    nameKo: "거북왕",
    nameEn: "Blastoise",
    category: "normal",
    isStarter: false,
    evolutionStage: 3,
    evolutionLine: ["squirtle", "wartortle", "blastoise"],
    nextEvolutionSpeciesId: null,
    branchEvolutionSpeciesIds: [],
  },
];
