import type { QuestionPage } from "@/content/questions/types";

export const arrayBasics: QuestionPage = {
  sourceId: "array",
  title: "배열",
  url: "https://ko.javascript.info/array",
  questions: [
    {
      questionId: "array-yn-001",
      type: "yes_no",
      prompt: "배열은 순서가 있는 컬렉션을 저장할 때 자주 사용한다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-arrays",
      explanation: "배열은 인덱스를 통해 순서 있는 데이터를 저장하는 데 적합하다.",
      sourceExcerptId: "array-001",
    },
    {
      questionId: "array-yn-002",
      type: "yes_no",
      prompt: "배열의 첫 번째 요소 인덱스는 1이다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-arrays",
      explanation: "자바스크립트 배열 인덱스는 0부터 시작한다.",
      sourceExcerptId: "array-002",
    },
    {
      questionId: "array-yn-003",
      type: "yes_no",
      prompt: "배열 끝에 요소를 추가할 때 push를 사용할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-arrays",
      explanation: "push는 배열 마지막에 요소를 추가한다.",
      sourceExcerptId: "array-003",
    },
    {
      questionId: "array-mc-001",
      type: "multiple_choice",
      prompt: "배열 마지막 요소를 제거하고 반환하는 메서드는?",
      answer: "pop",
      choices: ["push", "shift", "unshift", "pop", "slice"],
      conceptGroup: "js-arrays",
      explanation: "pop은 배열의 마지막 요소를 제거하고 그 값을 반환한다.",
      sourceExcerptId: "array-004",
    },
    {
      questionId: "array-mc-002",
      type: "multiple_choice",
      prompt: "배열 앞쪽에 요소를 추가하는 메서드는?",
      answer: "unshift",
      choices: ["push", "pop", "shift", "unshift", "concat"],
      conceptGroup: "js-arrays",
      explanation: "unshift는 배열 맨 앞에 요소를 추가한다.",
      sourceExcerptId: "array-005",
    },
    {
      questionId: "array-mc-003",
      type: "multiple_choice",
      prompt: "배열 길이를 나타내는 프로퍼티는?",
      answer: "length",
      choices: ["size", "count", "length", "index", "capacity"],
      conceptGroup: "js-arrays",
      explanation: "length는 배열 요소 개수와 관련된 길이 정보를 나타낸다.",
      sourceExcerptId: "array-006",
    },
    {
      questionId: "array-fb-001",
      type: "fill_blank",
      prompt: "배열의 첫 번째 요소 인덱스는 ____ 이다.",
      answer: "0",
      acceptedAnswers: ["0", "zero"],
      conceptGroup: "js-arrays",
      explanation: "배열 인덱스는 0부터 시작한다.",
      sourceExcerptId: "array-002",
    },
    {
      questionId: "array-fb-002",
      type: "fill_blank",
      prompt: "배열 마지막에 요소를 추가하는 메서드는 ____ 이다.",
      answer: "push",
      acceptedAnswers: ["push"],
      conceptGroup: "js-arrays",
      explanation: "push는 배열 끝에 요소를 추가한다.",
      sourceExcerptId: "array-003",
    },
    {
      questionId: "array-fb-003",
      type: "fill_blank",
      prompt: "배열 첫 요소를 제거하고 반환하는 메서드는 ____ 이다.",
      answer: "shift",
      acceptedAnswers: ["shift"],
      conceptGroup: "js-arrays",
      explanation: "shift는 배열 맨 앞 요소를 제거하고 반환한다.",
      sourceExcerptId: "array-005",
    },
  ],
};
