import type { QuestionPage } from "../types";

export const arrayMethods: QuestionPage = {
  sourceId: "array-methods",
  title: "배열과 메서드",
  url: "https://ko.javascript.info/array-methods",
  questions: [
    {
      questionId: "array-methods-yn-001",
      type: "yes_no",
      prompt: "map은 각 요소를 변환한 새 배열을 만든다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-array-methods",
      explanation: "map은 원본 배열 각 요소를 변환해 새 배열을 반환한다.",
      sourceExcerptId: "array-methods-001",
    },
    {
      questionId: "array-methods-yn-002",
      type: "yes_no",
      prompt: "filter는 조건을 통과한 요소만 모아 새 배열을 만든다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-array-methods",
      explanation: "filter는 콜백이 true를 반환한 요소만 새 배열에 담는다.",
      sourceExcerptId: "array-methods-002",
    },
    {
      questionId: "array-methods-yn-003",
      type: "yes_no",
      prompt: "slice는 원본 배열을 직접 수정한다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-array-methods",
      explanation: "slice는 원본을 유지한 채 일부를 복사한 새 배열을 반환한다.",
      sourceExcerptId: "array-methods-003",
    },
    {
      questionId: "array-methods-mc-001",
      type: "multiple_choice",
      prompt: "원본 배열을 수정하지 않고 일부를 잘라 새 배열을 반환하는 메서드는?",
      answer: "slice",
      choices: ["splice", "slice", "sort", "fill", "pop"],
      conceptGroup: "js-array-methods",
      explanation: "slice는 원본을 건드리지 않고 부분 배열을 복사한다.",
      sourceExcerptId: "array-methods-003",
    },
    {
      questionId: "array-methods-mc-002",
      type: "multiple_choice",
      prompt: "배열 요소 중 조건을 만족하는 첫 요소를 찾는 메서드는?",
      answer: "find",
      choices: ["map", "find", "reduce", "join", "reverse"],
      conceptGroup: "js-array-methods",
      explanation: "find는 조건을 만족하는 첫 요소를 반환한다.",
      sourceExcerptId: "array-methods-004",
    },
    {
      questionId: "array-methods-mc-003",
      type: "multiple_choice",
      prompt: "원본 배열 자체를 변경하며 요소를 제거/추가할 수 있는 메서드는?",
      answer: "splice",
      choices: ["slice", "splice", "concat", "map", "filter"],
      conceptGroup: "js-array-methods",
      explanation: "splice는 원본 배열을 직접 수정한다.",
      sourceExcerptId: "array-methods-005",
    },
    {
      questionId: "array-methods-fb-001",
      type: "fill_blank",
      prompt: "배열 각 요소를 변환해 새 배열을 만드는 메서드는 ____ 이다.",
      answer: "map",
      acceptedAnswers: ["map"],
      conceptGroup: "js-array-methods",
      explanation: "map은 요소별 변환 결과를 모아 새 배열을 반환한다.",
      sourceExcerptId: "array-methods-001",
    },
    {
      questionId: "array-methods-fb-002",
      type: "fill_blank",
      prompt: "조건을 통과한 요소만 남겨 새 배열을 만드는 메서드는 ____ 이다.",
      answer: "filter",
      acceptedAnswers: ["filter"],
      conceptGroup: "js-array-methods",
      explanation: "filter는 조건에 맞는 요소만 추려낸다.",
      sourceExcerptId: "array-methods-002",
    },
    {
      questionId: "array-methods-fb-003",
      type: "fill_blank",
      prompt: "원본 배열을 수정하며 요소를 추가/삭제할 수 있는 메서드는 ____ 이다.",
      answer: "splice",
      acceptedAnswers: ["splice"],
      conceptGroup: "js-array-methods",
      explanation: "splice는 원본 배열을 직접 변경하는 대표적인 메서드다.",
      sourceExcerptId: "array-methods-005",
    },
  ],
};
