import type { QuestionPage } from "../types";

export const arrowFunctionsBasics: QuestionPage = {
  sourceId: "arrow-functions-basics",
  title: "화살표 함수 기본",
  url: "https://ko.javascript.info/arrow-functions-basics",
  questions: [
    {
      questionId: "arrow-functions-basics-yn-001",
      type: "yes_no",
      prompt: "화살표 함수는 함수를 더 짧게 표현하는 문법이다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-arrow-functions",
      explanation: "화살표 함수는 간결한 함수 표현식 문법이다.",
      sourceExcerptId: "arrow-functions-001",
    },
    {
      questionId: "arrow-functions-basics-yn-002",
      type: "yes_no",
      prompt: "매개변수가 하나뿐이면 화살표 함수에서 괄호를 생략할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-arrow-functions",
      explanation: "매개변수가 하나일 때는 괄호를 생략할 수 있다.",
      sourceExcerptId: "arrow-functions-002",
    },
    {
      questionId: "arrow-functions-basics-yn-003",
      type: "yes_no",
      prompt: "본문이 한 줄 표현식이면 return 키워드 없이 값을 바로 반환할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-arrow-functions",
      explanation: "표현식 본문 화살표 함수는 결과를 암묵적으로 반환한다.",
      sourceExcerptId: "arrow-functions-003",
    },
    {
      questionId: "arrow-functions-basics-mc-001",
      type: "multiple_choice",
      prompt: "매개변수 하나를 받아 두 배를 반환하는 화살표 함수로 맞는 것은?",
      answer: "n => n * 2",
      choices: ["n => n * 2", "=> n * 2", "(n) -> n * 2", "function => n * 2", "n -> n * 2"],
      conceptGroup: "js-arrow-functions",
      explanation: "매개변수 하나면 `n => n * 2`처럼 쓸 수 있다.",
      sourceExcerptId: "arrow-functions-002",
    },
    {
      questionId: "arrow-functions-basics-mc-002",
      type: "multiple_choice",
      prompt: "화살표 함수 본문을 여러 줄 블록으로 쓸 때 무엇이 필요할 수 있는가?",
      answer: "중괄호와 return",
      choices: ["세미콜론만", "중괄호와 return", "break", "class", "case"],
      conceptGroup: "js-arrow-functions",
      explanation: "여러 줄 본문은 중괄호를 쓰고 필요하면 return을 명시한다.",
      sourceExcerptId: "arrow-functions-003",
    },
    {
      questionId: "arrow-functions-basics-mc-003",
      type: "multiple_choice",
      prompt: "매개변수가 없을 때 화살표 함수 문법으로 맞는 것은?",
      answer: "() => 42",
      choices: ["() => 42", "_ => 42", "=> 42", "{} => 42", "(=>) 42"],
      conceptGroup: "js-arrow-functions",
      explanation: "매개변수가 없으면 빈 괄호 `()`를 써야 한다.",
      sourceExcerptId: "arrow-functions-001",
    },
    {
      questionId: "arrow-functions-basics-fb-001",
      type: "fill_blank",
      prompt: "화살표 함수에서 화살표 기호는 ____ 이다.",
      answer: "=>",
      acceptedAnswers: ["=>"],
      conceptGroup: "js-arrow-functions",
      explanation: "`=>`는 화살표 함수 문법의 핵심 기호다.",
      sourceExcerptId: "arrow-functions-001",
    },
    {
      questionId: "arrow-functions-basics-fb-002",
      type: "fill_blank",
      prompt: "본문이 한 줄 표현식이면 ____ 반환이 가능하다.",
      answer: "암묵적",
      acceptedAnswers: ["암묵적", "implicit"],
      conceptGroup: "js-arrow-functions",
      explanation: "한 줄 표현식은 return 없이 암묵적으로 반환된다.",
      sourceExcerptId: "arrow-functions-003",
    },
    {
      questionId: "arrow-functions-basics-fb-003",
      type: "fill_blank",
      prompt: "매개변수가 하나일 때는 매개변수 괄호를 ____ 할 수 있다.",
      answer: "생략",
      acceptedAnswers: ["생략", "omit"],
      conceptGroup: "js-arrow-functions",
      explanation: "매개변수 하나일 때는 괄호 생략이 가능하다.",
      sourceExcerptId: "arrow-functions-002",
    },
  ],
};
