import type { QuestionPage } from "@/content/questions/types";

export const asyncIteratorsGenerators: QuestionPage = {
  sourceId: "async-iterators-generators",
  title: "async 이터레이터와 제너레이터",
  url: "https://ko.javascript.info/async-iterators-generators",
  questions: [
    {
      questionId: "async-iterators-generators-yn-001",
      type: "yes_no",
      prompt: "비동기 이터러블은 Symbol.iterator 대신 Symbol.asyncIterator를 구현한다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-async-iterators",
      explanation:
        "비동기 이터러블은 Symbol.asyncIterator 메서드를 제공하고, next()는 Promise를 반환한다.",
      sourceExcerptId: "async-iterators-generators-001",
    },
    {
      questionId: "async-iterators-generators-yn-002",
      type: "yes_no",
      prompt: "비동기 이터러블은 일반 for...of 반복문으로 순회해야 한다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-async-iterators",
      explanation: "비동기 이터러블은 for await...of 반복문으로 순회한다.",
      sourceExcerptId: "async-iterators-generators-002",
    },
    {
      questionId: "async-iterators-generators-yn-003",
      type: "yes_no",
      prompt: "async function* 안에서는 await와 yield를 함께 사용할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-async-iterators",
      explanation:
        "async 제너레이터는 async function* 문법으로 만들며 내부에서 await 후 값을 yield할 수 있다.",
      sourceExcerptId: "async-iterators-generators-003",
    },
    {
      questionId: "async-iterators-generators-mc-001",
      type: "multiple_choice",
      prompt: "비동기 이터러블을 순회할 때 사용하는 반복문은?",
      answer: "for await...of",
      choices: ["for await...of", "for...in", "for...of", "while await", "async for"],
      conceptGroup: "js-async-iterators",
      explanation: "비동기 이터러블은 for await (let value of iterable) 형태로 순회한다.",
      sourceExcerptId: "async-iterators-generators-002",
    },
    {
      questionId: "async-iterators-generators-mc-002",
      type: "multiple_choice",
      prompt: "비동기 이터레이터를 제공하는 심볼은?",
      answer: "Symbol.asyncIterator",
      choices: [
        "Symbol.asyncIterator",
        "Symbol.iterator",
        "Symbol.toPrimitive",
        "Symbol.for",
        "Symbol.hasInstance",
      ],
      conceptGroup: "js-async-iterators",
      explanation: "객체를 비동기적으로 반복 가능하게 만들려면 Symbol.asyncIterator를 구현한다.",
      sourceExcerptId: "async-iterators-generators-001",
    },
    {
      questionId: "async-iterators-generators-mc-003",
      type: "multiple_choice",
      prompt: "async 제너레이터 함수의 올바른 선언 형태는?",
      answer: "async function*",
      choices: [
        "async function*",
        "function async*",
        "await function*",
        "function* async",
        "async generator",
      ],
      conceptGroup: "js-async-iterators",
      explanation: "async 제너레이터는 async function* 문법으로 선언한다.",
      sourceExcerptId: "async-iterators-generators-003",
    },
    {
      questionId: "async-iterators-generators-fb-001",
      type: "fill_blank",
      prompt: "비동기 이터러블은 Symbol.____ 를 구현한다.",
      answer: "asyncIterator",
      acceptedAnswers: ["asyncIterator", "Symbol.asyncIterator"],
      conceptGroup: "js-async-iterators",
      explanation: "비동기 이터러블은 Symbol.asyncIterator를 사용한다.",
      sourceExcerptId: "async-iterators-generators-001",
    },
    {
      questionId: "async-iterators-generators-fb-002",
      type: "fill_blank",
      prompt: "비동기 이터러블 순회에는 for ____...of 문을 사용한다.",
      answer: "await",
      acceptedAnswers: ["await"],
      conceptGroup: "js-async-iterators",
      explanation:
        "for await...of는 비동기 이터러블에서 Promise로 전달되는 값을 순서대로 기다린다.",
      sourceExcerptId: "async-iterators-generators-002",
    },
    {
      questionId: "async-iterators-generators-fb-003",
      type: "fill_blank",
      prompt: "async 제너레이터의 next() 결과를 받으려면 ____ 를 붙여 기다릴 수 있다.",
      answer: "await",
      acceptedAnswers: ["await"],
      conceptGroup: "js-async-iterators",
      explanation:
        "async 제너레이터의 next()는 Promise를 반환하므로 await generator.next()처럼 사용할 수 있다.",
      sourceExcerptId: "async-iterators-generators-004",
    },
  ],
};
