import type { QuestionPage } from "@/content/questions/types";

export const asyncAwait: QuestionPage = {
  sourceId: "async-await",
  title: "async와 await",
  url: "https://ko.javascript.info/async-await",
  questions: [
    {
      questionId: "async-await-yn-001",
      type: "yes_no",
      prompt: "async 함수는 항상 Promise를 반환한다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-async-await",
      explanation: "async 함수는 반환값이 Promise가 아니어도 이행된 Promise로 감싸 반환한다.",
      sourceExcerptId: "async-await-001",
    },
    {
      questionId: "async-await-yn-002",
      type: "yes_no",
      prompt: "await는 일반 함수 안에서도 자유롭게 사용할 수 있다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-async-await",
      explanation:
        "await는 async 함수 안에서 동작하며, 일반 함수 안에서 사용하면 문법 에러가 발생한다.",
      sourceExcerptId: "async-await-002",
    },
    {
      questionId: "async-await-yn-003",
      type: "yes_no",
      prompt: "await가 rejected Promise를 만나면 throw처럼 에러를 던진다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-async-await",
      explanation: "await promise가 거부되면 해당 에러가 던져지고 try...catch로 잡을 수 있다.",
      sourceExcerptId: "async-await-005",
    },
    {
      questionId: "async-await-mc-001",
      type: "multiple_choice",
      prompt: "함수가 항상 Promise를 반환하게 만드는 키워드는?",
      answer: "async",
      choices: ["async", "await", "then", "catch", "defer"],
      conceptGroup: "js-async-await",
      explanation: "function 앞의 async 키워드는 함수가 항상 Promise를 반환하게 한다.",
      sourceExcerptId: "async-await-001",
    },
    {
      questionId: "async-await-mc-002",
      type: "multiple_choice",
      prompt: "Promise가 처리될 때까지 async 함수 실행을 잠시 멈추고 결과를 받는 키워드는?",
      answer: "await",
      choices: ["await", "async", "yield", "return", "resolve"],
      conceptGroup: "js-async-await",
      explanation: "await는 Promise가 처리될 때까지 기다렸다가 이행 값이나 에러를 이어받는다.",
      sourceExcerptId: "async-await-002",
    },
    {
      questionId: "async-await-mc-003",
      type: "multiple_choice",
      prompt: "여러 비동기 작업이 모두 끝나길 async 함수 안에서 기다릴 때 함께 쓰기 좋은 메서드는?",
      answer: "Promise.all",
      choices: ["Promise.all", "Promise.race", "JSON.parse", "Object.create", "Array.from"],
      conceptGroup: "js-async-await",
      explanation:
        "여러 Promise를 모두 기다려야 할 때 Promise.all(...)에 await를 붙여 사용할 수 있다.",
      sourceExcerptId: "async-await-006",
    },
    {
      questionId: "async-await-fb-001",
      type: "fill_blank",
      prompt: "함수 앞에 ____ 키워드를 붙이면 항상 Promise를 반환한다.",
      answer: "async",
      acceptedAnswers: ["async"],
      conceptGroup: "js-async-await",
      explanation: "async 함수는 일반 값을 반환해도 Promise로 감싸 반환한다.",
      sourceExcerptId: "async-await-001",
    },
    {
      questionId: "async-await-fb-002",
      type: "fill_blank",
      prompt: "Promise 결과를 기다릴 때 사용하는 키워드는 ____ 이다.",
      answer: "await",
      acceptedAnswers: ["await"],
      conceptGroup: "js-async-await",
      explanation: "await는 Promise가 처리될 때까지 기다렸다가 결과를 반환한다.",
      sourceExcerptId: "async-await-002",
    },
    {
      questionId: "async-await-fb-003",
      type: "fill_blank",
      prompt: "await로 발생한 에러는 일반 에러처럼 try...____ 로 잡을 수 있다.",
      answer: "catch",
      acceptedAnswers: ["catch"],
      conceptGroup: "js-async-await",
      explanation: "await가 던진 에러는 try...catch 블록으로 처리할 수 있다.",
      sourceExcerptId: "async-await-005",
    },
  ],
};
