import type { QuestionPage } from "@/content/questions/types";

export const classInheritance: QuestionPage = {
  sourceId: "class-inheritance",
  title: "클래스 상속",
  url: "https://ko.javascript.info/class-inheritance",
  questions: [
    {
      questionId: "class-inheritance-yn-001",
      type: "yes_no",
      prompt: "extends 키워드는 한 클래스가 다른 클래스를 상속받도록 만든다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-class-inheritance",
      explanation: "class Child extends Parent 문법은 Child가 Parent를 상속하도록 연결한다.",
      sourceExcerptId: "class-inheritance-001",
    },
    {
      questionId: "class-inheritance-yn-002",
      type: "yes_no",
      prompt: "자식 클래스의 메서드에서 super.method()로 부모 메서드를 호출할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-class-inheritance",
      explanation: "super.method()는 부모 클래스의 메서드를 호출할 때 사용한다.",
      sourceExcerptId: "class-inheritance-002",
    },
    {
      questionId: "class-inheritance-yn-003",
      type: "yes_no",
      prompt: "상속받은 클래스의 constructor에서는 this를 쓰기 전에 super()를 호출해야 한다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-class-inheritance",
      explanation: "파생 클래스 constructor에서는 this 접근 전에 super()를 먼저 호출해야 한다.",
      sourceExcerptId: "class-inheritance-003",
    },
    {
      questionId: "class-inheritance-mc-001",
      type: "multiple_choice",
      prompt: "클래스 상속에 사용하는 키워드는?",
      answer: "extends",
      choices: ["extends", "implements", "inherits", "prototype", "super"],
      conceptGroup: "js-class-inheritance",
      explanation: "자바스크립트 클래스 상속은 extends 키워드로 표현한다.",
      sourceExcerptId: "class-inheritance-001",
    },
    {
      questionId: "class-inheritance-mc-002",
      type: "multiple_choice",
      prompt: "부모 클래스의 constructor를 호출할 때 사용하는 것은?",
      answer: "super()",
      choices: ["parent()", "base()", "super()", "constructor()", "extends()"],
      conceptGroup: "js-class-inheritance",
      explanation: "super()는 파생 클래스 constructor에서 부모 constructor를 호출한다.",
      sourceExcerptId: "class-inheritance-003",
    },
    {
      questionId: "class-inheritance-mc-003",
      type: "multiple_choice",
      prompt: "자식 클래스에서 부모 메서드를 확장해 재사용할 때 적절한 문법은?",
      answer: "super.method()",
      choices: [
        "this.parent()",
        "super.method()",
        "Parent.call()",
        "extends.method()",
        "constructor.method()",
      ],
      conceptGroup: "js-class-inheritance",
      explanation: "super.method()는 부모 메서드를 호출해 기존 동작을 재사용할 수 있게 한다.",
      sourceExcerptId: "class-inheritance-002",
    },
    {
      questionId: "class-inheritance-fb-001",
      type: "fill_blank",
      prompt: "클래스 상속은 class Child ____ Parent 문법으로 표현한다.",
      answer: "extends",
      acceptedAnswers: ["extends"],
      conceptGroup: "js-class-inheritance",
      explanation: "extends는 Child가 Parent를 상속받도록 지정한다.",
      sourceExcerptId: "class-inheritance-001",
    },
    {
      questionId: "class-inheritance-fb-002",
      type: "fill_blank",
      prompt: "파생 클래스 constructor에서 this를 쓰기 전에 호출해야 하는 것은 ____ 이다.",
      answer: "super()",
      acceptedAnswers: ["super()", "super"],
      conceptGroup: "js-class-inheritance",
      explanation: "파생 클래스에서는 super() 호출 전 this를 사용할 수 없다.",
      sourceExcerptId: "class-inheritance-003",
    },
    {
      questionId: "class-inheritance-fb-003",
      type: "fill_blank",
      prompt: "부모 메서드를 호출할 때는 ____ .method() 형태를 사용한다.",
      answer: "super",
      acceptedAnswers: ["super"],
      conceptGroup: "js-class-inheritance",
      explanation: "super.method()는 부모 클래스의 메서드를 호출한다.",
      sourceExcerptId: "class-inheritance-002",
    },
  ],
};
