import type { QuestionPage } from "@/content/questions/types";

export const classBasic: QuestionPage = {
  sourceId: "class",
  title: "클래스 기본 문법",
  url: "https://ko.javascript.info/class",
  questions: [
    {
      questionId: "class-basic-yn-001",
      type: "yes_no",
      prompt: "class 문법은 생성자 함수와 프로토타입 기반 동작을 더 깔끔하게 표현한다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-class-basic",
      explanation:
        "클래스는 내부적으로 프로토타입 기반 동작을 사용하면서 더 명확한 문법을 제공한다.",
      sourceExcerptId: "class-basic-001",
    },
    {
      questionId: "class-basic-yn-002",
      type: "yes_no",
      prompt: "class 안의 메서드는 기본적으로 prototype에 저장된다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-class-basic",
      explanation: "클래스 메서드는 인스턴스마다 복사되지 않고 클래스의 prototype에 저장된다.",
      sourceExcerptId: "class-basic-002",
    },
    {
      questionId: "class-basic-yn-003",
      type: "yes_no",
      prompt: "클래스 선언은 함수 선언처럼 선언 전에 자유롭게 사용할 수 있다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-class-basic",
      explanation:
        "클래스 선언은 호이스팅되지만 초기화 전에는 사용할 수 없어 선언 전에 접근하면 오류가 난다.",
      sourceExcerptId: "class-basic-003",
    },
    {
      questionId: "class-basic-mc-001",
      type: "multiple_choice",
      prompt: "클래스에서 인스턴스를 초기화할 때 자동으로 호출되는 메서드는?",
      answer: "constructor",
      choices: ["init", "constructor", "prototype", "new", "super"],
      conceptGroup: "js-class-basic",
      explanation: "constructor는 new로 인스턴스를 만들 때 초기화 로직을 실행한다.",
      sourceExcerptId: "class-basic-004",
    },
    {
      questionId: "class-basic-mc-002",
      type: "multiple_choice",
      prompt: "class User { sayHi() {} }에서 sayHi는 주로 어디에 저장되는가?",
      answer: "User.prototype",
      choices: ["User", "User.prototype", "각 인스턴스 내부", "Object.prototype", "window"],
      conceptGroup: "js-class-basic",
      explanation: "클래스의 일반 메서드는 User.prototype에 저장되어 인스턴스가 공유한다.",
      sourceExcerptId: "class-basic-002",
    },
    {
      questionId: "class-basic-mc-003",
      type: "multiple_choice",
      prompt: "클래스 인스턴스를 만들 때 사용하는 키워드는?",
      answer: "new",
      choices: ["new", "class", "extends", "constructor", "return"],
      conceptGroup: "js-class-basic",
      explanation: "클래스는 new와 함께 호출해 인스턴스를 만든다.",
      sourceExcerptId: "class-basic-005",
    },
    {
      questionId: "class-basic-fb-001",
      type: "fill_blank",
      prompt: "클래스 인스턴스 초기화 메서드 이름은 ____ 이다.",
      answer: "constructor",
      acceptedAnswers: ["constructor"],
      conceptGroup: "js-class-basic",
      explanation: "constructor는 인스턴스 생성 시 호출되는 초기화 메서드다.",
      sourceExcerptId: "class-basic-004",
    },
    {
      questionId: "class-basic-fb-002",
      type: "fill_blank",
      prompt: "class User의 일반 메서드는 보통 User.____ 에 저장된다.",
      answer: "prototype",
      acceptedAnswers: ["prototype", "User.prototype"],
      conceptGroup: "js-class-basic",
      explanation: "클래스 메서드는 prototype에 저장되어 인스턴스들이 공유한다.",
      sourceExcerptId: "class-basic-002",
    },
    {
      questionId: "class-basic-fb-003",
      type: "fill_blank",
      prompt: "클래스 인스턴스를 만들 때 `____ User()`처럼 호출한다.",
      answer: "new",
      acceptedAnswers: ["new"],
      conceptGroup: "js-class-basic",
      explanation: "클래스는 new 키워드와 함께 호출해 인스턴스를 생성한다.",
      sourceExcerptId: "class-basic-005",
    },
  ],
};
