import type { QuestionPage } from "@/content/questions/types";

export const comparison: QuestionPage = {
  sourceId: "comparison",
  title: "비교 연산자",
  url: "https://ko.javascript.info/comparison",
  questions: [
    {
      questionId: "comparison-yn-001",
      type: "yes_no",
      prompt: "비교 연산자의 결과는 boolean 값이다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-comparison",
      explanation: "비교 연산자는 true 또는 false를 반환한다.",
      sourceExcerptId: "comparison-001",
    },
    {
      questionId: "comparison-yn-002",
      type: "yes_no",
      prompt: "문자열 비교는 사전순으로 이루어진다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-comparison",
      explanation: "문자열은 유니코드 순서를 기반으로 사전식 비교를 한다.",
      sourceExcerptId: "comparison-002",
    },
    {
      questionId: "comparison-yn-003",
      type: "yes_no",
      prompt: "null == undefined 의 결과는 false다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-comparison",
      explanation: "느슨한 동등 비교에서 null과 undefined는 서로 같다고 취급된다.",
      sourceExcerptId: "comparison-003",
    },
    {
      questionId: "comparison-mc-001",
      type: "multiple_choice",
      prompt: "엄격한 동등 비교를 하는 연산자는?",
      answer: "===",
      choices: ["==", "===", "!=", "<=>", "="],
      conceptGroup: "js-comparison",
      explanation: "=== 는 타입 변환 없이 값을 비교하는 엄격한 동등 연산자다.",
      sourceExcerptId: "comparison-004",
    },
    {
      questionId: "comparison-mc-002",
      type: "multiple_choice",
      prompt: "다음 중 true가 되는 비교식은?",
      answer: '"a" < "b"',
      choices: ['"a" < "b"', '"bee" < "be"', "null > 0", "undefined == 0", '"2" === 2'],
      conceptGroup: "js-comparison",
      explanation: '"a"와 "b"는 문자열 사전순 비교에서 "a"가 더 앞서므로 true다.',
      sourceExcerptId: "comparison-002",
    },
    {
      questionId: "comparison-mc-003",
      type: "multiple_choice",
      prompt: "null과 undefined를 서로 같다고 보는 비교는?",
      answer: "null == undefined",
      choices: [
        "null == undefined",
        "null === undefined",
        "null > undefined",
        "undefined > null",
        "null == 0",
      ],
      conceptGroup: "js-comparison",
      explanation: "느슨한 동등 비교(==)에서는 null과 undefined가 서로 같다고 취급된다.",
      sourceExcerptId: "comparison-003",
    },
    {
      questionId: "comparison-fb-001",
      type: "fill_blank",
      prompt: "타입 변환 없이 값을 비교하는 연산자는 ____ 이다.",
      answer: "===",
      acceptedAnswers: ["===", '"==="', "'==='"],
      conceptGroup: "js-comparison",
      explanation: "=== 는 엄격한 동등 비교 연산자다.",
      sourceExcerptId: "comparison-004",
    },
    {
      questionId: "comparison-fb-002",
      type: "fill_blank",
      prompt: "문자열 비교는 보통 ____ 순으로 이루어진다.",
      answer: "사전",
      acceptedAnswers: ["사전", "사전식", "lexicographical", "사전순"],
      conceptGroup: "js-comparison",
      explanation: "문자열은 사전식 순서로 비교된다.",
      sourceExcerptId: "comparison-002",
    },
    {
      questionId: "comparison-fb-003",
      type: "multiple_choice",
      prompt: "느슨한 동등 비교(==)에서 특별히 서로 같다고 취급되는 값의 조합은?",
      answer: "null과 undefined",
      choices: ["null과 undefined", "0과 false", "빈 문자열과 false", "NaN과 NaN", "null과 0"],
      conceptGroup: "js-comparison",
      explanation: "null과 undefined는 == 비교에서만 특별하게 서로 같다고 취급된다.",
      sourceExcerptId: "comparison-003",
    },
  ],
};
