import type { QuestionPage } from "../types";

export const constructorNew: QuestionPage = {
  sourceId: "constructor-new",
  title: "생성자 함수와 new 연산자",
  url: "https://ko.javascript.info/constructor-new",
  questions: [
    {
      questionId: "constructor-new-yn-001",
      type: "yes_no",
      prompt: "관례상 생성자 함수 이름은 대문자로 시작한다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-constructor-new",
      explanation: "생성자 함수는 일반 함수와 구분하기 위해 대문자로 시작하는 관례가 있다.",
      sourceExcerptId: "constructor-new-001",
    },
    {
      questionId: "constructor-new-yn-002",
      type: "yes_no",
      prompt: "new와 함께 함수를 호출하면 보통 새로운 객체가 만들어진다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-constructor-new",
      explanation: "new 호출은 새 객체를 만들고 this에 바인딩하는 흐름으로 동작한다.",
      sourceExcerptId: "constructor-new-002",
    },
    {
      questionId: "constructor-new-yn-003",
      type: "yes_no",
      prompt: "생성자 함수 안에서 return으로 원시값을 명시하면 그 원시값이 최종 결과가 된다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-constructor-new",
      explanation: "생성자 함수가 원시값을 return하면 무시되고, 보통 새 객체가 반환된다.",
      sourceExcerptId: "constructor-new-003",
    },
    {
      questionId: "constructor-new-mc-001",
      type: "multiple_choice",
      prompt: "new 호출 시 생성자 함수 내부 this는 무엇을 가리키는가?",
      answer: "새로 생성된 객체",
      choices: ["전역 객체", "새로 생성된 객체", "함수 자신", "undefined", "prototype 객체"],
      conceptGroup: "js-constructor-new",
      explanation: "new 호출 시 this는 새로 만들어지는 객체를 가리킨다.",
      sourceExcerptId: "constructor-new-002",
    },
    {
      questionId: "constructor-new-mc-002",
      type: "multiple_choice",
      prompt: "다음 중 생성자 함수 호출 예시로 맞는 것은?",
      answer: "new User()",
      choices: ["User.new()", "new User()", "User=>()", "create User()", "User[]"],
      conceptGroup: "js-constructor-new",
      explanation: "생성자 함수는 `new User()`처럼 호출한다.",
      sourceExcerptId: "constructor-new-001",
    },
    {
      questionId: "constructor-new-mc-003",
      type: "multiple_choice",
      prompt: "생성자 함수가 객체를 명시적으로 return하면 어떻게 되는가?",
      answer: "그 객체가 반환된다",
      choices: [
        "에러가 발생한다",
        "항상 무시된다",
        "그 객체가 반환된다",
        "undefined가 반환된다",
        "prototype이 반환된다",
      ],
      conceptGroup: "js-constructor-new",
      explanation: "생성자 함수에서 객체를 명시적으로 반환하면 그 객체가 최종 결과가 된다.",
      sourceExcerptId: "constructor-new-003",
    },
    {
      questionId: "constructor-new-fb-001",
      type: "fill_blank",
      prompt: "생성자 함수 호출에 사용하는 키워드는 ____ 이다.",
      answer: "new",
      acceptedAnswers: ["new"],
      conceptGroup: "js-constructor-new",
      explanation: "new는 생성자 함수를 통해 새 객체를 만들 때 쓰는 키워드다.",
      sourceExcerptId: "constructor-new-002",
    },
    {
      questionId: "constructor-new-fb-002",
      type: "fill_blank",
      prompt: "생성자 함수 안에서 새 객체를 가리키는 것은 ____ 이다.",
      answer: "this",
      acceptedAnswers: ["this"],
      conceptGroup: "js-constructor-new",
      explanation: "new 호출에서는 this가 새 객체에 바인딩된다.",
      sourceExcerptId: "constructor-new-002",
    },
    {
      questionId: "constructor-new-fb-003",
      type: "fill_blank",
      prompt: "생성자 함수 이름은 보통 ____ 문자로 시작한다.",
      answer: "대문자",
      acceptedAnswers: ["대문자", "uppercase"],
      conceptGroup: "js-constructor-new",
      explanation: "생성자 함수는 대문자로 시작하는 관례를 따른다.",
      sourceExcerptId: "constructor-new-001",
    },
  ],
};
