import type { QuestionPage } from "../types";

export const dateBasics: QuestionPage = {
  sourceId: "date",
  title: "Date와 시간",
  url: "https://ko.javascript.info/date",
  questions: [
    {
      questionId: "date-yn-001",
      type: "yes_no",
      prompt: "new Date()는 현재 날짜와 시간을 담은 객체를 만든다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-date",
      explanation: "인수를 주지 않은 new Date()는 현재 시점을 기준으로 Date 객체를 만든다.",
      sourceExcerptId: "date-001",
    },
    {
      questionId: "date-yn-002",
      type: "yes_no",
      prompt: "getMonth()는 1월을 1로 반환한다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-date",
      explanation: "getMonth()는 1월을 0, 12월을 11로 반환한다.",
      sourceExcerptId: "date-002",
    },
    {
      questionId: "date-yn-003",
      type: "yes_no",
      prompt: "Date 객체는 내부적으로 타임스탬프를 기반으로 동작한다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-date",
      explanation: "Date는 1970-01-01 UTC 이후 흐른 밀리초 수를 기준으로 시간을 표현한다.",
      sourceExcerptId: "date-003",
    },
    {
      questionId: "date-mc-001",
      type: "multiple_choice",
      prompt: "1970-01-01 UTC 이후 흐른 밀리초 수를 무엇이라고 하는가?",
      answer: "타임스탬프",
      choices: ["타임존", "타임스탬프", "UTC offset", "locale", "epoch string"],
      conceptGroup: "js-date",
      explanation: "Date는 내부적으로 epoch 기준 밀리초 수, 즉 타임스탬프로 저장된다.",
      sourceExcerptId: "date-003",
    },
    {
      questionId: "date-mc-002",
      type: "multiple_choice",
      prompt: "월 값을 숫자로 얻을 때 주의해야 하는 점은?",
      answer: "0부터 시작한다",
      choices: [
        "1부터 시작한다",
        "0부터 시작한다",
        "요일을 함께 반환한다",
        "문자열로만 반환한다",
        "UTC만 지원한다",
      ],
      conceptGroup: "js-date",
      explanation: "getMonth()는 0부터 11까지의 값을 반환한다.",
      sourceExcerptId: "date-002",
    },
    {
      questionId: "date-mc-003",
      type: "multiple_choice",
      prompt: "현재 시점의 밀리초 타임스탬프를 얻을 때 가장 직접적인 방법은?",
      answer: "Date.now()",
      choices: [
        "new Date.getTime()",
        "Date.now()",
        "Date.parse()",
        "getMilliseconds()",
        "toISOString()",
      ],
      conceptGroup: "js-date",
      explanation: "Date.now()는 현재 시점의 타임스탬프를 바로 반환한다.",
      sourceExcerptId: "date-004",
    },
    {
      questionId: "date-fb-001",
      type: "fill_blank",
      prompt: "현재 시점의 Date 객체를 만들려면 new ____()를 사용한다.",
      answer: "Date",
      acceptedAnswers: ["Date", "new Date"],
      conceptGroup: "js-date",
      explanation: "new Date()는 현재 날짜와 시간을 담은 객체를 생성한다.",
      sourceExcerptId: "date-001",
    },
    {
      questionId: "date-fb-002",
      type: "fill_blank",
      prompt: "Date.now()는 현재 시점의 ____ 를 반환한다.",
      answer: "타임스탬프",
      acceptedAnswers: ["타임스탬프", "timestamp"],
      conceptGroup: "js-date",
      explanation: "Date.now()는 현재 시간을 밀리초 기반 타임스탬프로 반환한다.",
      sourceExcerptId: "date-004",
    },
    {
      questionId: "date-fb-003",
      type: "fill_blank",
      prompt: "getMonth()에서 1월은 숫자 ____ 으로 표현된다.",
      answer: "0",
      acceptedAnswers: ["0", "zero"],
      conceptGroup: "js-date",
      explanation: "getMonth()는 월을 0부터 세므로 1월은 0이다.",
      sourceExcerptId: "date-002",
    },
  ],
};
