import type { QuestionPage } from "../types";

export const destructuringAssignment: QuestionPage = {
  sourceId: "destructuring-assignment",
  title: "구조 분해 할당",
  url: "https://ko.javascript.info/destructuring-assignment",
  questions: [
    {
      questionId: "destructuring-assignment-yn-001",
      type: "yes_no",
      prompt: "배열 구조 분해로 배열 요소를 변수에 바로 할당할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-destructuring",
      explanation: "배열 구조 분해를 사용하면 배열 요소를 순서대로 변수에 할당할 수 있다.",
      sourceExcerptId: "destructuring-assignment-001",
    },
    {
      questionId: "destructuring-assignment-yn-002",
      type: "yes_no",
      prompt: "객체 구조 분해에서는 프로퍼티 이름과 변수 이름이 항상 같아야 한다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-destructuring",
      explanation: "객체 구조 분해에서는 `prop: localName` 형태로 다른 변수 이름을 사용할 수 있다.",
      sourceExcerptId: "destructuring-assignment-002",
    },
    {
      questionId: "destructuring-assignment-yn-003",
      type: "yes_no",
      prompt: "구조 분해에서 기본값을 지정할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-destructuring",
      explanation: "값이 없을 때 사용할 기본값을 구조 분해 패턴 안에서 지정할 수 있다.",
      sourceExcerptId: "destructuring-assignment-003",
    },
    {
      questionId: "destructuring-assignment-mc-001",
      type: "multiple_choice",
      prompt: "객체 구조 분해에서 `name: userName`의 의미는?",
      answer: "name 프로퍼티를 userName 변수에 할당",
      choices: [
        "userName 프로퍼티를 name 변수에 할당",
        "name 프로퍼티를 userName 변수에 할당",
        "name 값을 그대로 삭제",
        "name을 배열로 변환",
        "userName을 기본값으로 설정",
      ],
      conceptGroup: "js-destructuring",
      explanation: "객체 구조 분해에서 `prop: localName` 문법은 prop 값을 localName 변수에 담는다.",
      sourceExcerptId: "destructuring-assignment-002",
    },
    {
      questionId: "destructuring-assignment-mc-002",
      type: "multiple_choice",
      prompt: "배열 구조 분해에서 남은 요소를 묶을 때 사용하는 문법은?",
      answer: "...rest",
      choices: ["??", "...rest", "=>", "?.", "Object.entries"],
      conceptGroup: "js-destructuring",
      explanation: "rest 문법을 사용하면 남은 배열 요소를 하나의 배열로 모을 수 있다.",
      sourceExcerptId: "destructuring-assignment-004",
    },
    {
      questionId: "destructuring-assignment-mc-003",
      type: "multiple_choice",
      prompt: "객체 구조 분해 기본값은 언제 사용되는가?",
      answer: "해당 값이 없거나 undefined일 때",
      choices: [
        "항상",
        "해당 값이 null일 때만",
        "해당 값이 없거나 undefined일 때",
        "값이 0일 때",
        "구조 분해가 실패할 때",
      ],
      conceptGroup: "js-destructuring",
      explanation: "기본값은 대상 값이 존재하지 않거나 undefined일 때 적용된다.",
      sourceExcerptId: "destructuring-assignment-003",
    },
    {
      questionId: "destructuring-assignment-fb-001",
      type: "fill_blank",
      prompt: "배열 구조 분해에서 남은 요소를 모으는 문법은 ____ 이다.",
      answer: "...rest",
      acceptedAnswers: ["...rest", "rest"],
      conceptGroup: "js-destructuring",
      explanation: "rest 문법은 남은 요소를 한 번에 모을 때 쓴다.",
      sourceExcerptId: "destructuring-assignment-004",
    },
    {
      questionId: "destructuring-assignment-fb-002",
      type: "fill_blank",
      prompt: "객체 구조 분해에서 다른 변수명으로 받으려면 `prop: ____` 형태를 사용한다.",
      answer: "localName",
      acceptedAnswers: ["localName", "새 변수명", "변수명"],
      conceptGroup: "js-destructuring",
      explanation: "객체 구조 분해는 `prop: localName` 형태로 변수명을 바꿔 받을 수 있다.",
      sourceExcerptId: "destructuring-assignment-002",
    },
    {
      questionId: "destructuring-assignment-fb-003",
      type: "fill_blank",
      prompt: "값이 없을 때 대비해 구조 분해 패턴 안에 넣는 것은 ____ 이다.",
      answer: "기본값",
      acceptedAnswers: ["기본값", "default value", "default"],
      conceptGroup: "js-destructuring",
      explanation: "구조 분해는 기본값을 함께 지정해 안전하게 값을 받을 수 있다.",
      sourceExcerptId: "destructuring-assignment-003",
    },
  ],
};
