import type { QuestionPage } from "../types";

export const extendNatives: QuestionPage = {
  sourceId: "extend-natives",
  title: "내장 클래스 확장하기",
  url: "https://ko.javascript.info/extend-natives",
  questions: [
    {
      questionId: "extend-natives-yn-001",
      type: "yes_no",
      prompt: "Array 같은 내장 클래스도 extends로 상속할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-extend-natives",
      explanation: "클래스 문법은 Array, Error 같은 내장 클래스를 상속하는 데에도 사용할 수 있다.",
      sourceExcerptId: "extend-natives-001",
    },
    {
      questionId: "extend-natives-yn-002",
      type: "yes_no",
      prompt: "내장 클래스를 상속한 객체는 부모 내장 클래스의 메서드를 사용할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-extend-natives",
      explanation: "Array를 상속한 클래스의 인스턴스는 배열 메서드를 사용할 수 있다.",
      sourceExcerptId: "extend-natives-002",
    },
    {
      questionId: "extend-natives-yn-003",
      type: "yes_no",
      prompt: "Symbol.species는 내장 클래스 상속에서 반환될 생성자를 조정할 때 사용할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-extend-natives",
      explanation:
        "Symbol.species는 map, filter 같은 메서드가 새 객체를 만들 때 사용할 생성자를 지정할 수 있다.",
      sourceExcerptId: "extend-natives-003",
    },
    {
      questionId: "extend-natives-mc-001",
      type: "multiple_choice",
      prompt: "배열을 상속하는 클래스 선언으로 맞는 것은?",
      answer: "class PowerArray extends Array",
      choices: [
        "class PowerArray inherit Array",
        "class PowerArray extends Array",
        "class PowerArray from Array",
        "class PowerArray super Array",
        "class PowerArray prototype Array",
      ],
      conceptGroup: "js-extend-natives",
      explanation: "내장 클래스도 일반 클래스처럼 extends 키워드로 상속할 수 있다.",
      sourceExcerptId: "extend-natives-001",
    },
    {
      questionId: "extend-natives-mc-002",
      type: "multiple_choice",
      prompt: "상속받은 배열 메서드가 새 객체를 만들 때 생성자를 정하는 데 관여하는 심볼은?",
      answer: "Symbol.species",
      choices: [
        "Symbol.iterator",
        "Symbol.species",
        "Symbol.toPrimitive",
        "Symbol.for",
        "Symbol.hasInstance",
      ],
      conceptGroup: "js-extend-natives",
      explanation: "Symbol.species는 파생 객체 생성 시 사용할 생성자를 커스터마이즈할 수 있다.",
      sourceExcerptId: "extend-natives-003",
    },
    {
      questionId: "extend-natives-mc-003",
      type: "multiple_choice",
      prompt: "Error를 상속한 커스텀 에러 클래스에서 자주 설정하는 프로퍼티는?",
      answer: "name",
      choices: ["length", "name", "species", "prototype", "iterator"],
      conceptGroup: "js-extend-natives",
      explanation: "커스텀 에러에서는 에러 종류를 구분하기 위해 name을 설정하는 패턴이 흔하다.",
      sourceExcerptId: "extend-natives-004",
    },
    {
      questionId: "extend-natives-fb-001",
      type: "fill_blank",
      prompt: "내장 클래스 상속도 class Child ____ Parent 문법을 사용한다.",
      answer: "extends",
      acceptedAnswers: ["extends"],
      conceptGroup: "js-extend-natives",
      explanation: "extends는 일반 클래스와 내장 클래스 상속 모두에 사용된다.",
      sourceExcerptId: "extend-natives-001",
    },
    {
      questionId: "extend-natives-fb-002",
      type: "fill_blank",
      prompt: "파생 배열 메서드의 반환 생성자를 조정하는 심볼은 Symbol.____ 이다.",
      answer: "species",
      acceptedAnswers: ["species", "Symbol.species"],
      conceptGroup: "js-extend-natives",
      explanation: "Symbol.species는 파생 객체 생성 시 사용할 생성자를 지정한다.",
      sourceExcerptId: "extend-natives-003",
    },
    {
      questionId: "extend-natives-fb-003",
      type: "fill_blank",
      prompt: "커스텀 에러 클래스는 보통 내장 ____ 클래스를 상속한다.",
      answer: "Error",
      acceptedAnswers: ["Error", "error"],
      conceptGroup: "js-extend-natives",
      explanation: "커스텀 에러는 Error를 상속해 에러 객체의 기본 동작을 재사용한다.",
      sourceExcerptId: "extend-natives-004",
    },
  ],
};
