import type { QuestionPage } from "../types";

export const firstSteps: QuestionPage = {
  sourceId: "first-steps",
  title: "자바스크립트의 기본",
  url: "https://ko.javascript.info/first-steps",
  questions: [
    {
      questionId: "first-steps-yn-001",
      type: "yes_no",
      prompt: "script 태그 안에 자바스크립트 코드를 작성할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-basics",
      explanation: "자바스크립트 코드는 HTML 문서의 script 태그 안에 직접 작성할 수 있다.",
      sourceExcerptId: "first-steps-001",
    },
    {
      questionId: "first-steps-yn-002",
      type: "yes_no",
      prompt: "let은 같은 이름의 변수를 같은 스코프에서 두 번 선언해도 된다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-basics",
      explanation: "let은 같은 스코프에서 같은 이름으로 중복 선언할 수 없다.",
      sourceExcerptId: "first-steps-002",
    },
    {
      questionId: "first-steps-yn-003",
      type: "yes_no",
      prompt: "const로 선언한 변수는 재할당할 수 없다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-basics",
      explanation: "const는 한 번 할당한 값을 다시 바꿀 수 없는 상수를 선언할 때 사용한다.",
      sourceExcerptId: "first-steps-003",
    },
    {
      questionId: "first-steps-mc-001",
      type: "multiple_choice",
      prompt: "자바스크립트에서 변수 선언에 사용하는 키워드가 아닌 것은?",
      answer: "value",
      choices: ["let", "const", "var", "value", "function"],
      conceptGroup: "js-basics",
      explanation: "value는 변수 선언 키워드가 아니다. 일반 식별자 이름으로만 사용할 수 있다.",
      sourceExcerptId: "first-steps-004",
    },
    {
      questionId: "first-steps-mc-002",
      type: "multiple_choice",
      prompt: "여러 단어로 된 변수명을 자바스크립트에서 보통 어떻게 작성하나?",
      answer: "camelCase",
      choices: ["snake_case", "PascalCase", "camelCase", "kebab-case", "UPPER_CASE"],
      conceptGroup: "js-basics",
      explanation: "여러 단어를 붙인 변수명은 보통 camelCase 규칙을 사용한다.",
      sourceExcerptId: "first-steps-005",
    },
    {
      questionId: "first-steps-mc-003",
      type: "multiple_choice",
      prompt: "strict mode를 활성화할 때 사용하는 지시문은?",
      answer: '"use strict";',
      choices: ['"use strict";', '"strict mode";', '"enable strict";', '"use js";', '"safe mode";'],
      conceptGroup: "js-basics",
      explanation: 'strict mode는 파일이나 함수 상단에 "use strict"; 를 적어 활성화한다.',
      sourceExcerptId: "first-steps-006",
    },
    {
      questionId: "first-steps-fb-001",
      type: "fill_blank",
      prompt: "재할당할 수 없는 값을 선언할 때는 ____ 를 사용한다.",
      answer: "const",
      acceptedAnswers: ["const"],
      conceptGroup: "js-basics",
      explanation: "값을 다시 바꾸지 않을 변수는 const로 선언한다.",
      sourceExcerptId: "first-steps-003",
    },
    {
      questionId: "first-steps-fb-002",
      type: "fill_blank",
      prompt: "엄격 모드를 활성화하는 지시문은 ____ 이다.",
      answer: "use strict",
      acceptedAnswers: ["use strict", '"use strict"', "'use strict'"],
      conceptGroup: "js-basics",
      explanation: 'strict mode는 "use strict" 지시문으로 켠다.',
      sourceExcerptId: "first-steps-006",
    },
    {
      questionId: "first-steps-fb-003",
      type: "fill_blank",
      prompt: "여러 단어를 붙여 변수명을 만들 때 자주 쓰는 표기법은 ____ 이다.",
      answer: "camelCase",
      acceptedAnswers: ["camelcase", "camelCase"],
      conceptGroup: "js-basics",
      explanation: "자바스크립트 변수명은 일반적으로 camelCase 규칙을 따른다.",
      sourceExcerptId: "first-steps-005",
    },
  ],
};
