import type { QuestionPage } from "@/content/questions/types";

export const functionBasics: QuestionPage = {
  sourceId: "function-basics",
  title: "함수",
  url: "https://ko.javascript.info/function-basics",
  questions: [
    {
      questionId: "function-basics-yn-001",
      type: "yes_no",
      prompt: "함수는 한 번 정의해두고 여러 번 호출할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-functions",
      explanation: "함수는 재사용 가능한 코드 블록이다.",
      sourceExcerptId: "function-basics-001",
    },
    {
      questionId: "function-basics-yn-002",
      type: "yes_no",
      prompt: "함수 안에서 선언한 변수는 기본적으로 함수 바깥에서도 그대로 접근할 수 있다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-functions",
      explanation: "함수 내부 변수는 함수 스코프 안에서만 접근할 수 있다.",
      sourceExcerptId: "function-basics-002",
    },
    {
      questionId: "function-basics-yn-003",
      type: "yes_no",
      prompt: "return 문이 없으면 함수는 undefined를 반환한다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-functions",
      explanation: "return이 없으면 함수 결과는 undefined다.",
      sourceExcerptId: "function-basics-003",
    },
    {
      questionId: "function-basics-mc-001",
      type: "multiple_choice",
      prompt: "함수에 값을 전달받는 이름은?",
      answer: "매개변수",
      choices: ["매개변수", "반환값", "식별자", "프로퍼티", "인덱스"],
      conceptGroup: "js-functions",
      explanation: "함수 정의부에서 받는 이름은 매개변수(parameter)다.",
      sourceExcerptId: "function-basics-001",
    },
    {
      questionId: "function-basics-mc-002",
      type: "multiple_choice",
      prompt: "함수 실행을 즉시 끝내고 값을 돌려주는 키워드는?",
      answer: "return",
      choices: ["yield", "break", "continue", "return", "result"],
      conceptGroup: "js-functions",
      explanation: "return은 함수 실행을 종료하고 값을 반환한다.",
      sourceExcerptId: "function-basics-003",
    },
    {
      questionId: "function-basics-mc-003",
      type: "multiple_choice",
      prompt: "함수 내부에서 선언한 지역 변수를 설명하는 말로 맞는 것은?",
      answer: "함수 내부에서만 접근 가능하다",
      choices: [
        "함수 내부에서만 접근 가능하다",
        "프로그램 전체에서 항상 접근 가능하다",
        "return 문 뒤에서도 자동으로 유지된다",
        "객체 프로퍼티와 완전히 같다",
        "매개변수와는 함께 쓸 수 없다",
      ],
      conceptGroup: "js-functions",
      explanation: "지역 변수는 해당 함수 내부에서만 접근 가능하다.",
      sourceExcerptId: "function-basics-002",
    },
    {
      questionId: "function-basics-fb-001",
      type: "fill_blank",
      prompt: "함수 실행 결과를 돌려주는 키워드는 ____ 이다.",
      answer: "return",
      acceptedAnswers: ["return"],
      conceptGroup: "js-functions",
      explanation: "return은 함수 결과를 호출한 곳으로 돌려준다.",
      sourceExcerptId: "function-basics-003",
    },
    {
      questionId: "function-basics-fb-002",
      type: "fill_blank",
      prompt: "함수 안에서만 사용할 수 있는 변수를 ____ 변수라고 한다.",
      answer: "지역",
      acceptedAnswers: ["지역", "local"],
      conceptGroup: "js-functions",
      explanation: "함수 내부 변수는 지역 변수다.",
      sourceExcerptId: "function-basics-002",
    },
    {
      questionId: "function-basics-fb-003",
      type: "fill_blank",
      prompt: "함수 정의부에서 입력값을 받는 이름은 ____ 이다.",
      answer: "매개변수",
      acceptedAnswers: ["매개변수", "parameter"],
      conceptGroup: "js-functions",
      explanation: "함수에 전달되는 입력 이름은 매개변수다.",
      sourceExcerptId: "function-basics-001",
    },
  ],
};
