import type { QuestionPage } from "@/content/questions/types";

export const functionPrototype: QuestionPage = {
  sourceId: "function-prototype",
  title: "F.prototype",
  url: "https://ko.javascript.info/function-prototype",
  questions: [
    {
      questionId: "function-prototype-yn-001",
      type: "yes_no",
      prompt: "생성자 함수의 prototype 프로퍼티는 new로 만든 객체의 [[Prototype]]이 될 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-function-prototype",
      explanation: "new F()로 생성된 객체는 F.prototype을 자신의 [[Prototype]]으로 연결한다.",
      sourceExcerptId: "function-prototype-001",
    },
    {
      questionId: "function-prototype-yn-002",
      type: "yes_no",
      prompt: "F.prototype은 함수 객체 자신이 상속받는 프로토타입을 뜻한다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-function-prototype",
      explanation: "F.prototype은 new F()로 만들어질 객체의 프로토타입을 지정하는 일반 프로퍼티다.",
      sourceExcerptId: "function-prototype-002",
    },
    {
      questionId: "function-prototype-yn-003",
      type: "yes_no",
      prompt: "기본 prototype 객체에는 constructor 프로퍼티가 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-function-prototype",
      explanation: "기본 prototype 객체는 constructor 프로퍼티로 함수 자신을 가리킨다.",
      sourceExcerptId: "function-prototype-003",
    },
    {
      questionId: "function-prototype-mc-001",
      type: "multiple_choice",
      prompt: "new Rabbit()으로 만든 객체의 [[Prototype]]이 되는 값은?",
      answer: "Rabbit.prototype",
      choices: ["Rabbit", "Rabbit.prototype", "Rabbit.__proto__", "Object", "constructor"],
      conceptGroup: "js-function-prototype",
      explanation: "생성자 함수 Rabbit으로 만든 객체는 Rabbit.prototype을 프로토타입으로 사용한다.",
      sourceExcerptId: "function-prototype-001",
    },
    {
      questionId: "function-prototype-mc-002",
      type: "multiple_choice",
      prompt: "기본 prototype 객체의 constructor는 보통 무엇을 가리키는가?",
      answer: "생성자 함수 자신",
      choices: ["새 인스턴스", "생성자 함수 자신", "Object.prototype", "null", "__proto__"],
      conceptGroup: "js-function-prototype",
      explanation: "기본 prototype.constructor는 생성자 함수 자신을 참조한다.",
      sourceExcerptId: "function-prototype-003",
    },
    {
      questionId: "function-prototype-mc-003",
      type: "multiple_choice",
      prompt: "생성자 함수의 prototype을 다른 객체로 교체할 때 주의할 점은?",
      answer: "constructor 연결이 사라질 수 있다",
      choices: [
        "함수가 즉시 실행된다",
        "constructor 연결이 사라질 수 있다",
        "인스턴스가 모두 삭제된다",
        "this가 null이 된다",
        "prototype이 배열이 된다",
      ],
      conceptGroup: "js-function-prototype",
      explanation: "prototype 객체를 통째로 바꾸면 기본 constructor 프로퍼티가 없어질 수 있다.",
      sourceExcerptId: "function-prototype-004",
    },
    {
      questionId: "function-prototype-fb-001",
      type: "fill_blank",
      prompt: "new F()로 만든 객체의 프로토타입은 보통 F.____ 이다.",
      answer: "prototype",
      acceptedAnswers: ["prototype", "F.prototype"],
      conceptGroup: "js-function-prototype",
      explanation: "생성자 함수의 prototype 프로퍼티가 새 객체의 [[Prototype]]으로 연결된다.",
      sourceExcerptId: "function-prototype-001",
    },
    {
      questionId: "function-prototype-fb-002",
      type: "fill_blank",
      prompt: "기본 prototype 객체는 함수 자신을 가리키는 ____ 프로퍼티를 가진다.",
      answer: "constructor",
      acceptedAnswers: ["constructor"],
      conceptGroup: "js-function-prototype",
      explanation: "기본 prototype.constructor는 생성자 함수 자신을 참조한다.",
      sourceExcerptId: "function-prototype-003",
    },
    {
      questionId: "function-prototype-fb-003",
      type: "fill_blank",
      prompt: "F.prototype은 함수 자신의 [[Prototype]]이 아니라 새 ____ 의 [[Prototype]]을 정한다.",
      answer: "인스턴스",
      acceptedAnswers: ["인스턴스", "객체", "instance"],
      conceptGroup: "js-function-prototype",
      explanation: "F.prototype은 new F()로 만들어질 객체의 프로토타입을 지정한다.",
      sourceExcerptId: "function-prototype-002",
    },
  ],
};
