import type { QuestionPage } from "../types";

export const functionExpressions: QuestionPage = {
  sourceId: "function-expressions",
  title: "함수 표현식",
  url: "https://ko.javascript.info/function-expressions",
  questions: [
    {
      questionId: "function-expressions-yn-001",
      type: "yes_no",
      prompt: "함수 표현식은 값을 변수에 할당할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-function-expressions",
      explanation: "함수 표현식은 하나의 값처럼 변수에 담을 수 있다.",
      sourceExcerptId: "function-expressions-001",
    },
    {
      questionId: "function-expressions-yn-002",
      type: "yes_no",
      prompt:
        "함수 선언문은 정의보다 먼저 호출할 수 있지만, 함수 표현식은 보통 할당 이후에 호출해야 한다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-function-expressions",
      explanation: "함수 선언문과 달리 함수 표현식은 변수에 값이 들어간 뒤에 호출해야 안전하다.",
      sourceExcerptId: "function-expressions-002",
    },
    {
      questionId: "function-expressions-yn-003",
      type: "yes_no",
      prompt: "콜백 함수는 다른 함수에 전달되는 함수다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-function-expressions",
      explanation: "콜백은 함수에 인수로 전달되어 나중에 실행되는 함수다.",
      sourceExcerptId: "function-expressions-003",
    },
    {
      questionId: "function-expressions-mc-001",
      type: "multiple_choice",
      prompt: "다른 함수에 전달되어 나중에 실행되는 함수를 무엇이라 하는가?",
      answer: "콜백 함수",
      choices: ["콜백 함수", "지역 변수", "프로퍼티", "생성자", "리터럴"],
      conceptGroup: "js-function-expressions",
      explanation: "콜백 함수는 다른 함수에 전달되는 함수다.",
      sourceExcerptId: "function-expressions-003",
    },
    {
      questionId: "function-expressions-mc-002",
      type: "multiple_choice",
      prompt: "변수에 저장된 함수는 무엇의 예시인가?",
      answer: "함수 표현식",
      choices: ["함수 선언문", "함수 표현식", "반복문", "객체 리터럴", "조건문"],
      conceptGroup: "js-function-expressions",
      explanation: "함수를 값처럼 만들어 변수에 넣은 형태가 함수 표현식이다.",
      sourceExcerptId: "function-expressions-001",
    },
    {
      questionId: "function-expressions-mc-003",
      type: "multiple_choice",
      prompt: "함수 선언문과 함수 표현식의 차이로 맞는 것은?",
      answer: "함수 선언문은 정의 전에도 호출 가능하다",
      choices: [
        "함수 선언문은 정의 전에도 호출 가능하다",
        "함수 표현식은 return을 쓸 수 없다",
        "함수 선언문은 변수에 저장할 수 없다",
        "함수 표현식은 인수를 받을 수 없다",
        "함수 선언문은 값이 아니다",
      ],
      conceptGroup: "js-function-expressions",
      explanation: "함수 선언문은 호이스팅되어 정의 전 호출이 가능하다.",
      sourceExcerptId: "function-expressions-002",
    },
    {
      questionId: "function-expressions-fb-001",
      type: "fill_blank",
      prompt: "함수를 값처럼 변수에 저장한 형태를 함수 ____ 이라고 한다.",
      answer: "표현식",
      acceptedAnswers: ["표현식", "expression"],
      conceptGroup: "js-function-expressions",
      explanation: "값으로 다루는 함수 형태를 함수 표현식이라 한다.",
      sourceExcerptId: "function-expressions-001",
    },
    {
      questionId: "function-expressions-fb-002",
      type: "fill_blank",
      prompt: "다른 함수에 전달되어 실행되는 함수는 ____ 함수라고 한다.",
      answer: "콜백",
      acceptedAnswers: ["콜백", "callback"],
      conceptGroup: "js-function-expressions",
      explanation: "콜백 함수는 다른 함수가 호출해주는 함수다.",
      sourceExcerptId: "function-expressions-003",
    },
    {
      questionId: "function-expressions-fb-003",
      type: "fill_blank",
      prompt: "함수 선언문이 정의 전 호출 가능한 이유를 흔히 함수 ____ 이라고 설명한다.",
      answer: "호이스팅",
      acceptedAnswers: ["호이스팅", "hoisting"],
      conceptGroup: "js-function-expressions",
      explanation: "함수 선언문은 호이스팅되어 정의 전 호출이 가능하다.",
      sourceExcerptId: "function-expressions-002",
    },
  ],
};
