import type { QuestionPage } from "@/content/questions/types";

export const garbageCollection: QuestionPage = {
  sourceId: "garbage-collection",
  title: "가비지 컬렉션",
  url: "https://ko.javascript.info/garbage-collection",
  questions: [
    {
      questionId: "garbage-collection-yn-001",
      type: "yes_no",
      prompt:
        "자바스크립트 엔진은 도달할 수 없는 값(unreachable value)을 자동으로 정리하려고 한다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-garbage-collection",
      explanation: "가비지 컬렉션은 더 이상 도달할 수 없는 값을 자동으로 정리한다.",
      sourceExcerptId: "garbage-collection-001",
    },
    {
      questionId: "garbage-collection-yn-002",
      type: "yes_no",
      prompt: "전역 변수에서 참조되고 있으면 그 값은 여전히 도달 가능한 상태일 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-garbage-collection",
      explanation: "전역 변수나 실행 컨텍스트에서 닿을 수 있으면 reachable 상태다.",
      sourceExcerptId: "garbage-collection-002",
    },
    {
      questionId: "garbage-collection-yn-003",
      type: "yes_no",
      prompt:
        "객체끼리 서로 참조만 하고 있어도 외부에서 더 이상 도달할 수 없으면 수거 대상이 될 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-garbage-collection",
      explanation: "서로 참조하더라도 루트에서 닿지 못하면 가비지 컬렉션 대상이 된다.",
      sourceExcerptId: "garbage-collection-003",
    },
    {
      questionId: "garbage-collection-mc-001",
      type: "multiple_choice",
      prompt: "가비지 컬렉션의 핵심 기준은 무엇인가?",
      answer: "도달 가능성",
      choices: ["파일 크기", "도달 가능성", "생성 시각", "프로퍼티 개수", "함수 길이"],
      conceptGroup: "js-garbage-collection",
      explanation: "JS 엔진은 값이 reachable한지 여부를 기준으로 메모리 정리를 판단한다.",
      sourceExcerptId: "garbage-collection-001",
    },
    {
      questionId: "garbage-collection-mc-002",
      type: "multiple_choice",
      prompt: "외부에서 닿지 못하는 값의 상태를 가장 잘 설명한 것은?",
      answer: "unreachable",
      choices: ["strict", "falsy", "shallow", "unreachable", "enumerable"],
      conceptGroup: "js-garbage-collection",
      explanation: "더 이상 루트에서 닿지 못하면 unreachable 상태가 된다.",
      sourceExcerptId: "garbage-collection-001",
    },
    {
      questionId: "garbage-collection-mc-003",
      type: "multiple_choice",
      prompt: "서로만 참조하는 두 객체가 모두 수거될 수 있는 경우는?",
      answer: "루트 객체에서 더 이상 둘 다 참조하지 않을 때",
      choices: [
        "프로퍼티 이름이 같을 때",
        "루트 객체에서 더 이상 둘 다 참조하지 않을 때",
        "한 객체에 함수가 없을 때",
        "둘 중 하나가 const일 때",
        "둘 다 빈 객체일 때",
      ],
      conceptGroup: "js-garbage-collection",
      explanation: "상호 참조 자체가 아니라 루트에서 도달 가능한지가 기준이다.",
      sourceExcerptId: "garbage-collection-003",
    },
    {
      questionId: "garbage-collection-fb-001",
      type: "fill_blank",
      prompt: "가비지 컬렉션에서 더 이상 도달할 수 없는 값은 ____ 상태라고 한다.",
      answer: "unreachable",
      acceptedAnswers: ["unreachable"],
      conceptGroup: "js-garbage-collection",
      explanation: "unreachable 값은 수거 대상이 된다.",
      sourceExcerptId: "garbage-collection-001",
    },
    {
      questionId: "garbage-collection-fb-002",
      type: "fill_blank",
      prompt: "가비지 컬렉션의 기준이 되는 값의 상태는 ____ 가능성이다.",
      answer: "도달",
      acceptedAnswers: ["도달", "reachable"],
      conceptGroup: "js-garbage-collection",
      explanation: "도달 가능성은 가비지 컬렉션의 핵심 개념이다.",
      sourceExcerptId: "garbage-collection-001",
    },
    {
      questionId: "garbage-collection-fb-003",
      type: "fill_blank",
      prompt: "서로만 참조하는 객체라도 바깥에서 닿지 못하면 ____ 대상이 될 수 있다.",
      answer: "수거",
      acceptedAnswers: ["수거", "collection"],
      conceptGroup: "js-garbage-collection",
      explanation: "외부에서 도달할 수 없으면 상호 참조 객체도 수거될 수 있다.",
      sourceExcerptId: "garbage-collection-003",
    },
  ],
};
