import type { QuestionPage } from "@/content/questions/types";

export const generators: QuestionPage = {
  sourceId: "generators",
  title: "제너레이터",
  url: "https://ko.javascript.info/generators",
  questions: [
    {
      questionId: "generators-yn-001",
      type: "yes_no",
      prompt: "제너레이터 함수는 function* 문법으로 만들 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-generators",
      explanation:
        "제너레이터 함수는 function* 문법을 사용하며 호출 시 제너레이터 객체를 반환한다.",
      sourceExcerptId: "generators-001",
    },
    {
      questionId: "generators-yn-002",
      type: "yes_no",
      prompt: "제너레이터 함수를 호출하면 함수 본문이 즉시 끝까지 실행된다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-generators",
      explanation:
        "제너레이터 함수를 호출하면 본문이 바로 실행되지 않고 제너레이터 객체가 반환된다.",
      sourceExcerptId: "generators-002",
    },
    {
      questionId: "generators-yn-003",
      type: "yes_no",
      prompt: "제너레이터는 이터러블이므로 for...of로 순회할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-generators",
      explanation: "제너레이터 객체는 이터러블이기 때문에 for...of와 전개 문법에 사용할 수 있다.",
      sourceExcerptId: "generators-004",
    },
    {
      questionId: "generators-mc-001",
      type: "multiple_choice",
      prompt: "제너레이터에서 값을 바깥으로 산출하고 실행을 멈추는 키워드는?",
      answer: "yield",
      choices: ["yield", "return", "await", "break", "continue"],
      conceptGroup: "js-generators",
      explanation: "yield는 값을 바깥으로 전달하고 제너레이터 실행을 일시 중지한다.",
      sourceExcerptId: "generators-003",
    },
    {
      questionId: "generators-mc-002",
      type: "multiple_choice",
      prompt: "제너레이터의 다음 값을 요청할 때 사용하는 주요 메서드는?",
      answer: "next()",
      choices: ["next()", "run()", "yield()", "resume()", "iterate()"],
      conceptGroup: "js-generators",
      explanation: "generator.next()를 호출하면 다음 yield 지점까지 실행되고 결과 객체를 반환한다.",
      sourceExcerptId: "generators-003",
    },
    {
      questionId: "generators-mc-003",
      type: "multiple_choice",
      prompt: "다른 제너레이터의 산출값을 위임할 때 사용하는 문법은?",
      answer: "yield*",
      choices: ["yield*", "yield all", "return*", "next*", "for yield"],
      conceptGroup: "js-generators",
      explanation:
        "yield*는 다른 제너레이터나 이터러블에 산출을 위임하는 제너레이터 컴포지션 문법이다.",
      sourceExcerptId: "generators-006",
    },
    {
      questionId: "generators-fb-001",
      type: "fill_blank",
      prompt: "제너레이터 함수는 function____ 문법으로 선언한다.",
      answer: "*",
      acceptedAnswers: ["*", "function*", "function *"],
      conceptGroup: "js-generators",
      explanation: "function* 문법은 제너레이터 함수를 선언할 때 사용한다.",
      sourceExcerptId: "generators-001",
    },
    {
      questionId: "generators-fb-002",
      type: "fill_blank",
      prompt: "제너레이터의 next()는 value와 ____ 프로퍼티를 가진 객체를 반환한다.",
      answer: "done",
      acceptedAnswers: ["done"],
      conceptGroup: "js-generators",
      explanation: "next() 결과 객체는 산출값 value와 종료 여부 done을 가진다.",
      sourceExcerptId: "generators-003",
    },
    {
      questionId: "generators-fb-003",
      type: "fill_blank",
      prompt: "제너레이터 안으로 에러를 던질 때 사용할 수 있는 메서드는 generator.____ 이다.",
      answer: "throw",
      acceptedAnswers: ["throw", "throw()"],
      conceptGroup: "js-generators",
      explanation: "generator.throw(err)는 제너레이터의 현재 yield 위치로 에러를 던진다.",
      sourceExcerptId: "generators-007",
    },
  ],
};
