import type { QuestionPage } from "../types";

export const ifElse: QuestionPage = {
  sourceId: "ifelse",
  title: "if와 물음표 연산자",
  url: "https://ko.javascript.info/ifelse",
  questions: [
    {
      questionId: "ifelse-yn-001",
      type: "yes_no",
      prompt: "if 문의 조건식은 truthy/falsy 값으로 평가된다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-conditionals",
      explanation: "if 조건은 값이 truthy인지 falsy인지에 따라 분기된다.",
      sourceExcerptId: "ifelse-001",
    },
    {
      questionId: "ifelse-yn-002",
      type: "yes_no",
      prompt: "숫자 0은 if 조건식에서 truthy로 취급된다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-conditionals",
      explanation: "0은 대표적인 falsy 값이다.",
      sourceExcerptId: "ifelse-002",
    },
    {
      questionId: "ifelse-yn-003",
      type: "yes_no",
      prompt: "물음표 연산자는 단순한 조건 분기를 짧게 표현할 때 사용할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-conditionals",
      explanation: "조건 연산자(?:)는 간단한 분기를 짧게 표현할 때 자주 쓴다.",
      sourceExcerptId: "ifelse-003",
    },
    {
      questionId: "ifelse-mc-001",
      type: "multiple_choice",
      prompt: "다음 중 falsy 값인 것은?",
      answer: "0",
      choices: ["0", '"hello"', "[]", "{}", "1"],
      conceptGroup: "js-conditionals",
      explanation: "0은 falsy 값이다. 나머지는 모두 truthy로 취급된다.",
      sourceExcerptId: "ifelse-002",
    },
    {
      questionId: "ifelse-mc-002",
      type: "multiple_choice",
      prompt: "조건 연산자의 기본 형태는?",
      answer: "condition ? a : b",
      choices: [
        "condition ? a : b",
        "condition : a ? b",
        "condition ?? a :: b",
        "condition if a else b",
        "condition => a : b",
      ],
      conceptGroup: "js-conditionals",
      explanation: "조건 연산자는 condition ? a : b 형태를 가진다.",
      sourceExcerptId: "ifelse-003",
    },
    {
      questionId: "ifelse-mc-003",
      type: "multiple_choice",
      prompt: "if ... else if ... else 구조의 목적은?",
      answer: "여러 조건을 순서대로 검사하기 위해",
      choices: [
        "여러 조건을 순서대로 검사하기 위해",
        "반복문을 만들기 위해",
        "함수를 선언하기 위해",
        "객체를 생성하기 위해",
        "배열을 정렬하기 위해",
      ],
      conceptGroup: "js-conditionals",
      explanation: "else if는 여러 조건을 순서대로 나눠 검사할 때 사용한다.",
      sourceExcerptId: "ifelse-004",
    },
    {
      questionId: "ifelse-fb-001",
      type: "fill_blank",
      prompt: "조건이 참이면 A, 거짓이면 B를 선택하는 연산자는 ____ 연산자다.",
      answer: "물음표",
      acceptedAnswers: ["물음표", "조건", "ternary", "ternary operator"],
      conceptGroup: "js-conditionals",
      explanation: "?: 는 물음표 또는 조건 연산자라고 부른다.",
      sourceExcerptId: "ifelse-003",
    },
    {
      questionId: "ifelse-fb-002",
      type: "fill_blank",
      prompt: "if 조건문에서 0은 ____ 값으로 취급된다.",
      answer: "falsy",
      acceptedAnswers: ["falsy", "거짓", "false"],
      conceptGroup: "js-conditionals",
      explanation: "0은 falsy 값이라 if 조건에서 거짓처럼 동작한다.",
      sourceExcerptId: "ifelse-002",
    },
    {
      questionId: "ifelse-fb-003",
      type: "fill_blank",
      prompt: "여러 조건을 차례로 검사하고 싶을 때는 else ____ 를 사용할 수 있다.",
      answer: "if",
      acceptedAnswers: ["if", '"if"', "'if'"],
      conceptGroup: "js-conditionals",
      explanation: "여러 조건 분기는 else if 체인으로 표현할 수 있다.",
      sourceExcerptId: "ifelse-004",
    },
  ],
};
