import type { QuestionPage } from "../types";

export const importExport: QuestionPage = {
  sourceId: "import-export",
  title: "모듈 내보내고 가져오기",
  url: "https://ko.javascript.info/import-export",
  questions: [
    {
      questionId: "import-export-yn-001",
      type: "yes_no",
      prompt: "변수, 함수, 클래스 선언 앞에 export를 붙여 내보낼 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-import-export",
      explanation: "선언부 앞에 export를 붙이면 해당 선언을 다른 모듈에서 가져올 수 있다.",
      sourceExcerptId: "import-export-001",
    },
    {
      questionId: "import-export-yn-002",
      type: "yes_no",
      prompt: "named export를 가져올 때는 중괄호 없이 아무 이름으로나 가져올 수 있다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-import-export",
      explanation: "named export는 import { name } 형태로 내보낸 이름을 중괄호 안에 써서 가져온다.",
      sourceExcerptId: "import-export-006",
    },
    {
      questionId: "import-export-yn-003",
      type: "yes_no",
      prompt: "한 파일에는 default export가 최대 하나만 있을 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-import-export",
      explanation: "default export는 모듈의 기본 내보내기이며 파일당 하나만 둘 수 있다.",
      sourceExcerptId: "import-export-005",
    },
    {
      questionId: "import-export-mc-001",
      type: "multiple_choice",
      prompt: "모듈의 모든 named export를 객체로 가져오는 문법은?",
      answer: "import * as name",
      choices: [
        "import * as name",
        "export * as name",
        "import default as name",
        "require * from name",
        "include all as name",
      ],
      conceptGroup: "js-import-export",
      explanation:
        "import * as obj from './module.js' 형태로 모든 named export를 객체에 담아 가져올 수 있다.",
      sourceExcerptId: "import-export-002",
    },
    {
      questionId: "import-export-mc-002",
      type: "multiple_choice",
      prompt: "import나 export에서 이름을 바꿀 때 사용하는 키워드는?",
      answer: "as",
      choices: ["as", "from", "default", "with", "rename"],
      conceptGroup: "js-import-export",
      explanation:
        "as를 사용하면 import { old as new } 또는 export { old as new }처럼 별칭을 지정할 수 있다.",
      sourceExcerptId: "import-export-003",
    },
    {
      questionId: "import-export-mc-003",
      type: "multiple_choice",
      prompt: "default export를 가져올 때 named export와 다른 점은?",
      answer: "중괄호 없이 가져올 수 있다",
      choices: [
        "중괄호 없이 가져올 수 있다",
        "반드시 import * as를 써야 한다",
        "반드시 같은 이름으로 가져와야 한다",
        "한 파일에 여러 개 있어야 한다",
        "export 키워드 없이 가져온다",
      ],
      conceptGroup: "js-import-export",
      explanation: "default export는 import User from './user.js'처럼 중괄호 없이 가져올 수 있다.",
      sourceExcerptId: "import-export-005",
    },
    {
      questionId: "import-export-fb-001",
      type: "fill_blank",
      prompt: "다른 모듈에서 사용할 수 있게 값을 공개하는 키워드는 ____ 이다.",
      answer: "export",
      acceptedAnswers: ["export"],
      conceptGroup: "js-import-export",
      explanation: "export는 선언이나 값을 외부 모듈에서 가져갈 수 있게 공개한다.",
      sourceExcerptId: "import-export-001",
    },
    {
      questionId: "import-export-fb-002",
      type: "fill_blank",
      prompt: "ES 모듈에서 import/export 대상에 별칭을 붙일 때 사용하는 키워드는 ____ 이다.",
      answer: "as",
      acceptedAnswers: ["as"],
      conceptGroup: "js-import-export",
      explanation:
        "as는 import { old as new } 또는 export { old as new }처럼 모듈 import/export에서 별칭을 지정할 때 사용한다.",
      sourceExcerptId: "import-export-003",
    },
    {
      questionId: "import-export-fb-003",
      type: "fill_blank",
      prompt: "모듈에 하나의 대표 내보내기를 둘 때 export ____ 를 사용할 수 있다.",
      answer: "default",
      acceptedAnswers: ["default", "export default"],
      conceptGroup: "js-import-export",
      explanation: "export default는 모듈의 기본 내보내기를 지정하는 문법이다.",
      sourceExcerptId: "import-export-005",
    },
  ],
};
