import type { QuestionPage } from "../types";

export const instanceOf: QuestionPage = {
  sourceId: "instanceof",
  title: "instanceof로 클래스 확인하기",
  url: "https://ko.javascript.info/instanceof",
  questions: [
    {
      questionId: "instanceof-yn-001",
      type: "yes_no",
      prompt: "obj instanceof Class는 obj가 Class 또는 그 상속 체인에 속하는지 확인할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-instanceof",
      explanation: "instanceof는 생성자의 prototype이 객체의 프로토타입 체인에 있는지 확인한다.",
      sourceExcerptId: "instanceof-001",
    },
    {
      questionId: "instanceof-yn-002",
      type: "yes_no",
      prompt: "instanceof는 프로토타입 체인을 기준으로 판단한다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-instanceof",
      explanation: "instanceof는 객체의 [[Prototype]] 체인에서 생성자의 prototype을 찾는다.",
      sourceExcerptId: "instanceof-002",
    },
    {
      questionId: "instanceof-yn-003",
      type: "yes_no",
      prompt: "Symbol.hasInstance로 instanceof 동작을 커스터마이즈할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-instanceof",
      explanation:
        "클래스에 Symbol.hasInstance 메서드를 정의하면 instanceof 판정 방식을 바꿀 수 있다.",
      sourceExcerptId: "instanceof-003",
    },
    {
      questionId: "instanceof-mc-001",
      type: "multiple_choice",
      prompt: "`rabbit instanceof Rabbit`이 확인하는 핵심 관계는?",
      answer: "Rabbit.prototype이 rabbit의 프로토타입 체인에 있는지",
      choices: [
        "Rabbit.prototype이 rabbit의 프로토타입 체인에 있는지",
        "rabbit이 함수인지",
        "Rabbit이 배열인지",
        "rabbit의 모든 필드가 private인지",
        "Rabbit이 null인지",
      ],
      conceptGroup: "js-instanceof",
      explanation: "instanceof는 생성자의 prototype이 객체의 프로토타입 체인에 있는지 확인한다.",
      sourceExcerptId: "instanceof-002",
    },
    {
      questionId: "instanceof-mc-002",
      type: "multiple_choice",
      prompt: "instanceof 동작을 직접 바꿀 때 사용할 수 있는 심볼은?",
      answer: "Symbol.hasInstance",
      choices: [
        "Symbol.iterator",
        "Symbol.species",
        "Symbol.hasInstance",
        "Symbol.toPrimitive",
        "Symbol.for",
      ],
      conceptGroup: "js-instanceof",
      explanation:
        "Symbol.hasInstance는 instanceof 연산자의 판정 로직을 커스터마이즈하는 데 쓰인다.",
      sourceExcerptId: "instanceof-003",
    },
    {
      questionId: "instanceof-mc-003",
      type: "multiple_choice",
      prompt: "Array.isArray(value)가 instanceof Array보다 유리한 대표 상황은?",
      answer: "다른 실행 환경의 배열 판별",
      choices: [
        "숫자 덧셈",
        "다른 실행 환경의 배열 판별",
        "문자열 길이 확인",
        "private 필드 접근",
        "정적 메서드 호출",
      ],
      conceptGroup: "js-instanceof",
      explanation:
        "다른 window나 iframe에서 온 배열은 instanceof Array 판정이 기대와 다를 수 있어 Array.isArray가 더 안전하다.",
      sourceExcerptId: "instanceof-004",
    },
    {
      questionId: "instanceof-fb-001",
      type: "fill_blank",
      prompt: "객체가 특정 클래스의 인스턴스인지 확인하는 키워드는 ____ 이다.",
      answer: "instanceof",
      acceptedAnswers: ["instanceof"],
      conceptGroup: "js-instanceof",
      explanation: "instanceof는 객체와 생성자 함수 사이의 프로토타입 관계를 확인한다.",
      sourceExcerptId: "instanceof-001",
    },
    {
      questionId: "instanceof-fb-002",
      type: "fill_blank",
      prompt: "instanceof 커스터마이징에 쓰이는 심볼은 Symbol.____ 이다.",
      answer: "hasInstance",
      acceptedAnswers: ["hasInstance", "Symbol.hasInstance"],
      conceptGroup: "js-instanceof",
      explanation: "Symbol.hasInstance 메서드를 정의하면 instanceof 판정을 바꿀 수 있다.",
      sourceExcerptId: "instanceof-003",
    },
    {
      questionId: "instanceof-fb-003",
      type: "fill_blank",
      prompt: "배열 판별에는 Array.____(value)가 instanceof보다 안전한 경우가 있다.",
      answer: "isArray",
      acceptedAnswers: ["isArray", "Array.isArray"],
      conceptGroup: "js-instanceof",
      explanation: "Array.isArray는 실행 환경이 다른 배열도 안정적으로 판별할 수 있다.",
      sourceExcerptId: "instanceof-004",
    },
  ],
};
