import type { QuestionPage } from "@/content/questions/types";

export const iterable: QuestionPage = {
  sourceId: "iterable",
  title: "iterable 객체",
  url: "https://ko.javascript.info/iterable",
  questions: [
    {
      questionId: "iterable-yn-001",
      type: "yes_no",
      prompt: "for...of는 iterable 객체를 순회할 때 사용한다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-iterables",
      explanation: "for...of는 iterable 프로토콜을 따르는 객체를 순회한다.",
      sourceExcerptId: "iterable-001",
    },
    {
      questionId: "iterable-yn-002",
      type: "yes_no",
      prompt: "배열은 iterable 객체의 대표적인 예다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-iterables",
      explanation: "배열은 Symbol.iterator를 통해 iterable로 동작한다.",
      sourceExcerptId: "iterable-002",
    },
    {
      questionId: "iterable-yn-003",
      type: "yes_no",
      prompt: "일반 객체는 별도 구현 없이 항상 for...of로 바로 순회된다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-iterables",
      explanation: "일반 객체는 기본적으로 iterable이 아니므로 for...of로 바로 돌 수 없다.",
      sourceExcerptId: "iterable-003",
    },
    {
      questionId: "iterable-mc-001",
      type: "multiple_choice",
      prompt: "iterable 프로토콜에서 핵심이 되는 심볼 프로퍼티는?",
      answer: "Symbol.iterator",
      choices: ["Symbol.iterable", "Symbol.iterator", "Symbol.for", "Symbol.loop", "Symbol.each"],
      conceptGroup: "js-iterables",
      explanation: "iterable 객체는 Symbol.iterator 메서드를 제공해야 한다.",
      sourceExcerptId: "iterable-001",
    },
    {
      questionId: "iterable-mc-002",
      type: "multiple_choice",
      prompt: "iterator의 next() 호출 결과로 기대되는 형태는?",
      answer: "{ value, done }",
      choices: [
        "{ item, end }",
        "{ value, done }",
        "[value, done]",
        "{ key, next }",
        "{ current, stop }",
      ],
      conceptGroup: "js-iterables",
      explanation: "iterator의 next()는 보통 value와 done 프로퍼티를 가진 객체를 반환한다.",
      sourceExcerptId: "iterable-004",
    },
    {
      questionId: "iterable-mc-003",
      type: "multiple_choice",
      prompt: "문자열이 iterable이라는 점에서 가능한 것은?",
      answer: "for...of로 문자 단위 순회",
      choices: [
        "push로 문자 추가",
        "for...of로 문자 단위 순회",
        "항상 숫자로 변환",
        "Symbol 없이만 순회",
        "인덱스 없이 접근",
      ],
      conceptGroup: "js-iterables",
      explanation: "문자열은 iterable이라 for...of로 문자 하나씩 순회할 수 있다.",
      sourceExcerptId: "iterable-005",
    },
    {
      questionId: "iterable-fb-001",
      type: "fill_blank",
      prompt: "iterable 객체를 순회할 때 자주 쓰는 반복문은 for...____ 이다.",
      answer: "of",
      acceptedAnswers: ["of"],
      conceptGroup: "js-iterables",
      explanation: "for...of는 iterable 객체 순회에 특화돼 있다.",
      sourceExcerptId: "iterable-001",
    },
    {
      questionId: "iterable-fb-002",
      type: "fill_blank",
      prompt: "iterable 프로토콜의 핵심 심볼은 Symbol.____ 이다.",
      answer: "iterator",
      acceptedAnswers: ["iterator"],
      conceptGroup: "js-iterables",
      explanation: "iterable 객체는 Symbol.iterator 메서드를 가져야 한다.",
      sourceExcerptId: "iterable-001",
    },
    {
      questionId: "iterable-fb-003",
      type: "fill_blank",
      prompt: "iterator의 next() 결과 객체에서 순회 종료 여부를 나타내는 프로퍼티는 ____ 이다.",
      answer: "done",
      acceptedAnswers: ["done"],
      conceptGroup: "js-iterables",
      explanation: "done이 true면 순회가 끝났음을 의미한다.",
      sourceExcerptId: "iterable-004",
    },
  ],
};
