import type { QuestionPage } from "@/content/questions/types";

export const jsonBasics: QuestionPage = {
  sourceId: "json",
  title: "JSON 메서드, toJSON",
  url: "https://ko.javascript.info/json",
  questions: [
    {
      questionId: "json-yn-001",
      type: "yes_no",
      prompt: "JSON.stringify는 객체를 JSON 문자열로 바꾼다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-json",
      explanation: "JSON.stringify는 값을 JSON 형식 문자열로 직렬화한다.",
      sourceExcerptId: "json-001",
    },
    {
      questionId: "json-yn-002",
      type: "yes_no",
      prompt: "JSON.parse는 JSON 문자열 없이도 객체를 복사해준다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-json",
      explanation: "JSON.parse는 JSON 문자열을 받아 자바스크립트 값으로 역직렬화한다.",
      sourceExcerptId: "json-002",
    },
    {
      questionId: "json-yn-003",
      type: "yes_no",
      prompt: "toJSON 메서드가 있으면 JSON.stringify가 그 결과를 사용할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-json",
      explanation:
        "객체에 toJSON이 있으면 JSON.stringify는 해당 메서드 반환값을 직렬화에 사용한다.",
      sourceExcerptId: "json-003",
    },
    {
      questionId: "json-mc-001",
      type: "multiple_choice",
      prompt: "JSON 문자열을 다시 객체로 바꾸는 메서드는?",
      answer: "JSON.parse",
      choices: ["JSON.stringify", "JSON.parse", "Object.entries", "toString", "Date.parse"],
      conceptGroup: "js-json",
      explanation: "JSON.parse는 JSON 문자열을 자바스크립트 값으로 변환한다.",
      sourceExcerptId: "json-002",
    },
    {
      questionId: "json-mc-002",
      type: "multiple_choice",
      prompt: "JSON.stringify가 기본적으로 직렬화하지 못하는 값으로 가장 적절한 것은?",
      answer: "순환 참조 객체",
      choices: ["문자열", "숫자", "배열", "순환 참조 객체", "boolean"],
      conceptGroup: "js-json",
      explanation: "순환 참조가 있으면 JSON.stringify는 오류를 던진다.",
      sourceExcerptId: "json-004",
    },
    {
      questionId: "json-mc-003",
      type: "multiple_choice",
      prompt: "직렬화 전 값을 가공하는 두 번째 인수로 넘길 수 있는 것은?",
      answer: "replacer",
      choices: ["reviver", "replacer", "parser", "formatter", "serializer"],
      conceptGroup: "js-json",
      explanation: "JSON.stringify의 두 번째 인수 replacer로 직렬화 대상을 조정할 수 있다.",
      sourceExcerptId: "json-005",
    },
    {
      questionId: "json-fb-001",
      type: "fill_blank",
      prompt: "JSON 문자열을 객체로 되돌리는 메서드는 JSON.____ 이다.",
      answer: "parse",
      acceptedAnswers: ["parse", "JSON.parse"],
      conceptGroup: "js-json",
      explanation: "JSON.parse는 JSON 문자열을 자바스크립트 값으로 변환한다.",
      sourceExcerptId: "json-002",
    },
    {
      questionId: "json-fb-002",
      type: "fill_blank",
      prompt: "객체를 JSON 문자열로 바꾸는 메서드는 JSON.____ 이다.",
      answer: "stringify",
      acceptedAnswers: ["stringify", "JSON.stringify"],
      conceptGroup: "js-json",
      explanation: "JSON.stringify는 자바스크립트 값을 JSON 문자열로 직렬화한다.",
      sourceExcerptId: "json-001",
    },
    {
      questionId: "json-fb-003",
      type: "fill_blank",
      prompt: "JSON.stringify에서 사용자 정의 직렬화 결과를 제공하는 메서드는 ____ 이다.",
      answer: "toJSON",
      acceptedAnswers: ["toJSON"],
      conceptGroup: "js-json",
      explanation: "toJSON 메서드가 있으면 JSON.stringify가 그 반환값을 사용한다.",
      sourceExcerptId: "json-003",
    },
  ],
};
