import type { QuestionPage } from "../types";

export const logicalOperators: QuestionPage = {
  sourceId: "logical-operators",
  title: "논리 연산자",
  url: "https://ko.javascript.info/logical-operators",
  questions: [
    {
      questionId: "logical-operators-yn-001",
      type: "yes_no",
      prompt: "|| 연산자는 왼쪽 값이 truthy이면 그 값을 그대로 반환할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-logical-operators",
      explanation: "|| 는 첫 번째 truthy 값을 반환하고, 모두 falsy면 마지막 값을 반환한다.",
      sourceExcerptId: "logical-operators-001",
    },
    {
      questionId: "logical-operators-yn-002",
      type: "yes_no",
      prompt: "&& 연산자는 왼쪽 값이 falsy여도 오른쪽 표현식을 계속 평가한다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-logical-operators",
      explanation: "&& 는 첫 번째 falsy 값을 만나면 평가를 멈춘다.",
      sourceExcerptId: "logical-operators-002",
    },
    {
      questionId: "logical-operators-yn-003",
      type: "yes_no",
      prompt: "! 연산자를 두 번 쓰면 값을 boolean으로 바꾸는 데 활용할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-logical-operators",
      explanation: "!!value 는 값을 truthy/falsy 기준의 boolean으로 변환할 때 자주 쓴다.",
      sourceExcerptId: "logical-operators-003",
    },
    {
      questionId: "logical-operators-mc-001",
      type: "multiple_choice",
      prompt: "다음 중 첫 번째 truthy 값을 반환하는 연산자는?",
      answer: "||",
      choices: ["||", "&&", "!", "??", "?:"],
      conceptGroup: "js-logical-operators",
      explanation: "|| 는 왼쪽에서 오른쪽으로 보며 첫 번째 truthy 값을 반환한다.",
      sourceExcerptId: "logical-operators-001",
    },
    {
      questionId: "logical-operators-mc-002",
      type: "multiple_choice",
      prompt: "다음 중 첫 번째 falsy 값을 반환하거나, 모두 truthy면 마지막 값을 반환하는 연산자는?",
      answer: "&&",
      choices: ["||", "&&", "!", "==", "+"],
      conceptGroup: "js-logical-operators",
      explanation: "&& 는 첫 번째 falsy 값을 반환하고, 모두 truthy일 때만 마지막 값을 반환한다.",
      sourceExcerptId: "logical-operators-002",
    },
    {
      questionId: "logical-operators-mc-003",
      type: "multiple_choice",
      prompt: "boolean 값을 반대로 뒤집는 연산자는?",
      answer: "!",
      choices: ["!", "!!", "&&", "||", "~"],
      conceptGroup: "js-logical-operators",
      explanation: "! 는 truthy/falsy를 반전한 boolean 값을 만든다.",
      sourceExcerptId: "logical-operators-003",
    },
    {
      questionId: "logical-operators-fb-001",
      type: "fill_blank",
      prompt: "첫 번째 truthy 값을 찾는 논리 연산자는 ____ 이다.",
      answer: "||",
      acceptedAnswers: ["||", "or"],
      conceptGroup: "js-logical-operators",
      explanation: "|| 는 첫 번째 truthy 값을 찾는 데 자주 사용된다.",
      sourceExcerptId: "logical-operators-001",
    },
    {
      questionId: "logical-operators-fb-002",
      type: "fill_blank",
      prompt: "첫 번째 falsy 값을 찾는 논리 연산자는 ____ 이다.",
      answer: "&&",
      acceptedAnswers: ["&&", "and"],
      conceptGroup: "js-logical-operators",
      explanation: "&& 는 첫 번째 falsy 값을 기준으로 평가를 멈춘다.",
      sourceExcerptId: "logical-operators-002",
    },
    {
      questionId: "logical-operators-fb-003",
      type: "fill_blank",
      prompt: "값을 boolean으로 강제 변환할 때 자주 쓰는 표현은 ____ 이다.",
      answer: "!!",
      acceptedAnswers: ["!!", "double not"],
      conceptGroup: "js-logical-operators",
      explanation: "!!value 는 value를 boolean 값으로 바꾼다.",
      sourceExcerptId: "logical-operators-003",
    },
  ],
};
