import type { QuestionPage } from "../types";

export const mapSet: QuestionPage = {
  sourceId: "map-set",
  title: "Map과 Set",
  url: "https://ko.javascript.info/map-set",
  questions: [
    {
      questionId: "map-set-yn-001",
      type: "yes_no",
      prompt: "Map은 키로 문자열뿐 아니라 객체도 사용할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-map-set",
      explanation: "Map은 다양한 타입의 값을 키로 사용할 수 있다.",
      sourceExcerptId: "map-set-001",
    },
    {
      questionId: "map-set-yn-002",
      type: "yes_no",
      prompt: "Set은 중복 없는 값의 컬렉션을 저장할 때 유용하다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-map-set",
      explanation: "Set은 같은 값을 한 번만 저장하는 구조다.",
      sourceExcerptId: "map-set-002",
    },
    {
      questionId: "map-set-yn-003",
      type: "yes_no",
      prompt: "일반 객체와 달리 Map은 size 프로퍼티로 항목 수를 바로 알 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-map-set",
      explanation: "Map은 size 프로퍼티를 통해 저장된 항목 수를 제공한다.",
      sourceExcerptId: "map-set-003",
    },
    {
      questionId: "map-set-mc-001",
      type: "multiple_choice",
      prompt: "중복을 허용하지 않는 컬렉션은?",
      answer: "Set",
      choices: ["Map", "Set", "Object", "Array", "WeakMap"],
      conceptGroup: "js-map-set",
      explanation: "Set은 중복 없는 값 집합을 저장한다.",
      sourceExcerptId: "map-set-002",
    },
    {
      questionId: "map-set-mc-002",
      type: "multiple_choice",
      prompt: "Map에서 키에 대응하는 값을 저장할 때 쓰는 메서드는?",
      answer: "set",
      choices: ["add", "push", "set", "assign", "put"],
      conceptGroup: "js-map-set",
      explanation: "Map은 set(key, value)로 항목을 저장한다.",
      sourceExcerptId: "map-set-001",
    },
    {
      questionId: "map-set-mc-003",
      type: "multiple_choice",
      prompt: "Set에 값이 존재하는지 확인할 때 쓰는 메서드는?",
      answer: "has",
      choices: ["get", "find", "has", "contains", "check"],
      conceptGroup: "js-map-set",
      explanation: "Set은 has(value)로 값 존재 여부를 확인한다.",
      sourceExcerptId: "map-set-002",
    },
    {
      questionId: "map-set-fb-001",
      type: "fill_blank",
      prompt: "키-값 쌍을 저장하는 컬렉션은 ____ 이다.",
      answer: "Map",
      acceptedAnswers: ["Map"],
      conceptGroup: "js-map-set",
      explanation: "Map은 키-값 쌍 저장에 특화된 컬렉션이다.",
      sourceExcerptId: "map-set-001",
    },
    {
      questionId: "map-set-fb-002",
      type: "fill_blank",
      prompt: "중복 없는 값 집합을 저장하는 컬렉션은 ____ 이다.",
      answer: "Set",
      acceptedAnswers: ["Set"],
      conceptGroup: "js-map-set",
      explanation: "Set은 중복 없는 값 집합을 표현한다.",
      sourceExcerptId: "map-set-002",
    },
    {
      questionId: "map-set-fb-003",
      type: "fill_blank",
      prompt: "Map의 항목 개수를 알려주는 프로퍼티는 ____ 이다.",
      answer: "size",
      acceptedAnswers: ["size"],
      conceptGroup: "js-map-set",
      explanation: "Map은 size로 저장된 항목 수를 제공한다.",
      sourceExcerptId: "map-set-003",
    },
  ],
};
