import type { QuestionPage } from "@/content/questions/types";

export const mixins: QuestionPage = {
  sourceId: "mixins",
  title: "믹스인",
  url: "https://ko.javascript.info/mixins",
  questions: [
    {
      questionId: "mixins-yn-001",
      type: "yes_no",
      prompt: "믹스인은 여러 클래스에서 재사용할 수 있는 메서드 묶음을 제공하는 패턴이다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-mixins",
      explanation:
        "믹스인은 상속 계층을 깊게 만들지 않고 공통 동작을 여러 클래스에 섞어 넣는 패턴이다.",
      sourceExcerptId: "mixins-001",
    },
    {
      questionId: "mixins-yn-002",
      type: "yes_no",
      prompt: "자바스크립트 클래스는 여러 클래스를 동시에 extends 할 수 있다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-mixins",
      explanation:
        "자바스크립트 클래스는 단일 상속만 지원하므로 여러 동작 조합에는 믹스인 패턴을 사용할 수 있다.",
      sourceExcerptId: "mixins-002",
    },
    {
      questionId: "mixins-yn-003",
      type: "yes_no",
      prompt: "Object.assign으로 믹스인 메서드를 prototype에 복사할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-mixins",
      explanation:
        "Object.assign(Target.prototype, mixin) 형태로 믹스인 메서드를 클래스 prototype에 추가할 수 있다.",
      sourceExcerptId: "mixins-003",
    },
    {
      questionId: "mixins-mc-001",
      type: "multiple_choice",
      prompt: "믹스인을 사용하는 주된 이유로 가장 적절한 것은?",
      answer: "여러 클래스에 공통 동작을 조합하기 위해",
      choices: [
        "private 필드를 제거하기 위해",
        "여러 클래스에 공통 동작을 조합하기 위해",
        "배열을 정렬하기 위해",
        "상속을 금지하기 위해",
        "모듈을 비동기로 불러오기 위해",
      ],
      conceptGroup: "js-mixins",
      explanation: "믹스인은 여러 클래스가 공유할 수 있는 동작을 조합하는 데 유용하다.",
      sourceExcerptId: "mixins-001",
    },
    {
      questionId: "mixins-mc-002",
      type: "multiple_choice",
      prompt: "믹스인 메서드를 클래스 prototype에 복사할 때 자주 쓰는 메서드는?",
      answer: "Object.assign",
      choices: ["Object.assign", "Object.freeze", "Object.keys", "Array.from", "JSON.parse"],
      conceptGroup: "js-mixins",
      explanation:
        "Object.assign은 믹스인 객체의 메서드를 대상 prototype에 복사하는 데 쓸 수 있다.",
      sourceExcerptId: "mixins-003",
    },
    {
      questionId: "mixins-mc-003",
      type: "multiple_choice",
      prompt: "믹스인 패턴이 보완하는 자바스크립트 클래스의 제약은?",
      answer: "단일 상속",
      choices: ["동적 타입", "단일 상속", "strict mode", "호이스팅", "스코프 체인"],
      conceptGroup: "js-mixins",
      explanation:
        "자바스크립트 클래스는 하나의 부모만 extends 할 수 있으므로 믹스인으로 여러 동작을 조합할 수 있다.",
      sourceExcerptId: "mixins-002",
    },
    {
      questionId: "mixins-fb-001",
      type: "fill_blank",
      prompt: "여러 클래스에 동작을 섞어 넣는 재사용 패턴을 ____ 이라고 한다.",
      answer: "믹스인",
      acceptedAnswers: ["믹스인", "mixin", "mixins"],
      conceptGroup: "js-mixins",
      explanation: "믹스인은 공통 동작을 여러 클래스에 조합하는 패턴이다.",
      sourceExcerptId: "mixins-001",
    },
    {
      questionId: "mixins-fb-002",
      type: "fill_blank",
      prompt: "믹스인 메서드를 prototype에 복사할 때 Object.____ 을 사용할 수 있다.",
      answer: "assign",
      acceptedAnswers: ["assign", "Object.assign"],
      conceptGroup: "js-mixins",
      explanation: "Object.assign(Target.prototype, mixin)으로 메서드를 복사할 수 있다.",
      sourceExcerptId: "mixins-003",
    },
    {
      questionId: "mixins-fb-003",
      type: "fill_blank",
      prompt: "자바스크립트 클래스는 기본적으로 ____ 상속만 지원한다.",
      answer: "단일",
      acceptedAnswers: ["단일", "single"],
      conceptGroup: "js-mixins",
      explanation: "클래스는 하나의 부모 클래스만 extends 할 수 있다.",
      sourceExcerptId: "mixins-002",
    },
  ],
};
