import type { QuestionPage } from "@/content/questions/types";

export const modulesIntro: QuestionPage = {
  sourceId: "modules-intro",
  title: "모듈 소개",
  url: "https://ko.javascript.info/modules-intro",
  questions: [
    {
      questionId: "modules-intro-yn-001",
      type: "yes_no",
      prompt: "자바스크립트 모듈은 보통 파일 하나를 기준으로 나눌 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-modules",
      explanation: "모듈은 대개 파일 하나이며, export와 import로 기능을 공유한다.",
      sourceExcerptId: "modules-intro-001",
    },
    {
      questionId: "modules-intro-yn-002",
      type: "yes_no",
      prompt: '브라우저에서 모듈 스크립트를 사용하려면 script 태그에 type="module"을 지정한다.',
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-modules",
      explanation: '브라우저는 type="module"이 붙은 스크립트를 모듈로 인식해 가져오고 평가한다.',
      sourceExcerptId: "modules-intro-002",
    },
    {
      questionId: "modules-intro-yn-003",
      type: "yes_no",
      prompt:
        "모듈 내부의 변수는 기본적으로 다른 모듈이나 일반 스크립트의 전역 스코프에 자동 공개된다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-modules",
      explanation: "모듈은 자신만의 스코프를 가지며, 외부에서 쓰려면 export와 import가 필요하다.",
      sourceExcerptId: "modules-intro-004",
    },
    {
      questionId: "modules-intro-mc-001",
      type: "multiple_choice",
      prompt: "다른 모듈에서 사용할 수 있게 값을 공개하는 지시자는?",
      answer: "export",
      choices: ["export", "import", "module", "require", "include"],
      conceptGroup: "js-modules",
      explanation: "export는 변수, 함수, 클래스 등을 외부 모듈에서 가져갈 수 있게 공개한다.",
      sourceExcerptId: "modules-intro-001",
    },
    {
      questionId: "modules-intro-mc-002",
      type: "multiple_choice",
      prompt: "다른 모듈에서 공개한 기능을 가져올 때 사용하는 지시자는?",
      answer: "import",
      choices: ["import", "export", "defer", "async", "attach"],
      conceptGroup: "js-modules",
      explanation: "import는 다른 모듈이 export한 기능을 현재 모듈에서 사용할 수 있게 한다.",
      sourceExcerptId: "modules-intro-001",
    },
    {
      questionId: "modules-intro-mc-003",
      type: "multiple_choice",
      prompt: "모듈에서 현재 모듈 파일 URL 같은 메타 정보를 얻을 수 있는 객체는?",
      answer: "import.meta",
      choices: ["import.meta", "module.info", "export.meta", "this.module", "script.meta"],
      conceptGroup: "js-modules",
      explanation:
        "import.meta는 현재 모듈에 대한 정보를 제공하며, 브라우저에서는 URL 정보를 얻을 수 있다.",
      sourceExcerptId: "modules-intro-006",
    },
    {
      questionId: "modules-intro-fb-001",
      type: "fill_blank",
      prompt: '브라우저에서 모듈 스크립트는 <script type="____">로 표시한다.',
      answer: "module",
      acceptedAnswers: ["module"],
      conceptGroup: "js-modules",
      explanation: 'type="module" 속성이 있어야 브라우저가 해당 스크립트를 모듈로 처리한다.',
      sourceExcerptId: "modules-intro-002",
    },
    {
      questionId: "modules-intro-fb-002",
      type: "fill_blank",
      prompt: "모듈은 항상 ____ 모드로 실행된다.",
      answer: "엄격",
      acceptedAnswers: ["엄격", "strict", "strict mode", "use strict"],
      conceptGroup: "js-modules",
      explanation: "모듈은 자동으로 strict mode에서 실행된다.",
      sourceExcerptId: "modules-intro-003",
    },
    {
      questionId: "modules-intro-fb-003",
      type: "fill_blank",
      prompt: "모듈은 최초 import 시 단 ____ 번만 평가된다.",
      answer: "한",
      acceptedAnswers: ["한", "1", "한 번", "한번"],
      conceptGroup: "js-modules",
      explanation: "동일한 모듈은 여러 곳에서 가져와도 최초 한 번만 실행되고 결과가 공유된다.",
      sourceExcerptId: "modules-intro-005",
    },
  ],
};
