import type { QuestionPage } from "../types";

export const modulesDynamicImports: QuestionPage = {
  sourceId: "modules-dynamic-imports",
  title: "동적으로 모듈 가져오기",
  url: "https://ko.javascript.info/modules-dynamic-imports",
  questions: [
    {
      questionId: "modules-dynamic-imports-yn-001",
      type: "yes_no",
      prompt: "정적 import 문은 런타임 조건문 안에서 자유롭게 사용할 수 있다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-dynamic-imports",
      explanation: "정적 import 문은 코드 구조 분석을 위해 최상위에 고정된 형태로 사용해야 한다.",
      sourceExcerptId: "modules-dynamic-imports-001",
    },
    {
      questionId: "modules-dynamic-imports-yn-002",
      type: "yes_no",
      prompt: "import(module) 표현식은 Promise를 반환한다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-dynamic-imports",
      explanation: "import(module)은 모듈 객체로 이행되는 Promise를 반환한다.",
      sourceExcerptId: "modules-dynamic-imports-002",
    },
    {
      questionId: "modules-dynamic-imports-yn-003",
      type: "yes_no",
      prompt: '동적 import는 script type="module" 안에서만 동작한다.',
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-dynamic-imports",
      explanation: "동적 import는 일반 스크립트에서도 사용할 수 있다.",
      sourceExcerptId: "modules-dynamic-imports-005",
    },
    {
      questionId: "modules-dynamic-imports-mc-001",
      type: "multiple_choice",
      prompt: "런타임에 모듈 경로를 정해 가져올 때 사용하는 표현식은?",
      answer: "import(module)",
      choices: [
        "import(module)",
        "import ... from module",
        "export(module)",
        "require.static(module)",
        "module.loadSync(module)",
      ],
      conceptGroup: "js-dynamic-imports",
      explanation:
        "import(module) 표현식은 어디서나 호출할 수 있고, 모듈 객체를 담은 Promise를 반환한다.",
      sourceExcerptId: "modules-dynamic-imports-002",
    },
    {
      questionId: "modules-dynamic-imports-mc-002",
      type: "multiple_choice",
      prompt:
        "동적 import로 default export를 가져온 모듈 객체에서 기본 내보내기는 어느 프로퍼티에 들어있는가?",
      answer: "default",
      choices: ["default", "module", "main", "export", "value"],
      conceptGroup: "js-dynamic-imports",
      explanation:
        "동적 import 결과 모듈 객체의 default 프로퍼티에서 기본 내보내기를 사용할 수 있다.",
      sourceExcerptId: "modules-dynamic-imports-004",
    },
    {
      questionId: "modules-dynamic-imports-mc-003",
      type: "multiple_choice",
      prompt: "async 함수 안에서 동적 import 결과를 받는 예로 가장 적절한 것은?",
      answer: "let module = await import(path)",
      choices: [
        "let module = await import(path)",
        "let module = import path",
        "let module = export await(path)",
        "let module = await import from path",
        "let module = require await path",
      ],
      conceptGroup: "js-dynamic-imports",
      explanation:
        "import(path)는 Promise를 반환하므로 async 함수 안에서 await import(path)로 결과를 받을 수 있다.",
      sourceExcerptId: "modules-dynamic-imports-003",
    },
    {
      questionId: "modules-dynamic-imports-fb-001",
      type: "fill_blank",
      prompt: "동적 import 표현식 import(module)은 ____ 를 반환한다.",
      answer: "Promise",
      acceptedAnswers: ["Promise", "프라미스"],
      conceptGroup: "js-dynamic-imports",
      explanation: "import(module)은 모듈 객체를 담아 이행되는 Promise를 반환한다.",
      sourceExcerptId: "modules-dynamic-imports-002",
    },
    {
      questionId: "modules-dynamic-imports-fb-002",
      type: "fill_blank",
      prompt: "동적 import로 가져온 default export는 모듈 객체의 ____ 프로퍼티에서 사용할 수 있다.",
      answer: "default",
      acceptedAnswers: ["default"],
      conceptGroup: "js-dynamic-imports",
      explanation: "default export는 동적 import 결과 객체의 default 프로퍼티로 접근한다.",
      sourceExcerptId: "modules-dynamic-imports-004",
    },
    {
      questionId: "modules-dynamic-imports-fb-003",
      type: "fill_blank",
      prompt: "import(module)은 함수 호출처럼 보이지만 함수가 아니라 특별한 ____ 이다.",
      answer: "문법",
      acceptedAnswers: ["문법", "syntax"],
      conceptGroup: "js-dynamic-imports",
      explanation:
        "import()는 함수 호출이 아니라 괄호를 쓰는 특별한 문법이므로 call/apply로 사용할 수 없다.",
      sourceExcerptId: "modules-dynamic-imports-006",
    },
  ],
};
