import type { QuestionPage } from "../types";

export const nativePrototypes: QuestionPage = {
  sourceId: "native-prototypes",
  title: "내장 객체의 프로토타입",
  url: "https://ko.javascript.info/native-prototypes",
  questions: [
    {
      questionId: "native-prototypes-yn-001",
      type: "yes_no",
      prompt: "배열은 Array.prototype의 메서드를 상속받아 사용할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-native-prototypes",
      explanation: "배열은 Array.prototype에 있는 map, filter 같은 메서드를 상속받는다.",
      sourceExcerptId: "native-prototypes-001",
    },
    {
      questionId: "native-prototypes-yn-002",
      type: "yes_no",
      prompt: "문자열 원시값도 메서드를 호출할 때 임시 래퍼 객체를 통해 동작할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-native-prototypes",
      explanation:
        "문자열 같은 원시값은 메서드 호출 시 임시 객체로 감싸져 String.prototype 메서드를 사용할 수 있다.",
      sourceExcerptId: "native-prototypes-002",
    },
    {
      questionId: "native-prototypes-yn-003",
      type: "yes_no",
      prompt: "내장 프로토타입을 수정하는 것은 항상 안전하고 권장된다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-native-prototypes",
      explanation:
        "내장 프로토타입 수정은 충돌과 예측 어려움을 만들 수 있어 보통 피하는 편이 좋다.",
      sourceExcerptId: "native-prototypes-003",
    },
    {
      questionId: "native-prototypes-mc-001",
      type: "multiple_choice",
      prompt: "배열 메서드 map이 주로 정의되어 있는 곳은?",
      answer: "Array.prototype",
      choices: [
        "Object",
        "Array.prototype",
        "String.prototype",
        "Function.prototype",
        "Map.prototype",
      ],
      conceptGroup: "js-native-prototypes",
      explanation: "배열 인스턴스는 Array.prototype의 메서드를 프로토타입 체인으로 사용한다.",
      sourceExcerptId: "native-prototypes-001",
    },
    {
      questionId: "native-prototypes-mc-002",
      type: "multiple_choice",
      prompt: "모든 객체의 공통 조상에 가까운 내장 프로토타입은?",
      answer: "Object.prototype",
      choices: [
        "Array.prototype",
        "String.prototype",
        "Object.prototype",
        "Promise.prototype",
        "Date.prototype",
      ],
      conceptGroup: "js-native-prototypes",
      explanation: "대부분의 일반 객체는 프로토타입 체인의 위쪽에서 Object.prototype을 만난다.",
      sourceExcerptId: "native-prototypes-004",
    },
    {
      questionId: "native-prototypes-mc-003",
      type: "multiple_choice",
      prompt: "내장 프로토타입 확장이 예외적으로 허용되기 쉬운 경우는?",
      answer: "폴리필 추가",
      choices: [
        "취향에 맞는 별칭 추가",
        "폴리필 추가",
        "모든 메서드 덮어쓰기",
        "랜덤 값 저장",
        "전역 상태 공유",
      ],
      conceptGroup: "js-native-prototypes",
      explanation: "표준 메서드가 없는 환경에서 호환성을 위한 폴리필은 제한적으로 쓰일 수 있다.",
      sourceExcerptId: "native-prototypes-003",
    },
    {
      questionId: "native-prototypes-fb-001",
      type: "fill_blank",
      prompt: "배열 인스턴스가 공유하는 내장 프로토타입은 Array.____ 이다.",
      answer: "prototype",
      acceptedAnswers: ["prototype", "Array.prototype"],
      conceptGroup: "js-native-prototypes",
      explanation: "배열 메서드는 주로 Array.prototype에 정의되어 있다.",
      sourceExcerptId: "native-prototypes-001",
    },
    {
      questionId: "native-prototypes-fb-002",
      type: "fill_blank",
      prompt: "문자열 메서드는 주로 String.____ 에 정의되어 있다.",
      answer: "prototype",
      acceptedAnswers: ["prototype", "String.prototype"],
      conceptGroup: "js-native-prototypes",
      explanation: "문자열 관련 메서드는 String.prototype에서 찾아 사용할 수 있다.",
      sourceExcerptId: "native-prototypes-002",
    },
    {
      questionId: "native-prototypes-fb-003",
      type: "fill_blank",
      prompt: "표준 메서드가 없는 환경에서 호환성을 위해 추가하는 구현을 ____ 이라고 한다.",
      answer: "폴리필",
      acceptedAnswers: ["폴리필", "polyfill"],
      conceptGroup: "js-native-prototypes",
      explanation: "폴리필은 오래된 환경에 표준 기능을 보완하기 위한 구현이다.",
      sourceExcerptId: "native-prototypes-003",
    },
  ],
};
