import type { QuestionPage } from "../types";

export const nullishCoalescing: QuestionPage = {
  sourceId: "nullish-coalescing-operator",
  title: "Nullish 병합 연산자 '??'",
  url: "https://ko.javascript.info/nullish-coalescing-operator",
  questions: [
    {
      questionId: "nullish-yn-001",
      type: "yes_no",
      prompt: "?? 연산자는 왼쪽 값이 null 또는 undefined일 때만 오른쪽 값을 반환한다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-nullish",
      explanation: "?? 는 null과 undefined만 비어 있는 값으로 취급한다.",
      sourceExcerptId: "nullish-001",
    },
    {
      questionId: "nullish-yn-002",
      type: "yes_no",
      prompt: "값이 0이면 ?? 연산자는 항상 오른쪽 값을 반환한다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-nullish",
      explanation: "0은 nullish가 아니므로 왼쪽 값 0이 그대로 반환된다.",
      sourceExcerptId: "nullish-002",
    },
    {
      questionId: "nullish-yn-003",
      type: "yes_no",
      prompt: "|| 대신 ?? 를 쓰면 0이나 빈 문자열을 유효한 값으로 유지할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-nullish",
      explanation: "|| 는 falsy 전부를 걸러내지만 ?? 는 nullish만 처리한다.",
      sourceExcerptId: "nullish-003",
    },
    {
      questionId: "nullish-mc-001",
      type: "multiple_choice",
      prompt: "다음 중 ?? 연산자가 오른쪽 값을 반환하는 경우는?",
      answer: "왼쪽 값이 undefined일 때",
      choices: [
        "왼쪽 값이 undefined일 때",
        "왼쪽 값이 0일 때",
        "왼쪽 값이 빈 문자열일 때",
        "왼쪽 값이 false일 때",
        "왼쪽 값이 NaN일 때",
      ],
      conceptGroup: "js-nullish",
      explanation: "undefined는 nullish 값이므로 오른쪽 피연산자가 반환된다.",
      sourceExcerptId: "nullish-001",
    },
    {
      questionId: "nullish-mc-002",
      type: "multiple_choice",
      prompt: "0을 기본값으로 덮어쓰지 않으려면 어떤 연산자가 더 적절한가?",
      answer: "??",
      choices: ["||", "&&", "??", "?:", "!"],
      conceptGroup: "js-nullish",
      explanation: "0은 falsy지만 nullish는 아니므로 ?? 가 더 적절하다.",
      sourceExcerptId: "nullish-003",
    },
    {
      questionId: "nullish-mc-003",
      type: "multiple_choice",
      prompt: "다음 중 nullish 값만 고르면?",
      answer: "null, undefined",
      choices: ["null, undefined", "0, false", "false, ''", "NaN, null", "0, undefined"],
      conceptGroup: "js-nullish",
      explanation: "nullish 값은 null과 undefined 두 가지다.",
      sourceExcerptId: "nullish-001",
    },
    {
      questionId: "nullish-fb-001",
      type: "fill_blank",
      prompt: "Nullish 병합 연산자의 기호는 ____ 이다.",
      answer: "??",
      acceptedAnswers: ["??"],
      conceptGroup: "js-nullish",
      explanation: "?? 는 nullish 병합 연산자다.",
      sourceExcerptId: "nullish-001",
    },
    {
      questionId: "nullish-fb-002",
      type: "fill_blank",
      prompt: "?? 는 왼쪽 값이 null 또는 ____ 일 때 오른쪽 값을 선택한다.",
      answer: "undefined",
      acceptedAnswers: ["undefined"],
      conceptGroup: "js-nullish",
      explanation: "?? 는 null과 undefined를 같은 기준으로 본다.",
      sourceExcerptId: "nullish-001",
    },
    {
      questionId: "nullish-fb-003",
      type: "fill_blank",
      prompt: "0이나 빈 문자열 같은 falsy 값을 유지하면서 기본값을 주려면 ____ 연산자가 적절하다.",
      answer: "??",
      acceptedAnswers: ["??"],
      conceptGroup: "js-nullish",
      explanation: "?? 는 falsy 전체가 아니라 nullish만 처리한다.",
      sourceExcerptId: "nullish-003",
    },
  ],
};
