import type { QuestionPage } from "@/content/questions/types";

export const objectCopy: QuestionPage = {
  sourceId: "object-copy",
  title: "참조에 의한 객체 복사",
  url: "https://ko.javascript.info/object-copy",
  questions: [
    {
      questionId: "object-copy-yn-001",
      type: "yes_no",
      prompt: "객체 변수에는 객체 자체가 아니라 객체에 대한 참조가 저장된다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-object-copy",
      explanation: "객체 변수는 메모리의 객체를 가리키는 참조를 저장한다.",
      sourceExcerptId: "object-copy-001",
    },
    {
      questionId: "object-copy-yn-002",
      type: "yes_no",
      prompt: "두 변수가 같은 객체를 참조하면 한쪽 변경이 다른 쪽에서도 보인다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-object-copy",
      explanation: "같은 객체 참조를 공유하면 한쪽 수정이 같은 객체에 반영된다.",
      sourceExcerptId: "object-copy-002",
    },
    {
      questionId: "object-copy-yn-003",
      type: "yes_no",
      prompt: "Object.assign은 중첩 객체까지 완전한 깊은 복사를 보장한다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-object-copy",
      explanation: "Object.assign은 얕은 복사이므로 중첩 객체는 참조를 공유할 수 있다.",
      sourceExcerptId: "object-copy-003",
    },
    {
      questionId: "object-copy-mc-001",
      type: "multiple_choice",
      prompt: "여러 프로퍼티를 다른 객체로 복사할 때 자주 쓰는 메서드는?",
      answer: "Object.assign",
      choices: ["Object.copy", "Object.assign", "Object.clone", "Object.merge", "Object.link"],
      conceptGroup: "js-object-copy",
      explanation: "Object.assign은 다른 객체의 프로퍼티를 복사하는 데 자주 쓰인다.",
      sourceExcerptId: "object-copy-003",
    },
    {
      questionId: "object-copy-mc-002",
      type: "multiple_choice",
      prompt: "얕은 복사의 특징으로 맞는 것은?",
      answer: "중첩 객체 참조를 그대로 공유할 수 있다",
      choices: [
        "항상 완전한 독립 객체를 만든다",
        "중첩 객체 참조를 그대로 공유할 수 있다",
        "원본 객체를 자동으로 삭제한다",
        "함수만 복사하지 못한다",
        "배열에는 사용할 수 없다",
      ],
      conceptGroup: "js-object-copy",
      explanation: "얕은 복사는 최상위 프로퍼티만 복사하고 중첩 참조는 공유할 수 있다.",
      sourceExcerptId: "object-copy-003",
    },
    {
      questionId: "object-copy-mc-003",
      type: "multiple_choice",
      prompt: "같은 객체를 가리키는지 비교할 때 객체끼리 비교 결과가 true가 되려면?",
      answer: "두 값이 같은 객체 참조일 때",
      choices: [
        "프로퍼티 개수가 같을 때",
        "내용이 비슷할 때",
        "두 값이 같은 객체 참조일 때",
        "둘 다 const일 때",
        "JSON 문자열이 같을 때",
      ],
      conceptGroup: "js-object-copy",
      explanation: "객체 비교는 내용이 아니라 참조 동일성 기준으로 동작한다.",
      sourceExcerptId: "object-copy-004",
    },
    {
      questionId: "object-copy-fb-001",
      type: "fill_blank",
      prompt: "Object.assign은 대표적인 ____ 복사 방법이다.",
      answer: "얕은",
      acceptedAnswers: ["얕은", "shallow"],
      conceptGroup: "js-object-copy",
      explanation: "Object.assign은 얕은 복사를 수행한다.",
      sourceExcerptId: "object-copy-003",
    },
    {
      questionId: "object-copy-fb-002",
      type: "fill_blank",
      prompt: "객체 변수를 다른 변수에 그대로 대입하면 객체 자체가 아니라 ____ 가 복사된다.",
      answer: "참조",
      acceptedAnswers: ["참조", "reference"],
      conceptGroup: "js-object-copy",
      explanation: "객체 대입은 참조를 복사한다.",
      sourceExcerptId: "object-copy-001",
    },
    {
      questionId: "object-copy-fb-003",
      type: "fill_blank",
      prompt: "중첩 객체까지 완전히 새로 복사하는 방식을 ____ 복사라고 한다.",
      answer: "깊은",
      acceptedAnswers: ["깊은", "deep"],
      conceptGroup: "js-object-copy",
      explanation: "중첩 객체까지 독립적으로 복사하면 깊은 복사다.",
      sourceExcerptId: "object-copy-005",
    },
  ],
};
