import type { QuestionPage } from "@/content/questions/types";

export const objectKeysValuesEntries: QuestionPage = {
  sourceId: "keys-values-entries",
  title: "Object.keys, values, entries",
  url: "https://ko.javascript.info/keys-values-entries",
  questions: [
    {
      questionId: "keys-values-entries-yn-001",
      type: "yes_no",
      prompt: "Object.keys(obj)는 객체의 키들로 이루어진 배열을 반환한다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-object-keys-values-entries",
      explanation: "Object.keys는 객체 자신의 enumerable 프로퍼티 키 배열을 반환한다.",
      sourceExcerptId: "keys-values-entries-001",
    },
    {
      questionId: "keys-values-entries-yn-002",
      type: "yes_no",
      prompt: "Object.values(obj)는 키와 값을 쌍으로 묶은 배열을 반환한다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-object-keys-values-entries",
      explanation: "Object.values는 값들만 담은 배열을 반환한다.",
      sourceExcerptId: "keys-values-entries-002",
    },
    {
      questionId: "keys-values-entries-yn-003",
      type: "yes_no",
      prompt: "Object.entries(obj)는 for...of와 함께 순회하기 좋다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-object-keys-values-entries",
      explanation:
        "Object.entries는 [key, value] 쌍 배열을 반환하므로 구조 분해와 함께 순회하기 좋다.",
      sourceExcerptId: "keys-values-entries-003",
    },
    {
      questionId: "keys-values-entries-mc-001",
      type: "multiple_choice",
      prompt: "객체의 값들만 배열로 얻고 싶을 때 쓰는 메서드는?",
      answer: "Object.values",
      choices: [
        "Object.keys",
        "Object.values",
        "Object.entries",
        "Object.assign",
        "Object.fromEntries",
      ],
      conceptGroup: "js-object-keys-values-entries",
      explanation: "Object.values는 객체 자신의 enumerable 값들만 배열로 반환한다.",
      sourceExcerptId: "keys-values-entries-002",
    },
    {
      questionId: "keys-values-entries-mc-002",
      type: "multiple_choice",
      prompt: "Object.entries(user)의 각 원소 형태로 맞는 것은?",
      answer: "[key, value]",
      choices: ["key", "value", "[key, value]", "{ key, value }", "[value, key]"],
      conceptGroup: "js-object-keys-values-entries",
      explanation: "Object.entries는 각 프로퍼티를 [key, value] 형태의 배열로 만든다.",
      sourceExcerptId: "keys-values-entries-003",
    },
    {
      questionId: "keys-values-entries-mc-003",
      type: "multiple_choice",
      prompt: "배열이 아닌 일반 객체를 바로 map으로 순회하기 전에 자주 거치는 단계는?",
      answer: "Object.entries로 배열화",
      choices: [
        "JSON.stringify로 문자열화",
        "Object.entries로 배열화",
        "Number로 형변환",
        "Set으로 감싸기",
        "WeakMap으로 변환",
      ],
      conceptGroup: "js-object-keys-values-entries",
      explanation:
        "일반 객체는 바로 배열 메서드를 쓰기 어려워 Object.entries로 배열화한 뒤 처리하는 패턴이 흔하다.",
      sourceExcerptId: "keys-values-entries-004",
    },
    {
      questionId: "keys-values-entries-fb-001",
      type: "fill_blank",
      prompt: "Object.____(obj)는 객체 키 배열을 반환한다.",
      answer: "keys",
      acceptedAnswers: ["keys", "Object.keys"],
      conceptGroup: "js-object-keys-values-entries",
      explanation: "Object.keys는 객체 키 배열을 반환한다.",
      sourceExcerptId: "keys-values-entries-001",
    },
    {
      questionId: "keys-values-entries-fb-002",
      type: "fill_blank",
      prompt: "Object.entries(obj)의 각 요소는 ____ 쌍이다.",
      answer: "key-value",
      acceptedAnswers: ["key-value", "[key, value]", "키-값", "키와 값"],
      conceptGroup: "js-object-keys-values-entries",
      explanation: "Object.entries는 각 프로퍼티를 key-value 쌍으로 변환한다.",
      sourceExcerptId: "keys-values-entries-003",
    },
    {
      questionId: "keys-values-entries-fb-003",
      type: "fill_blank",
      prompt: "배열 형태의 [key, value] 목록을 다시 객체로 만들 때 쓰는 메서드는 Object.____ 이다.",
      answer: "fromEntries",
      acceptedAnswers: ["fromEntries", "Object.fromEntries"],
      conceptGroup: "js-object-keys-values-entries",
      explanation: "Object.fromEntries는 key-value 쌍 배열을 다시 객체로 만든다.",
      sourceExcerptId: "keys-values-entries-004",
    },
  ],
};
