import type { QuestionPage } from "../types";

export const objectBasics: QuestionPage = {
  sourceId: "object",
  title: "객체",
  url: "https://ko.javascript.info/object",
  questions: [
    {
      questionId: "object-yn-001",
      type: "yes_no",
      prompt: "객체는 키와 값의 쌍으로 데이터를 저장할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-objects",
      explanation: "객체는 프로퍼티(key-value 쌍)를 모아두는 자료형이다.",
      sourceExcerptId: "object-001",
    },
    {
      questionId: "object-yn-002",
      type: "yes_no",
      prompt: "객체 프로퍼티는 점 표기법이나 대괄호 표기법으로 접근할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-objects",
      explanation: "객체 프로퍼티 접근에는 점 표기법과 대괄호 표기법을 쓸 수 있다.",
      sourceExcerptId: "object-002",
    },
    {
      questionId: "object-yn-003",
      type: "yes_no",
      prompt: "const로 선언한 객체는 프로퍼티 수정도 전혀 할 수 없다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-objects",
      explanation: "const는 변수 재할당을 막지만, 객체 내부 프로퍼티 수정은 가능하다.",
      sourceExcerptId: "object-003",
    },
    {
      questionId: "object-mc-001",
      type: "multiple_choice",
      prompt: "프로퍼티 이름이 변수에 들어 있을 때 적절한 접근 방식은?",
      answer: "대괄호 표기법",
      choices: ["점 표기법", "대괄호 표기법", "콜백 함수", "switch문", "strict mode"],
      conceptGroup: "js-objects",
      explanation: "동적인 프로퍼티 이름은 대괄호 표기법으로 접근한다.",
      sourceExcerptId: "object-002",
    },
    {
      questionId: "object-mc-002",
      type: "multiple_choice",
      prompt: "없는 프로퍼티에 접근하면 기본적으로 무엇이 반환되는가?",
      answer: "undefined",
      choices: ["null", "false", "0", "undefined", "error"],
      conceptGroup: "js-objects",
      explanation: "존재하지 않는 프로퍼티 접근 결과는 undefined다.",
      sourceExcerptId: "object-004",
    },
    {
      questionId: "object-mc-003",
      type: "multiple_choice",
      prompt: "프로퍼티를 삭제할 때 사용하는 연산자는?",
      answer: "delete",
      choices: ["remove", "delete", "unset", "drop", "clear"],
      conceptGroup: "js-objects",
      explanation: "객체 프로퍼티 삭제에는 delete 연산자를 사용한다.",
      sourceExcerptId: "object-005",
    },
    {
      questionId: "object-fb-001",
      type: "fill_blank",
      prompt: "객체에서 프로퍼티를 삭제할 때 쓰는 키워드는 ____ 이다.",
      answer: "delete",
      acceptedAnswers: ["delete"],
      conceptGroup: "js-objects",
      explanation: "delete는 객체 프로퍼티를 제거할 때 쓴다.",
      sourceExcerptId: "object-005",
    },
    {
      questionId: "object-fb-002",
      type: "fill_blank",
      prompt: "obj.name처럼 접근하는 방식을 점 ____ 이라고 한다.",
      answer: "표기법",
      acceptedAnswers: ["표기법", "notation"],
      conceptGroup: "js-objects",
      explanation: "obj.name은 점 표기법의 대표적인 예다.",
      sourceExcerptId: "object-002",
    },
    {
      questionId: "object-fb-003",
      type: "fill_blank",
      prompt: "객체는 여러 개의 ____ 와 값을 저장한다.",
      answer: "키",
      acceptedAnswers: ["키", "key"],
      conceptGroup: "js-objects",
      explanation: "객체는 key-value 쌍 구조를 가진다.",
      sourceExcerptId: "object-001",
    },
  ],
};
