import type { QuestionPage } from "@/content/questions/types";

export const objectToPrimitive: QuestionPage = {
  sourceId: "object-toprimitive",
  title: "객체를 원시형으로 변환하기",
  url: "https://ko.javascript.info/object-toprimitive",
  questions: [
    {
      questionId: "object-toprimitive-yn-001",
      type: "yes_no",
      prompt:
        "객체가 문자열이나 숫자처럼 원시값이 필요한 문맥에 놓이면 원시형 변환이 시도될 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-object-toprimitive",
      explanation:
        "객체는 원시값이 필요한 연산에서 문자열, 숫자, default 힌트 기반 변환을 시도한다.",
      sourceExcerptId: "object-toprimitive-001",
    },
    {
      questionId: "object-toprimitive-yn-002",
      type: "yes_no",
      prompt:
        "객체의 [Symbol.toPrimitive] 메서드는 원시형 변환 우선순위에서 가장 먼저 고려될 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-object-toprimitive",
      explanation: "[Symbol.toPrimitive]가 있으면 가장 먼저 호출될 수 있다.",
      sourceExcerptId: "object-toprimitive-002",
    },
    {
      questionId: "object-toprimitive-yn-003",
      type: "yes_no",
      prompt: "toString과 valueOf는 항상 둘 다 호출되어야만 객체가 원시형으로 변환된다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-object-toprimitive",
      explanation: "힌트와 결과에 따라 하나만으로 변환이 끝날 수도 있다.",
      sourceExcerptId: "object-toprimitive-003",
    },
    {
      questionId: "object-toprimitive-mc-001",
      type: "multiple_choice",
      prompt: "객체의 원시형 변환을 직접 제어하는 잘 알려진 심볼 메서드는?",
      answer: "[Symbol.toPrimitive]",
      choices: [
        "[Symbol.toPrimitive]",
        "[Symbol.value]",
        "Object.toPrimitive",
        "toSymbol",
        "primitiveOf",
      ],
      conceptGroup: "js-object-toprimitive",
      explanation: "[Symbol.toPrimitive]는 객체의 원시형 변환 방식을 직접 정의할 수 있다.",
      sourceExcerptId: "object-toprimitive-002",
    },
    {
      questionId: "object-toprimitive-mc-002",
      type: "multiple_choice",
      prompt: "숫자 힌트 변환에서 보통 더 우선적으로 시도되는 메서드 조합은?",
      answer: "valueOf 후 toString",
      choices: [
        "toString 후 valueOf",
        "valueOf 후 toString",
        "항상 toJSON만",
        "constructor 후 toString",
        "Symbol.iterator 후 valueOf",
      ],
      conceptGroup: "js-object-toprimitive",
      explanation: "숫자 힌트에서는 보통 valueOf를 먼저 보고, 필요하면 toString을 본다.",
      sourceExcerptId: "object-toprimitive-003",
    },
    {
      questionId: "object-toprimitive-mc-003",
      type: "multiple_choice",
      prompt: "문자열 힌트 변환에서 일반적으로 더 우선적으로 시도되는 것은?",
      answer: "toString 후 valueOf",
      choices: [
        "toString 후 valueOf",
        "valueOf 후 toString",
        "항상 Number()만",
        "prototype 후 constructor",
        "Symbol.toStringTag만",
      ],
      conceptGroup: "js-object-toprimitive",
      explanation: "문자열 힌트에서는 보통 toString을 먼저 시도한다.",
      sourceExcerptId: "object-toprimitive-003",
    },
    {
      questionId: "object-toprimitive-fb-001",
      type: "fill_blank",
      prompt: "객체의 원시형 변환을 직접 정의하는 심볼 메서드는 ____ 이다.",
      answer: "Symbol.toPrimitive",
      acceptedAnswers: ["Symbol.toPrimitive", "[Symbol.toPrimitive]"],
      conceptGroup: "js-object-toprimitive",
      explanation: "[Symbol.toPrimitive]는 객체 원시형 변환의 직접 제어 지점이다.",
      sourceExcerptId: "object-toprimitive-002",
    },
    {
      questionId: "object-toprimitive-fb-002",
      type: "fill_blank",
      prompt: "문자열 힌트에서는 보통 ____ 이 valueOf보다 먼저 시도된다.",
      answer: "toString",
      acceptedAnswers: ["toString"],
      conceptGroup: "js-object-toprimitive",
      explanation: "string 힌트에서는 toString이 먼저 시도된다.",
      sourceExcerptId: "object-toprimitive-003",
    },
    {
      questionId: "object-toprimitive-fb-003",
      type: "fill_blank",
      prompt: "숫자 힌트에서는 보통 ____ 가 toString보다 먼저 시도된다.",
      answer: "valueOf",
      acceptedAnswers: ["valueOf"],
      conceptGroup: "js-object-toprimitive",
      explanation: "number 힌트에서는 valueOf가 먼저 시도되는 경우가 일반적이다.",
      sourceExcerptId: "object-toprimitive-003",
    },
  ],
};
