import type { QuestionPage } from "../types";

export const objectMethods: QuestionPage = {
  sourceId: "object-methods",
  title: "메서드와 this",
  url: "https://ko.javascript.info/object-methods",
  questions: [
    {
      questionId: "object-methods-yn-001",
      type: "yes_no",
      prompt: "화살표 함수는 자신만의 this를 가진다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "this-core",
      explanation: "화살표 함수는 자신만의 this를 가지지 않는다. 외부 렉시컬 환경의 this를 그대로 사용한다.",
      sourceExcerptId: "object-methods-001",
    },
    {
      questionId: "object-methods-yn-002",
      type: "yes_no",
      prompt: "메서드를 객체 없이 호출하면 this는 undefined가 된다. (엄격 모드 기준)",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "this-core",
      explanation: "엄격 모드에서 this는 undefined가 된다. 비엄격 모드에서는 전역 객체를 참조한다.",
      sourceExcerptId: "object-methods-002",
    },
    {
      questionId: "object-methods-yn-003",
      type: "yes_no",
      prompt: "this 값은 런타임에 결정된다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "this-core",
      explanation: "this 값은 호출 시점에 결정되며, 함수를 어떻게 호출했느냐에 따라 달라진다.",
      sourceExcerptId: "object-methods-003",
    },
    {
      questionId: "object-methods-mc-001",
      type: "multiple_choice",
      prompt: "메서드 안의 this는 보통 무엇을 가리키나?",
      answer: "점 앞의 객체",
      choices: [
        "전역 객체",
        "점 앞의 객체",
        "항상 undefined",
        "항상 함수 자신",
        "새로 생성된 빈 객체",
      ],
      conceptGroup: "this-core",
      explanation: "메서드 호출에서 this는 점 앞의 객체를 가리킨다.",
      sourceExcerptId: "object-methods-004",
    },
    {
      questionId: "object-methods-mc-002",
      type: "multiple_choice",
      prompt: "다음 중 화살표 함수의 특징으로 올바른 것은?",
      answer: "자신만의 this를 가지지 않는다",
      choices: [
        "자신만의 this를 가진다",
        "자신만의 this를 가지지 않는다",
        "항상 전역 객체를 this로 가진다",
        "this를 바인딩할 수 없다는 에러가 발생한다",
        "new 키워드로 호출할 수 있다",
      ],
      conceptGroup: "this-core",
      explanation: "화살표 함수는 자신만의 this를 가지지 않으며, 외부 컨텍스트의 this를 그대로 가져온다.",
      sourceExcerptId: "object-methods-001",
    },
    {
      questionId: "object-methods-mc-003",
      type: "multiple_choice",
      prompt: "객체 리터럴에서 메서드를 정의하는 단축 구문은?",
      answer: "sayHi() { ... }",
      choices: [
        "sayHi: function() { ... }",
        "sayHi() { ... }",
        "function sayHi() { ... }",
        "sayHi => { ... }",
        "const sayHi = () => { ... }",
      ],
      conceptGroup: "this-core",
      explanation: "객체 리터럴에서 메서드를 정의할 때 function 키워드를 생략한 단축 구문을 사용할 수 있다.",
      sourceExcerptId: "object-methods-005",
    },
    {
      questionId: "object-methods-fb-001",
      type: "fill_blank",
      prompt: "화살표 함수는 자신만의 ____ 를 가지지 않는다.",
      answer: "this",
      acceptedAnswers: ["this", "디스"],
      conceptGroup: "this-core",
      explanation: "화살표 함수는 자신만의 this를 가지지 않는다.",
      sourceExcerptId: "object-methods-001",
    },
    {
      questionId: "object-methods-fb-002",
      type: "fill_blank",
      prompt: "this 값은 ____에 결정된다.",
      answer: "런타임",
      acceptedAnswers: ["런타임", "runtime", "실행 시점", "호출 시점"],
      conceptGroup: "this-core",
      explanation: "this 값은 런타임에 결정되며, 함수 선언 위치와 무관하다.",
      sourceExcerptId: "object-methods-003",
    },
    {
      questionId: "object-methods-fb-003",
      type: "fill_blank",
      prompt: "obj.method() 호출 시, method 안의 this는 ____ 를 가리킨다.",
      answer: "obj",
      acceptedAnswers: ["obj", "점 앞의 객체", "해당 객체"],
      conceptGroup: "this-core",
      explanation: "메서드를 호출할 때 this는 점(.) 앞의 객체를 참조한다.",
      sourceExcerptId: "object-methods-004",
    },
  ],
};
