import type { QuestionPage } from "@/content/questions/types";

export const operators: QuestionPage = {
  sourceId: "operators",
  title: "기본 연산자와 수학",
  url: "https://ko.javascript.info/operators",
  questions: [
    {
      questionId: "operators-yn-001",
      type: "yes_no",
      prompt: "이항 덧셈 연산자 + 는 숫자 덧셈뿐 아니라 문자열 연결에도 사용된다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-operators",
      explanation: "+ 연산자는 숫자 덧셈과 문자열 연결 모두에 사용된다.",
      sourceExcerptId: "operators-001",
    },
    {
      questionId: "operators-yn-002",
      type: "yes_no",
      prompt: "단항 + 는 피연산자를 숫자로 변환하려고 시도한다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-operators",
      explanation: "단항 + 는 값을 숫자형으로 변환하려고 할 때 자주 쓰인다.",
      sourceExcerptId: "operators-002",
    },
    {
      questionId: "operators-yn-003",
      type: "yes_no",
      prompt: "증가 연산자 ++ 는 변수 없이 숫자 리터럴에 직접 사용할 수 있다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-operators",
      explanation: "증가 연산자 ++ 는 값을 다시 대입할 수 있는 변수에만 사용할 수 있다.",
      sourceExcerptId: "operators-003",
    },
    {
      questionId: "operators-mc-001",
      type: "multiple_choice",
      prompt: "다음 중 문자열 연결 결과가 되는 것은?",
      answer: '"1" + 2',
      choices: ['"1" + 2', "1 - 2", "2 * 3", "10 / 2", "5 % 2"],
      conceptGroup: "js-operators",
      explanation: '"1" + 2 는 문자열 "12"를 만든다.',
      sourceExcerptId: "operators-001",
    },
    {
      questionId: "operators-mc-002",
      type: "multiple_choice",
      prompt: "나머지를 구하는 연산자는?",
      answer: "%",
      choices: ["%", "*", "/", "**", "++"],
      conceptGroup: "js-operators",
      explanation: "% 연산자는 나머지를 구할 때 사용한다.",
      sourceExcerptId: "operators-004",
    },
    {
      questionId: "operators-mc-003",
      type: "multiple_choice",
      prompt: "거듭제곱을 계산하는 연산자는?",
      answer: "**",
      choices: ["^", "**", "pow", "^^", "//"],
      conceptGroup: "js-operators",
      explanation: "** 연산자는 거듭제곱을 계산한다.",
      sourceExcerptId: "operators-005",
    },
    {
      questionId: "operators-fb-001",
      type: "fill_blank",
      prompt: "값을 숫자로 바꾸려 할 때 자주 쓰는 단항 연산자는 ____ 이다.",
      answer: "+",
      acceptedAnswers: ["+", '"+"', "'+'", "단항 +"],
      conceptGroup: "js-operators",
      explanation: "단항 + 는 숫자형 변환에 자주 사용된다.",
      sourceExcerptId: "operators-002",
    },
    {
      questionId: "operators-fb-002",
      type: "fill_blank",
      prompt: "나머지를 구하는 연산자는 ____ 이다.",
      answer: "%",
      acceptedAnswers: ["%", '"%"', "'%'"],
      conceptGroup: "js-operators",
      explanation: "% 연산자는 나머지를 반환한다.",
      sourceExcerptId: "operators-004",
    },
    {
      questionId: "operators-fb-003",
      type: "fill_blank",
      prompt: "거듭제곱 연산자는 ____ 이다.",
      answer: "**",
      acceptedAnswers: ["**", '"**"', "'**'"],
      conceptGroup: "js-operators",
      explanation: "** 는 거듭제곱 연산자다.",
      sourceExcerptId: "operators-005",
    },
  ],
};
