import type { QuestionPage } from "@/content/questions/types";

export const optionalChaining: QuestionPage = {
  sourceId: "optional-chaining",
  title: "옵셔널 체이닝 '?.'",
  url: "https://ko.javascript.info/optional-chaining",
  questions: [
    {
      questionId: "optional-chaining-yn-001",
      type: "yes_no",
      prompt: "옵셔널 체이닝은 중간 값이 null 또는 undefined여도 에러 없이 접근을 멈출 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-optional-chaining",
      explanation: "?. 는 nullish 값을 만나면 더 깊은 접근을 멈추고 undefined를 반환한다.",
      sourceExcerptId: "optional-chaining-001",
    },
    {
      questionId: "optional-chaining-yn-002",
      type: "yes_no",
      prompt: "옵셔널 체이닝은 존재하지 않는 변수 이름 자체를 안전하게 만들어준다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-optional-chaining",
      explanation: "선언되지 않은 변수에는 ?.를 붙여도 ReferenceError를 피할 수 없다.",
      sourceExcerptId: "optional-chaining-002",
    },
    {
      questionId: "optional-chaining-yn-003",
      type: "yes_no",
      prompt: "옵셔널 체이닝은 읽기나 호출 안전성 확보에 쓰고, 남용은 피하는 편이 좋다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-optional-chaining",
      explanation: "?. 는 꼭 필요한 nullish 방어에만 쓰는 것이 가독성에 좋다.",
      sourceExcerptId: "optional-chaining-003",
    },
    {
      questionId: "optional-chaining-mc-001",
      type: "multiple_choice",
      prompt: "obj?.prop 의 의미로 가장 맞는 것은?",
      answer: "obj가 nullish가 아니면 prop에 접근한다",
      choices: [
        "obj가 nullish가 아니면 prop에 접근한다",
        "항상 prop을 새로 만든다",
        "obj가 falsy면 무조건 에러를 던진다",
        "prop 값을 깊은 복사한다",
        "obj를 문자열로 바꾼다",
      ],
      conceptGroup: "js-optional-chaining",
      explanation: "?. 는 왼쪽 값이 null 또는 undefined가 아닐 때만 다음 접근을 진행한다.",
      sourceExcerptId: "optional-chaining-001",
    },
    {
      questionId: "optional-chaining-mc-002",
      type: "multiple_choice",
      prompt: "존재할 수도 있는 메서드를 안전하게 호출하려면?",
      answer: "obj.method?.()",
      choices: ["obj?.method()", "obj.method?.()", "obj?.method", "obj.method()", "method?.obj()"],
      conceptGroup: "js-optional-chaining",
      explanation: "메서드 존재 여부까지 안전하게 보려면 호출 위치에 ?.를 둔다.",
      sourceExcerptId: "optional-chaining-004",
    },
    {
      questionId: "optional-chaining-mc-003",
      type: "multiple_choice",
      prompt: "옵셔널 체이닝이 멈추는 기준은?",
      answer: "값이 null 또는 undefined일 때",
      choices: [
        "값이 0일 때",
        "값이 빈 문자열일 때",
        "값이 false일 때",
        "값이 null 또는 undefined일 때",
        "값이 NaN일 때",
      ],
      conceptGroup: "js-optional-chaining",
      explanation: "?. 는 falsy 전체가 아니라 nullish만 검사한다.",
      sourceExcerptId: "optional-chaining-001",
    },
    {
      questionId: "optional-chaining-fb-001",
      type: "fill_blank",
      prompt: "옵셔널 체이닝의 연산자 기호는 ____ 이다.",
      answer: "?.",
      acceptedAnswers: ["?."],
      conceptGroup: "js-optional-chaining",
      explanation: "옵셔널 체이닝은 `?.` 연산자를 사용한다.",
      sourceExcerptId: "optional-chaining-001",
    },
    {
      questionId: "optional-chaining-fb-002",
      type: "fill_blank",
      prompt: "옵셔널 체이닝은 값이 null 또는 ____ 일 때 멈춘다.",
      answer: "undefined",
      acceptedAnswers: ["undefined"],
      conceptGroup: "js-optional-chaining",
      explanation: "nullish 값인 null, undefined가 기준이다.",
      sourceExcerptId: "optional-chaining-001",
    },
    {
      questionId: "optional-chaining-fb-003",
      type: "fill_blank",
      prompt:
        "존재할 수도 있는 메서드 호출을 안전하게 처리할 때는 메서드 이름 뒤에 ____ 를 붙인다.",
      answer: "?.()",
      acceptedAnswers: ["?.()", "?."],
      conceptGroup: "js-optional-chaining",
      explanation: "호출 자체를 안전하게 하려면 `method?.()` 형태를 쓴다.",
      sourceExcerptId: "optional-chaining-004",
    },
  ],
};
