import type { QuestionPage } from "@/content/questions/types";

export const privateProtectedPropertiesMethods: QuestionPage = {
  sourceId: "private-protected-properties-methods",
  title: "private, protected 프로퍼티와 메서드",
  url: "https://ko.javascript.info/private-protected-properties-methods",
  questions: [
    {
      questionId: "private-protected-properties-methods-yn-001",
      type: "yes_no",
      prompt: "자바스크립트의 private 필드는 이름 앞에 #을 붙여 선언한다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-private-protected",
      explanation:
        "#으로 시작하는 클래스 필드는 클래스 외부에서 직접 접근할 수 없는 private 필드다.",
      sourceExcerptId: "private-protected-properties-methods-001",
    },
    {
      questionId: "private-protected-properties-methods-yn-002",
      type: "yes_no",
      prompt: "protected는 자바스크립트 문법 차원에서 강제되는 접근 제한자다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-private-protected",
      explanation:
        "자바스크립트에는 protected 문법이 없고, 보통 밑줄 관례 같은 방식으로 의도를 표현한다.",
      sourceExcerptId: "private-protected-properties-methods-002",
    },
    {
      questionId: "private-protected-properties-methods-yn-003",
      type: "yes_no",
      prompt: "#private 필드는 클래스 본문 안에서만 접근할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-private-protected",
      explanation: "#private 필드는 클래스 외부나 하위 클래스에서 직접 접근할 수 없다.",
      sourceExcerptId: "private-protected-properties-methods-003",
    },
    {
      questionId: "private-protected-properties-methods-mc-001",
      type: "multiple_choice",
      prompt: "자바스크립트 private 필드를 나타내는 문법은?",
      answer: "#field",
      choices: ["_field", "#field", "private field", "protected field", "@field"],
      conceptGroup: "js-private-protected",
      explanation: "표준 private 필드는 #field처럼 # 기호로 선언한다.",
      sourceExcerptId: "private-protected-properties-methods-001",
    },
    {
      questionId: "private-protected-properties-methods-mc-002",
      type: "multiple_choice",
      prompt: "밑줄로 시작하는 _value 같은 이름은 보통 무엇을 의미하는 관례인가?",
      answer: "protected처럼 내부용으로 쓰겠다는 의도",
      choices: [
        "문법상 private",
        "protected처럼 내부용으로 쓰겠다는 의도",
        "정적 필드",
        "읽기 전용 필드",
        "전역 변수",
      ],
      conceptGroup: "js-private-protected",
      explanation:
        "밑줄 접두사는 외부에서 직접 쓰지 말라는 관례일 뿐 문법적으로 접근을 막지는 않는다.",
      sourceExcerptId: "private-protected-properties-methods-002",
    },
    {
      questionId: "private-protected-properties-methods-mc-003",
      type: "multiple_choice",
      prompt: "#private 필드의 특징으로 맞는 것은?",
      answer: "클래스 외부에서 직접 접근할 수 없다",
      choices: [
        "객체마다 공유된다",
        "클래스 외부에서 직접 접근할 수 없다",
        "항상 static이다",
        "JSON으로 자동 직렬화된다",
        "prototype에 저장된다",
      ],
      conceptGroup: "js-private-protected",
      explanation: "#private 필드는 클래스 내부 구현을 감추기 위한 필드다.",
      sourceExcerptId: "private-protected-properties-methods-003",
    },
    {
      questionId: "private-protected-properties-methods-fb-001",
      type: "fill_blank",
      prompt: "표준 private 필드는 이름 앞에 기호 ____ 를 붙인다.",
      answer: "#",
      acceptedAnswers: ["#", "hash"],
      conceptGroup: "js-private-protected",
      explanation: "# 기호가 붙은 필드는 클래스 private 필드다.",
      sourceExcerptId: "private-protected-properties-methods-001",
    },
    {
      questionId: "private-protected-properties-methods-fb-002",
      type: "fill_blank",
      prompt: "자바스크립트에는 문법으로 강제되는 ____ 접근 제한자가 없다.",
      answer: "protected",
      acceptedAnswers: ["protected"],
      conceptGroup: "js-private-protected",
      explanation: "protected는 자바스크립트 표준 클래스 문법의 접근 제한자가 아니다.",
      sourceExcerptId: "private-protected-properties-methods-002",
    },
    {
      questionId: "private-protected-properties-methods-fb-003",
      type: "multiple_choice",
      prompt: "_value처럼 내부용 필드라는 관례를 나타낼 때 이름 앞에 붙는 기호는?",
      answer: "_",
      choices: ["#", "_", "@", "private", "protected"],
      conceptGroup: "js-private-protected",
      explanation: "밑줄 접두사는 내부용이라는 관례지만 실제 접근 제한은 아니다.",
      sourceExcerptId: "private-protected-properties-methods-002",
    },
  ],
};
