import type { QuestionPage } from "@/content/questions/types";

export const promiseChaining: QuestionPage = {
  sourceId: "promise-chaining",
  title: "프라미스 체이닝",
  url: "https://ko.javascript.info/promise-chaining",
  questions: [
    {
      questionId: "promise-chaining-yn-001",
      type: "yes_no",
      prompt: ".then 핸들러가 값을 반환하면 그 값은 다음 .then 핸들러로 전달될 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-promises",
      explanation: ".then은 새 프라미스를 반환하고, 핸들러의 반환값은 다음 체인의 result가 된다.",
      sourceExcerptId: "promise-chaining-001",
    },
    {
      questionId: "promise-chaining-yn-002",
      type: "yes_no",
      prompt:
        "같은 Promise에 .then을 여러 번 붙이면 각 핸들러는 항상 이전 핸들러 결과를 순서대로 받는다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-promises",
      explanation:
        "같은 Promise에 등록된 여러 핸들러는 같은 결과를 독립적으로 받고, 체이닝처럼 결과를 넘기지 않는다.",
      sourceExcerptId: "promise-chaining-002",
    },
    {
      questionId: "promise-chaining-yn-003",
      type: "yes_no",
      prompt: ".then 핸들러가 Promise를 반환하면 다음 체인은 그 Promise가 처리될 때까지 기다린다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-promises",
      explanation: "핸들러가 반환한 Promise가 처리되면 그 결과가 다음 .then으로 전달된다.",
      sourceExcerptId: "promise-chaining-003",
    },
    {
      questionId: "promise-chaining-mc-001",
      type: "multiple_choice",
      prompt: "프라미스 체이닝이 가능한 핵심 이유는?",
      answer: "then이 새 Promise를 반환하기 때문",
      choices: [
        "then이 새 Promise를 반환하기 때문",
        "catch가 동기 함수이기 때문",
        "resolve가 항상 숫자를 반환하기 때문",
        "fetch가 배열을 반환하기 때문",
        "finally가 상태를 직접 바꾸기 때문",
      ],
      conceptGroup: "js-promises",
      explanation:
        "promise.then을 호출하면 새 Promise가 반환되므로 그 뒤에 다시 then을 연결할 수 있다.",
      sourceExcerptId: "promise-chaining-001",
    },
    {
      questionId: "promise-chaining-mc-002",
      type: "multiple_choice",
      prompt: "Promise가 아닌데 .then 메서드를 가진 객체를 부르는 이름은?",
      answer: "thenable",
      choices: ["thenable", "iterable", "callable", "observable", "serializable"],
      conceptGroup: "js-promises",
      explanation:
        ".then 메서드를 가진 객체는 thenable로 취급되어 Promise 체인에서 호환될 수 있다.",
      sourceExcerptId: "promise-chaining-004",
    },
    {
      questionId: "promise-chaining-mc-003",
      type: "multiple_choice",
      prompt: "fetch 응답 본문을 JSON으로 읽을 때 주로 사용하는 메서드는?",
      answer: "response.json()",
      choices: [
        "response.json()",
        "response.stringify()",
        "JSON.response()",
        "fetch.json()",
        "Promise.json()",
      ],
      conceptGroup: "js-promises",
      explanation: "response.json()은 응답 본문을 읽고 JSON으로 파싱한 결과 Promise를 반환한다.",
      sourceExcerptId: "promise-chaining-005",
    },
    {
      questionId: "promise-chaining-fb-001",
      type: "fill_blank",
      prompt: "Promise 체인에서 다음 단계로 값을 넘길 때 주로 연결하는 메서드는 ____ 이다.",
      answer: "then",
      acceptedAnswers: ["then", ".then"],
      conceptGroup: "js-promises",
      explanation: ".then 핸들러의 반환값은 다음 .then 핸들러로 이어질 수 있다.",
      sourceExcerptId: "promise-chaining-001",
    },
    {
      questionId: "promise-chaining-fb-002",
      type: "fill_blank",
      prompt: ".then 메서드를 가진 Promise 호환 객체를 ____ 이라고 부른다.",
      answer: "thenable",
      acceptedAnswers: ["thenable", "thenable 객체"],
      conceptGroup: "js-promises",
      explanation: "thenable은 .then 메서드를 가진 객체로, Promise와 유사하게 처리될 수 있다.",
      sourceExcerptId: "promise-chaining-004",
    },
    {
      questionId: "promise-chaining-fb-003",
      type: "fill_blank",
      prompt: "promise.then(f1).catch(f2)에서 f1이 던진 에러는 ____ 에서 처리될 수 있다.",
      answer: "catch",
      acceptedAnswers: ["catch", ".catch", "f2"],
      conceptGroup: "js-promises",
      explanation: "then 핸들러에서 발생한 에러는 아래 체인으로 전달되어 catch에서 처리될 수 있다.",
      sourceExcerptId: "promise-chaining-006",
    },
  ],
};
