import type { QuestionPage } from "../types";

export const promiseBasics: QuestionPage = {
  sourceId: "promise-basics",
  title: "프라미스",
  url: "https://ko.javascript.info/promise-basics",
  questions: [
    {
      questionId: "promise-basics-yn-001",
      type: "yes_no",
      prompt: "Promise executor는 new Promise가 만들어질 때 자동으로 실행된다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-promises",
      explanation: "Promise 생성자에 전달한 executor 함수는 Promise 생성 시점에 즉시 실행된다.",
      sourceExcerptId: "promise-basics-001",
    },
    {
      questionId: "promise-basics-yn-002",
      type: "yes_no",
      prompt: "Promise는 한 번 fulfilled 또는 rejected가 되면 이후 상태 변경이 무시된다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-promises",
      explanation:
        "처리된 Promise는 결과나 에러 하나만 가지며, 이후 resolve나 reject 호출은 무시된다.",
      sourceExcerptId: "promise-basics-002",
    },
    {
      questionId: "promise-basics-yn-003",
      type: "yes_no",
      prompt: "Promise의 state와 result 내부 프로퍼티는 코드에서 직접 읽고 수정하는 값이다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-promises",
      explanation:
        "state와 result는 내부 프로퍼티이며, 결과 처리는 then, catch, finally로 연결한다.",
      sourceExcerptId: "promise-basics-003",
    },
    {
      questionId: "promise-basics-mc-001",
      type: "multiple_choice",
      prompt: "Promise 작업이 성공했을 때 호출하는 콜백은?",
      answer: "resolve",
      choices: ["resolve", "reject", "finally", "catch", "throw"],
      conceptGroup: "js-promises",
      explanation: "executor는 작업 성공 시 resolve(value)를 호출해 Promise를 이행 상태로 만든다.",
      sourceExcerptId: "promise-basics-001",
    },
    {
      questionId: "promise-basics-mc-002",
      type: "multiple_choice",
      prompt: "Promise 작업이 실패했을 때 호출하는 콜백은?",
      answer: "reject",
      choices: ["resolve", "reject", "then", "return", "await"],
      conceptGroup: "js-promises",
      explanation: "executor는 에러 발생 시 reject(error)를 호출해 Promise를 거부 상태로 만든다.",
      sourceExcerptId: "promise-basics-001",
    },
    {
      questionId: "promise-basics-mc-003",
      type: "multiple_choice",
      prompt: "Promise가 성공했을 때와 실패했을 때 모두 실행할 정리 작업에 적합한 메서드는?",
      answer: "finally",
      choices: ["then", "catch", "finally", "resolve", "reject"],
      conceptGroup: "js-promises",
      explanation: "finally는 Promise가 이행되든 거부되든 마무리 작업을 실행할 때 사용한다.",
      sourceExcerptId: "promise-basics-004",
    },
    {
      questionId: "promise-basics-fb-001",
      type: "fill_blank",
      prompt: "Promise가 처음 만들어졌고 아직 처리되지 않은 상태는 ____ 이다.",
      answer: "pending",
      acceptedAnswers: ["pending", "보류"],
      conceptGroup: "js-promises",
      explanation: "Promise는 처음 pending 상태였다가 fulfilled 또는 rejected 상태가 된다.",
      sourceExcerptId: "promise-basics-002",
    },
    {
      questionId: "promise-basics-fb-002",
      type: "fill_blank",
      prompt: "Promise가 거부되었을 때의 상태 이름은 ____ 이다.",
      answer: "rejected",
      acceptedAnswers: ["rejected", "거부"],
      conceptGroup: "js-promises",
      explanation: "reject(error)가 호출되면 Promise 상태는 rejected가 된다.",
      sourceExcerptId: "promise-basics-002",
    },
    {
      questionId: "promise-basics-fb-003",
      type: "fill_blank",
      prompt: "에러만 처리하려면 promise.____(handler)를 사용할 수 있다.",
      answer: "catch",
      acceptedAnswers: ["catch"],
      conceptGroup: "js-promises",
      explanation: "catch(handler)는 then(null, handler)와 같은 방식으로 에러를 처리한다.",
      sourceExcerptId: "promise-basics-005",
    },
  ],
};
