import type { QuestionPage } from "../types";

export const promiseApi: QuestionPage = {
  sourceId: "promise-api",
  title: "프라미스 API",
  url: "https://ko.javascript.info/promise-api",
  questions: [
    {
      questionId: "promise-api-yn-001",
      type: "yes_no",
      prompt: "Promise.all은 전달된 Promise가 모두 이행되어야 결과 배열을 반환한다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-promise-api",
      explanation: "Promise.all은 모든 입력 Promise가 이행되면 각 결과를 배열로 모아 이행한다.",
      sourceExcerptId: "promise-api-001",
    },
    {
      questionId: "promise-api-yn-002",
      type: "yes_no",
      prompt: "Promise.all은 입력 중 하나라도 거부되면 즉시 거부된다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-promise-api",
      explanation: "Promise.all은 하나라도 rejected가 되면 전체가 그 에러로 거부된다.",
      sourceExcerptId: "promise-api-001",
    },
    {
      questionId: "promise-api-yn-003",
      type: "yes_no",
      prompt: "Promise.allSettled는 하나가 실패하면 나머지 결과를 버리고 즉시 rejected가 된다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-promise-api",
      explanation:
        "Promise.allSettled는 모든 Promise가 처리될 때까지 기다린 뒤 각 상태와 값을 반환한다.",
      sourceExcerptId: "promise-api-002",
    },
    {
      questionId: "promise-api-mc-001",
      type: "multiple_choice",
      prompt: "여러 Promise가 모두 성공해야 다음 단계로 진행할 때 가장 적절한 메서드는?",
      answer: "Promise.all",
      choices: ["Promise.all", "Promise.race", "Promise.resolve", "Promise.reject", "Promise.any"],
      conceptGroup: "js-promise-api",
      explanation: "Promise.all은 여러 비동기 작업이 모두 성공해야 할 때 사용한다.",
      sourceExcerptId: "promise-api-001",
    },
    {
      questionId: "promise-api-mc-002",
      type: "multiple_choice",
      prompt: "가장 먼저 처리된 Promise의 결과나 에러를 그대로 사용하는 메서드는?",
      answer: "Promise.race",
      choices: [
        "Promise.all",
        "Promise.allSettled",
        "Promise.race",
        "Promise.any",
        "Promise.resolve",
      ],
      conceptGroup: "js-promise-api",
      explanation: "Promise.race는 가장 먼저 settled 된 Promise의 결과를 따른다.",
      sourceExcerptId: "promise-api-003",
    },
    {
      questionId: "promise-api-mc-003",
      type: "multiple_choice",
      prompt: "가장 먼저 이행된 Promise를 찾고, 모두 거부되면 AggregateError로 거부되는 메서드는?",
      answer: "Promise.any",
      choices: [
        "Promise.all",
        "Promise.any",
        "Promise.race",
        "Promise.reject",
        "Promise.allSettled",
      ],
      conceptGroup: "js-promise-api",
      explanation:
        "Promise.any는 첫 fulfilled 결과를 반환하고, 모두 실패하면 AggregateError로 거부된다.",
      sourceExcerptId: "promise-api-004",
    },
    {
      questionId: "promise-api-fb-001",
      type: "fill_blank",
      prompt: "여러 Promise가 모두 이행될 때까지 기다리는 메서드는 Promise.____ 이다.",
      answer: "all",
      acceptedAnswers: ["all", "Promise.all"],
      conceptGroup: "js-promise-api",
      explanation: "Promise.all은 입력된 Promise들이 모두 이행되어야 결과 배열을 반환한다.",
      sourceExcerptId: "promise-api-001",
    },
    {
      questionId: "promise-api-fb-002",
      type: "fill_blank",
      prompt: "성공/실패와 관계없이 모든 Promise 처리 결과를 보고 싶으면 Promise.____ 를 사용한다.",
      answer: "allSettled",
      acceptedAnswers: ["allSettled", "Promise.allSettled"],
      conceptGroup: "js-promise-api",
      explanation:
        "Promise.allSettled는 각 Promise의 status와 value 또는 reason을 결과로 제공한다.",
      sourceExcerptId: "promise-api-002",
    },
    {
      questionId: "promise-api-fb-003",
      type: "fill_blank",
      prompt: "비동기 작업 없이 바로 성공하는 Promise를 만들 때 Promise.____ 를 사용한다.",
      answer: "resolve",
      acceptedAnswers: ["resolve", "Promise.resolve"],
      conceptGroup: "js-promise-api",
      explanation: "Promise.resolve(value)는 value를 성공 결과로 가진 Promise를 만든다.",
      sourceExcerptId: "promise-api-005",
    },
  ],
};
