import type { QuestionPage } from "@/content/questions/types";

export const propertyAccessors: QuestionPage = {
  sourceId: "property-accessors",
  title: "프로퍼티 getter와 setter",
  url: "https://ko.javascript.info/property-accessors",
  questions: [
    {
      questionId: "property-accessors-yn-001",
      type: "yes_no",
      prompt: "getter는 프로퍼티를 읽을 때 호출될 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-property-accessors",
      explanation: "getter는 함수처럼 정의되지만 프로퍼티 읽기 문법으로 호출된다.",
      sourceExcerptId: "property-accessors-001",
    },
    {
      questionId: "property-accessors-yn-002",
      type: "yes_no",
      prompt: "setter는 반드시 값을 반환해야 한다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-property-accessors",
      explanation: "setter는 값을 받는 용도이며 반환값이 핵심이 아니다.",
      sourceExcerptId: "property-accessors-002",
    },
    {
      questionId: "property-accessors-yn-003",
      type: "yes_no",
      prompt: "접근자 프로퍼티는 value와 writable을 함께 가질 수 없다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-property-accessors",
      explanation:
        "접근자 프로퍼티는 get/set을 가지며 데이터 프로퍼티의 value, writable과 함께 쓸 수 없다.",
      sourceExcerptId: "property-accessors-003",
    },
    {
      questionId: "property-accessors-mc-001",
      type: "multiple_choice",
      prompt: "프로퍼티를 읽을 때 동작하는 접근자 함수는?",
      answer: "getter",
      choices: ["setter", "getter", "descriptor", "enumerator", "iterator"],
      conceptGroup: "js-property-accessors",
      explanation: "getter는 프로퍼티 읽기 시 계산된 값을 제공한다.",
      sourceExcerptId: "property-accessors-001",
    },
    {
      questionId: "property-accessors-mc-002",
      type: "multiple_choice",
      prompt: "접근자 프로퍼티를 설명자로 정의할 때 사용하는 키 조합으로 맞는 것은?",
      answer: "get / set",
      choices: ["value / writable", "key / value", "get / set", "read / write", "open / close"],
      conceptGroup: "js-property-accessors",
      explanation: "접근자 프로퍼티 설명자는 get과 set 함수를 사용한다.",
      sourceExcerptId: "property-accessors-003",
    },
    {
      questionId: "property-accessors-mc-003",
      type: "multiple_choice",
      prompt: "setter를 두는 주된 이유로 가장 적절한 것은?",
      answer: "대입 시 검증이나 가공 수행",
      choices: [
        "프로퍼티 삭제",
        "루프 순회 속도 향상",
        "대입 시 검증이나 가공 수행",
        "프로토타입 제거",
        "타입 변환 강제",
      ],
      conceptGroup: "js-property-accessors",
      explanation: "setter는 대입 시 유효성 검사나 내부 값 가공 로직을 넣기 좋다.",
      sourceExcerptId: "property-accessors-002",
    },
    {
      questionId: "property-accessors-fb-001",
      type: "fill_blank",
      prompt: "프로퍼티 읽기 시 실행되는 접근자 함수는 ____ 이다.",
      answer: "getter",
      acceptedAnswers: ["getter", "get"],
      conceptGroup: "js-property-accessors",
      explanation: "getter는 읽기 동작을 담당한다.",
      sourceExcerptId: "property-accessors-001",
    },
    {
      questionId: "property-accessors-fb-002",
      type: "fill_blank",
      prompt: "프로퍼티 대입 시 실행되는 접근자 함수는 ____ 이다.",
      answer: "setter",
      acceptedAnswers: ["setter", "set"],
      conceptGroup: "js-property-accessors",
      explanation: "setter는 값이 할당될 때 실행된다.",
      sourceExcerptId: "property-accessors-002",
    },
    {
      questionId: "property-accessors-fb-003",
      type: "fill_blank",
      prompt: "접근자 프로퍼티는 `value` 대신 `____ / set`을 사용한다.",
      answer: "get",
      acceptedAnswers: ["get"],
      conceptGroup: "js-property-accessors",
      explanation: "접근자 프로퍼티는 get, set 조합으로 정의된다.",
      sourceExcerptId: "property-accessors-003",
    },
  ],
};
