import type { QuestionPage } from "@/content/questions/types";

export const propertyDescriptors: QuestionPage = {
  sourceId: "property-descriptors",
  title: "프로퍼티 플래그와 설명자",
  url: "https://ko.javascript.info/property-descriptors",
  questions: [
    {
      questionId: "property-descriptors-yn-001",
      type: "yes_no",
      prompt: "Object.getOwnPropertyDescriptor는 프로퍼티 설명자를 반환한다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-property-descriptors",
      explanation: "Object.getOwnPropertyDescriptor는 값과 플래그를 담은 설명자 객체를 반환한다.",
      sourceExcerptId: "property-descriptors-001",
    },
    {
      questionId: "property-descriptors-yn-002",
      type: "yes_no",
      prompt: "writable이 false면 프로퍼티 값을 수정할 수 없다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-property-descriptors",
      explanation: "writable: false인 데이터 프로퍼티는 재할당이 막힌다.",
      sourceExcerptId: "property-descriptors-002",
    },
    {
      questionId: "property-descriptors-yn-003",
      type: "yes_no",
      prompt: "enumerable이 false여도 for...in에서 항상 보인다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-property-descriptors",
      explanation: "enumerable이 false면 일반 열거에서 제외된다.",
      sourceExcerptId: "property-descriptors-003",
    },
    {
      questionId: "property-descriptors-mc-001",
      type: "multiple_choice",
      prompt: "프로퍼티 삭제 가능 여부를 제어하는 플래그는?",
      answer: "configurable",
      choices: ["writable", "enumerable", "configurable", "value", "frozen"],
      conceptGroup: "js-property-descriptors",
      explanation: "configurable은 삭제 가능 여부와 설명자 재정의를 제어한다.",
      sourceExcerptId: "property-descriptors-004",
    },
    {
      questionId: "property-descriptors-mc-002",
      type: "multiple_choice",
      prompt: "프로퍼티를 열거 대상에서 숨기고 싶을 때 보통 바꾸는 것은?",
      answer: "enumerable",
      choices: ["writable", "enumerable", "configurable", "prototype", "getter"],
      conceptGroup: "js-property-descriptors",
      explanation: "enumerable을 false로 두면 for...in, Object.keys 등에서 숨길 수 있다.",
      sourceExcerptId: "property-descriptors-003",
    },
    {
      questionId: "property-descriptors-mc-003",
      type: "multiple_choice",
      prompt: "설명자를 직접 정의하는 메서드는?",
      answer: "Object.defineProperty",
      choices: [
        "Object.assign",
        "Object.keys",
        "Object.defineProperty",
        "Object.entries",
        "Object.freeze",
      ],
      conceptGroup: "js-property-descriptors",
      explanation: "Object.defineProperty로 프로퍼티 값과 플래그를 직접 정의할 수 있다.",
      sourceExcerptId: "property-descriptors-005",
    },
    {
      questionId: "property-descriptors-fb-001",
      type: "fill_blank",
      prompt: "프로퍼티가 열거에 보일지 정하는 플래그는 ____ 이다.",
      answer: "enumerable",
      acceptedAnswers: ["enumerable"],
      conceptGroup: "js-property-descriptors",
      explanation: "enumerable은 프로퍼티가 열거 가능한지 여부를 결정한다.",
      sourceExcerptId: "property-descriptors-003",
    },
    {
      questionId: "property-descriptors-fb-002",
      type: "fill_blank",
      prompt: "프로퍼티 값 수정 가능 여부를 정하는 플래그는 ____ 이다.",
      answer: "writable",
      acceptedAnswers: ["writable"],
      conceptGroup: "js-property-descriptors",
      explanation: "writable은 값 재할당 가능 여부를 나타낸다.",
      sourceExcerptId: "property-descriptors-002",
    },
    {
      questionId: "property-descriptors-fb-003",
      type: "fill_blank",
      prompt: "설명자 기반으로 프로퍼티를 정의하는 메서드는 Object.____ 이다.",
      answer: "defineProperty",
      acceptedAnswers: ["defineProperty", "Object.defineProperty"],
      conceptGroup: "js-property-descriptors",
      explanation: "Object.defineProperty는 설명자를 기반으로 프로퍼티를 만든다.",
      sourceExcerptId: "property-descriptors-005",
    },
  ],
};
