import type { QuestionPage } from "@/content/questions/types";

export const prototypeInheritance: QuestionPage = {
  sourceId: "prototype-inheritance",
  title: "프로토타입 상속",
  url: "https://ko.javascript.info/prototype-inheritance",
  questions: [
    {
      questionId: "prototype-inheritance-yn-001",
      type: "yes_no",
      prompt: "객체에서 프로퍼티를 찾지 못하면 프로토타입 체인을 따라 검색할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-prototype-inheritance",
      explanation: "자바스크립트는 객체에 없는 프로퍼티를 프로토타입에서 이어서 찾는다.",
      sourceExcerptId: "prototype-inheritance-001",
    },
    {
      questionId: "prototype-inheritance-yn-002",
      type: "yes_no",
      prompt: "__proto__는 객체의 [[Prototype]]에 접근하는 방법 중 하나다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-prototype-inheritance",
      explanation: "__proto__는 [[Prototype]]을 다루는 역사적인 접근자다.",
      sourceExcerptId: "prototype-inheritance-002",
    },
    {
      questionId: "prototype-inheritance-yn-003",
      type: "yes_no",
      prompt: "프로토타입 체인은 무한히 길어질 수 있고 순환 참조도 허용된다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-prototype-inheritance",
      explanation: "프로토타입 체인은 순환 참조가 허용되지 않으며 결국 null에서 끝난다.",
      sourceExcerptId: "prototype-inheritance-003",
    },
    {
      questionId: "prototype-inheritance-mc-001",
      type: "multiple_choice",
      prompt: "객체 자신의 프로퍼티에 값이 없을 때 이어서 탐색하는 대상은?",
      answer: "프로토타입",
      choices: ["전역 객체", "프로토타입", "클로저", "모듈", "스택"],
      conceptGroup: "js-prototype-inheritance",
      explanation: "객체에 없는 프로퍼티는 프로토타입 체인을 따라 검색된다.",
      sourceExcerptId: "prototype-inheritance-001",
    },
    {
      questionId: "prototype-inheritance-mc-002",
      type: "multiple_choice",
      prompt: "프로토타입 체인의 끝에 있는 값은?",
      answer: "null",
      choices: ["undefined", "null", "Object", "window", "prototype"],
      conceptGroup: "js-prototype-inheritance",
      explanation: "프로토타입 체인은 더 이상 이어질 대상이 없는 null에서 끝난다.",
      sourceExcerptId: "prototype-inheritance-003",
    },
    {
      questionId: "prototype-inheritance-mc-003",
      type: "multiple_choice",
      prompt: "프로토타입에 있는 메서드를 호출할 때 this는 보통 무엇을 가리키는가?",
      answer: "메서드를 호출한 객체",
      choices: ["프로토타입 객체", "전역 객체", "메서드를 호출한 객체", "null", "함수 자체"],
      conceptGroup: "js-prototype-inheritance",
      explanation: "상속받은 메서드라도 this는 점 앞의 객체, 즉 호출한 객체를 가리킨다.",
      sourceExcerptId: "prototype-inheritance-004",
    },
    {
      questionId: "prototype-inheritance-fb-001",
      type: "fill_blank",
      prompt: "객체들이 공유 동작을 물려받는 연결 구조를 ____ 체인이라고 한다.",
      answer: "프로토타입",
      acceptedAnswers: ["프로토타입", "prototype"],
      conceptGroup: "js-prototype-inheritance",
      explanation: "프로토타입 체인은 객체 간 상속 관계를 이어주는 구조다.",
      sourceExcerptId: "prototype-inheritance-001",
    },
    {
      questionId: "prototype-inheritance-fb-002",
      type: "fill_blank",
      prompt: "프로토타입 체인은 마지막에 ____ 에 도달한다.",
      answer: "null",
      acceptedAnswers: ["null"],
      conceptGroup: "js-prototype-inheritance",
      explanation: "더 이상 상속받을 대상이 없으면 프로토타입은 null이다.",
      sourceExcerptId: "prototype-inheritance-003",
    },
    {
      questionId: "prototype-inheritance-fb-003",
      type: "fill_blank",
      prompt: "상속받은 메서드 안의 this는 보통 메서드를 ____ 객체를 가리킨다.",
      answer: "호출한",
      acceptedAnswers: ["호출한", "실행한", "call한"],
      conceptGroup: "js-prototype-inheritance",
      explanation: "this는 메서드가 어디에 정의됐는지가 아니라 어떻게 호출됐는지에 따라 결정된다.",
      sourceExcerptId: "prototype-inheritance-004",
    },
  ],
};
