import type { QuestionPage } from "@/content/questions/types";

export const prototypeMethods: QuestionPage = {
  sourceId: "prototype-methods",
  title: "프로토타입 메서드와 __proto__가 없는 객체",
  url: "https://ko.javascript.info/prototype-methods",
  questions: [
    {
      questionId: "prototype-methods-yn-001",
      type: "yes_no",
      prompt: "Object.create(proto)는 지정한 proto를 [[Prototype]]으로 갖는 객체를 만들 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-prototype-methods",
      explanation:
        "Object.create는 첫 번째 인수로 받은 객체를 새 객체의 [[Prototype]]으로 설정한다.",
      sourceExcerptId: "prototype-methods-001",
    },
    {
      questionId: "prototype-methods-yn-002",
      type: "yes_no",
      prompt: "Object.getPrototypeOf(obj)는 obj의 [[Prototype]]을 반환한다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-prototype-methods",
      explanation: "Object.getPrototypeOf는 객체의 프로토타입을 읽는 표준 메서드다.",
      sourceExcerptId: "prototype-methods-002",
    },
    {
      questionId: "prototype-methods-yn-003",
      type: "yes_no",
      prompt: "Object.create(null)로 만든 객체도 Object.prototype 메서드를 자동으로 상속받는다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-prototype-methods",
      explanation:
        "Object.create(null)은 프로토타입이 null인 객체를 만들어 Object.prototype을 상속받지 않는다.",
      sourceExcerptId: "prototype-methods-003",
    },
    {
      questionId: "prototype-methods-mc-001",
      type: "multiple_choice",
      prompt: "객체의 프로토타입을 읽는 표준 메서드는?",
      answer: "Object.getPrototypeOf",
      choices: [
        "Object.getPrototypeOf",
        "Object.setPrototypeOf",
        "Object.create",
        "Object.assign",
        "Object.keys",
      ],
      conceptGroup: "js-prototype-methods",
      explanation: "Object.getPrototypeOf는 객체의 [[Prototype]] 값을 반환한다.",
      sourceExcerptId: "prototype-methods-002",
    },
    {
      questionId: "prototype-methods-mc-002",
      type: "multiple_choice",
      prompt: "프로토타입이 없는 순수 사전형 객체를 만들 때 사용할 수 있는 코드는?",
      answer: "Object.create(null)",
      choices: [
        "Object.create(null)",
        "new Object(null)",
        "Object.assign(null)",
        "Object.keys(null)",
        "Object.freeze(null)",
      ],
      conceptGroup: "js-prototype-methods",
      explanation: "Object.create(null)은 [[Prototype]]이 null인 객체를 만든다.",
      sourceExcerptId: "prototype-methods-003",
    },
    {
      questionId: "prototype-methods-mc-003",
      type: "multiple_choice",
      prompt: "객체의 프로토타입을 바꾸는 표준 메서드는?",
      answer: "Object.setPrototypeOf",
      choices: [
        "Object.getPrototypeOf",
        "Object.setPrototypeOf",
        "Object.defineProperty",
        "Object.fromEntries",
        "Object.values",
      ],
      conceptGroup: "js-prototype-methods",
      explanation: "Object.setPrototypeOf는 객체의 [[Prototype]]을 설정하는 표준 메서드다.",
      sourceExcerptId: "prototype-methods-004",
    },
    {
      questionId: "prototype-methods-fb-001",
      type: "fill_blank",
      prompt: "지정한 프로토타입을 가진 객체를 만들 때 Object.____ 를 사용한다.",
      answer: "create",
      acceptedAnswers: ["create", "Object.create"],
      conceptGroup: "js-prototype-methods",
      explanation: "Object.create(proto)는 proto를 [[Prototype]]으로 갖는 새 객체를 만든다.",
      sourceExcerptId: "prototype-methods-001",
    },
    {
      questionId: "prototype-methods-fb-002",
      type: "fill_blank",
      prompt: "객체의 프로토타입을 읽는 메서드는 Object.____ 이다.",
      answer: "getPrototypeOf",
      acceptedAnswers: ["getPrototypeOf", "Object.getPrototypeOf"],
      conceptGroup: "js-prototype-methods",
      explanation: "Object.getPrototypeOf는 객체의 [[Prototype]]을 반환한다.",
      sourceExcerptId: "prototype-methods-002",
    },
    {
      questionId: "prototype-methods-fb-003",
      type: "fill_blank",
      prompt: "Object.create(____)은 프로토타입이 없는 객체를 만든다.",
      answer: "null",
      acceptedAnswers: ["null"],
      conceptGroup: "js-prototype-methods",
      explanation: "Object.create(null)은 [[Prototype]]이 null인 객체를 만든다.",
      sourceExcerptId: "prototype-methods-003",
    },
  ],
};
