import type { QuestionPage } from "../types";

export const restParametersSpread: QuestionPage = {
  sourceId: "rest-parameters-spread",
  title: "나머지 매개변수와 전개 문법",
  url: "https://ko.javascript.info/rest-parameters-spread",
  questions: [
    {
      questionId: "rest-parameters-spread-yn-001",
      type: "yes_no",
      prompt: "함수 매개변수 앞의 `...`는 남은 인수를 배열로 모을 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-rest-spread",
      explanation: "rest parameter는 전달된 남은 인수들을 배열로 모은다.",
      sourceExcerptId: "rest-parameters-spread-001",
    },
    {
      questionId: "rest-parameters-spread-yn-002",
      type: "yes_no",
      prompt: "배열 앞에 `...`를 붙이면 요소를 펼칠 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-rest-spread",
      explanation: "spread 문법은 iterable의 요소를 하나씩 펼친다.",
      sourceExcerptId: "rest-parameters-spread-002",
    },
    {
      questionId: "rest-parameters-spread-yn-003",
      type: "yes_no",
      prompt: "rest parameter와 spread syntax는 완전히 다른 기호를 사용한다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-rest-spread",
      explanation: "둘 다 `...`를 사용하지만 위치와 역할이 다르다.",
      sourceExcerptId: "rest-parameters-spread-003",
    },
    {
      questionId: "rest-parameters-spread-mc-001",
      type: "multiple_choice",
      prompt: "함수 정의에서 `...args`의 역할은?",
      answer: "남은 인수를 배열로 수집",
      choices: [
        "인수를 문자열로 변환",
        "남은 인수를 배열로 수집",
        "객체를 복사",
        "첫 번째 인수만 추출",
        "인수 개수를 제한",
      ],
      conceptGroup: "js-rest-spread",
      explanation: "rest parameter는 남은 인수들을 배열 `args`에 모은다.",
      sourceExcerptId: "rest-parameters-spread-001",
    },
    {
      questionId: "rest-parameters-spread-mc-002",
      type: "multiple_choice",
      prompt: "Math.max에 배열 값을 그대로 넘기려면 주로 무엇을 쓰는가?",
      answer: "spread syntax",
      choices: ["rest parameter", "spread syntax", "JSON.parse", "Object.keys", "Array.from"],
      conceptGroup: "js-rest-spread",
      explanation: "spread 문법으로 배열 요소를 개별 인수처럼 펼쳐 전달할 수 있다.",
      sourceExcerptId: "rest-parameters-spread-002",
    },
    {
      questionId: "rest-parameters-spread-mc-003",
      type: "multiple_choice",
      prompt: "rest parameter는 함수 정의에서 몇 개까지 둘 수 있는가?",
      answer: "하나, 마지막 위치에만",
      choices: ["무제한", "하나, 마지막 위치에만", "두 개", "첫 위치에만", "인수 없을 때만"],
      conceptGroup: "js-rest-spread",
      explanation: "rest parameter는 하나만 가능하고 반드시 마지막 매개변수여야 한다.",
      sourceExcerptId: "rest-parameters-spread-004",
    },
    {
      questionId: "rest-parameters-spread-fb-001",
      type: "fill_blank",
      prompt: "함수 정의에서 남은 인수를 모으는 문법은 ____ parameter라고 부른다.",
      answer: "rest",
      acceptedAnswers: ["rest", "rest parameter"],
      conceptGroup: "js-rest-spread",
      explanation: "rest parameter는 남은 인수를 하나의 배열에 수집한다.",
      sourceExcerptId: "rest-parameters-spread-001",
    },
    {
      questionId: "rest-parameters-spread-fb-002",
      type: "fill_blank",
      prompt: "배열이나 문자열을 펼쳐 인수로 넘길 때 쓰는 문법은 ____ syntax다.",
      answer: "spread",
      acceptedAnswers: ["spread", "spread syntax"],
      conceptGroup: "js-rest-spread",
      explanation: "spread syntax는 iterable 요소를 하나씩 펼친다.",
      sourceExcerptId: "rest-parameters-spread-002",
    },
    {
      questionId: "rest-parameters-spread-fb-003",
      type: "fill_blank",
      prompt: "rest와 spread는 모두 기호 ____ 를 사용한다.",
      answer: "...",
      acceptedAnswers: ["...", "점 세 개"],
      conceptGroup: "js-rest-spread",
      explanation: "둘 다 `...`를 사용하지만 문맥에 따라 의미가 달라진다.",
      sourceExcerptId: "rest-parameters-spread-003",
    },
  ],
};
