import type { QuestionPage } from "@/content/questions/types";

export const staticPropertiesMethods: QuestionPage = {
  sourceId: "static-properties-methods",
  title: "정적 메서드와 정적 프로퍼티",
  url: "https://ko.javascript.info/static-properties-methods",
  questions: [
    {
      questionId: "static-properties-methods-yn-001",
      type: "yes_no",
      prompt: "static 메서드는 클래스 자체에 속하며 인스턴스 메서드가 아니다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-static-properties-methods",
      explanation:
        "static 메서드는 클래스 생성자에 직접 붙으며 인스턴스의 prototype 메서드가 아니다.",
      sourceExcerptId: "static-properties-methods-001",
    },
    {
      questionId: "static-properties-methods-yn-002",
      type: "yes_no",
      prompt: "정적 메서드는 인스턴스에서 바로 호출하는 것이 기본 사용법이다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-static-properties-methods",
      explanation: "정적 메서드는 보통 ClassName.method() 형태로 클래스에서 직접 호출한다.",
      sourceExcerptId: "static-properties-methods-002",
    },
    {
      questionId: "static-properties-methods-yn-003",
      type: "yes_no",
      prompt: "정적 프로퍼티는 클래스 자체에 데이터를 보관할 때 사용할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-static-properties-methods",
      explanation:
        "static 프로퍼티는 특정 인스턴스가 아니라 클래스 자체와 관련된 값을 둘 때 유용하다.",
      sourceExcerptId: "static-properties-methods-003",
    },
    {
      questionId: "static-properties-methods-mc-001",
      type: "multiple_choice",
      prompt: "정적 메서드를 선언할 때 사용하는 키워드는?",
      answer: "static",
      choices: ["static", "const", "class", "extends", "super"],
      conceptGroup: "js-static-properties-methods",
      explanation: "static 키워드를 메서드 앞에 붙이면 정적 메서드가 된다.",
      sourceExcerptId: "static-properties-methods-001",
    },
    {
      questionId: "static-properties-methods-mc-002",
      type: "multiple_choice",
      prompt: "class Article { static compare() {} }에서 compare 호출 형태로 맞는 것은?",
      answer: "Article.compare()",
      choices: [
        "new Article().compare()",
        "Article.prototype.compare()",
        "Article.compare()",
        "compare.Article()",
        "super.compare()",
      ],
      conceptGroup: "js-static-properties-methods",
      explanation: "정적 메서드는 클래스 이름을 통해 직접 호출한다.",
      sourceExcerptId: "static-properties-methods-002",
    },
    {
      questionId: "static-properties-methods-mc-003",
      type: "multiple_choice",
      prompt: "정적 메서드 사용 예로 가장 적절한 것은?",
      answer: "팩토리 메서드",
      choices: [
        "인스턴스 상태 변경",
        "팩토리 메서드",
        "DOM 이벤트 핸들러",
        "지역 변수 선언",
        "반복문 제어",
      ],
      conceptGroup: "js-static-properties-methods",
      explanation: "정적 메서드는 인스턴스 생성 보조나 유틸리티 같은 클래스 수준 동작에 잘 맞는다.",
      sourceExcerptId: "static-properties-methods-004",
    },
    {
      questionId: "static-properties-methods-fb-001",
      type: "fill_blank",
      prompt: "클래스 자체에 속한 메서드를 만들 때 ____ 키워드를 사용한다.",
      answer: "static",
      acceptedAnswers: ["static"],
      conceptGroup: "js-static-properties-methods",
      explanation: "static은 메서드나 프로퍼티를 클래스 자체에 연결한다.",
      sourceExcerptId: "static-properties-methods-001",
    },
    {
      questionId: "static-properties-methods-fb-002",
      type: "fill_blank",
      prompt: "정적 메서드는 보통 ____ 이름으로 직접 호출한다.",
      answer: "클래스",
      acceptedAnswers: ["클래스", "class", "ClassName"],
      conceptGroup: "js-static-properties-methods",
      explanation: "정적 메서드는 ClassName.method() 형태로 호출한다.",
      sourceExcerptId: "static-properties-methods-002",
    },
    {
      questionId: "static-properties-methods-fb-003",
      type: "fill_blank",
      prompt: "정적 메서드는 인스턴스의 ____ 에 저장되는 일반 메서드와 다르다.",
      answer: "prototype",
      acceptedAnswers: ["prototype"],
      conceptGroup: "js-static-properties-methods",
      explanation:
        "일반 클래스 메서드는 prototype에 저장되지만 정적 메서드는 클래스 자체에 저장된다.",
      sourceExcerptId: "static-properties-methods-001",
    },
  ],
};
