import type { QuestionPage } from "../types";

export const switchStatement: QuestionPage = {
  sourceId: "switch",
  title: "switch문",
  url: "https://ko.javascript.info/switch",
  questions: [
    {
      questionId: "switch-yn-001",
      type: "yes_no",
      prompt: "switch 문은 여러 case 중 일치하는 값을 찾아 분기할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-switch",
      explanation: "switch는 하나의 값을 여러 case와 비교해 분기할 때 쓴다.",
      sourceExcerptId: "switch-001",
    },
    {
      questionId: "switch-yn-002",
      type: "yes_no",
      prompt: "break를 생략하면 다음 case로 실행이 이어질 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-switch",
      explanation: "break가 없으면 다음 case로 흐름이 이어지는 fall-through가 발생한다.",
      sourceExcerptId: "switch-002",
    },
    {
      questionId: "switch-yn-003",
      type: "yes_no",
      prompt: "switch 문 비교는 느슨한 동등 비교(==)를 사용한다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-switch",
      explanation: "switch는 엄격한 동등 비교(===)로 case를 비교한다.",
      sourceExcerptId: "switch-003",
    },
    {
      questionId: "switch-mc-001",
      type: "multiple_choice",
      prompt: "일치하는 case가 하나도 없을 때 실행할 블록은?",
      answer: "default",
      choices: ["default", "else", "fallback", "finally", "otherwise"],
      conceptGroup: "js-switch",
      explanation: "default는 어떤 case도 일치하지 않을 때 실행된다.",
      sourceExcerptId: "switch-004",
    },
    {
      questionId: "switch-mc-002",
      type: "multiple_choice",
      prompt: "switch 문에서 다음 case로 흐름이 이어지는 현상은?",
      answer: "fall-through",
      choices: ["hoisting", "fall-through", "short-circuit", "coalescing", "currying"],
      conceptGroup: "js-switch",
      explanation: "break가 없으면 다음 case로 이어지는 fall-through가 생긴다.",
      sourceExcerptId: "switch-002",
    },
    {
      questionId: "switch-mc-003",
      type: "multiple_choice",
      prompt: "switch(x)에서 case 비교에 사용되는 연산은?",
      answer: "===",
      choices: ["==", "===", "=", "!==", "??"],
      conceptGroup: "js-switch",
      explanation: "switch는 case를 비교할 때 엄격한 동등 비교를 사용한다.",
      sourceExcerptId: "switch-003",
    },
    {
      questionId: "switch-fb-001",
      type: "fill_blank",
      prompt: "어떤 case도 일치하지 않을 때 실행할 블록 이름은 ____ 이다.",
      answer: "default",
      acceptedAnswers: ["default"],
      conceptGroup: "js-switch",
      explanation: "default는 switch 문의 기본 분기다.",
      sourceExcerptId: "switch-004",
    },
    {
      questionId: "switch-fb-002",
      type: "fill_blank",
      prompt: "현재 case 실행 후 switch 문을 빠져나가려면 ____ 를 사용한다.",
      answer: "break",
      acceptedAnswers: ["break"],
      conceptGroup: "js-switch",
      explanation: "break는 현재 case 실행 후 switch 문을 종료한다.",
      sourceExcerptId: "switch-002",
    },
    {
      questionId: "switch-fb-003",
      type: "fill_blank",
      prompt: "switch 문의 case 비교는 ____ 비교를 사용한다.",
      answer: "엄격한",
      acceptedAnswers: ["엄격한", "strict", "==="],
      conceptGroup: "js-switch",
      explanation: "switch는 ==가 아니라 === 기준으로 값을 비교한다.",
      sourceExcerptId: "switch-003",
    },
  ],
};
