import type { QuestionPage } from "../types";

export const symbolType: QuestionPage = {
  sourceId: "symbol",
  title: "심볼형",
  url: "https://ko.javascript.info/symbol",
  questions: [
    {
      questionId: "symbol-yn-001",
      type: "yes_no",
      prompt: "Symbol()로 만든 값은 항상 고유하다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-symbols",
      explanation: "설명이 같아도 각각의 Symbol() 호출은 서로 다른 고유 심볼을 만든다.",
      sourceExcerptId: "symbol-001",
    },
    {
      questionId: "symbol-yn-002",
      type: "yes_no",
      prompt: "심볼은 객체 프로퍼티 키로 사용할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-symbols",
      explanation: "심볼은 문자열 대신 객체의 고유 프로퍼티 키로 쓸 수 있다.",
      sourceExcerptId: "symbol-002",
    },
    {
      questionId: "symbol-yn-003",
      type: "yes_no",
      prompt: "for...in은 심볼 키 프로퍼티도 자동으로 순회한다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-symbols",
      explanation: "심볼 키 프로퍼티는 일반적인 열거에서 자동으로 제외된다.",
      sourceExcerptId: "symbol-003",
    },
    {
      questionId: "symbol-mc-001",
      type: "multiple_choice",
      prompt: "같은 설명을 가진 두 Symbol('id')의 비교 결과는?",
      answer: "false",
      choices: ["true", "false", "undefined", "null", "error"],
      conceptGroup: "js-symbols",
      explanation: "설명이 같아도 서로 다른 심볼이므로 비교 결과는 false다.",
      sourceExcerptId: "symbol-001",
    },
    {
      questionId: "symbol-mc-002",
      type: "multiple_choice",
      prompt: "전역 심볼 레지스트리에서 심볼을 가져올 때 쓰는 것은?",
      answer: "Symbol.for",
      choices: ["Symbol.new", "Symbol.for", "Symbol.of", "Symbol.key", "Symbol.global"],
      conceptGroup: "js-symbols",
      explanation: "Symbol.for는 전역 심볼 레지스트리에서 심볼을 만들거나 가져온다.",
      sourceExcerptId: "symbol-004",
    },
    {
      questionId: "symbol-mc-003",
      type: "multiple_choice",
      prompt: "심볼 프로퍼티가 기본 열거에서 숨겨지는 이유로 가장 가까운 것은?",
      answer: "내부 구현용 고유 키를 만들기 위해",
      choices: [
        "문자열보다 느리기 때문에",
        "항상 private이기 때문에",
        "내부 구현용 고유 키를 만들기 위해",
        "객체에 하나만 허용되기 때문에",
        "배열에서는 쓸 수 없기 때문에",
      ],
      conceptGroup: "js-symbols",
      explanation: "심볼은 이름 충돌 없이 내부용 고유 프로퍼티를 둘 때 자주 쓴다.",
      sourceExcerptId: "symbol-003",
    },
    {
      questionId: "symbol-fb-001",
      type: "fill_blank",
      prompt: "고유한 원시값을 만드는 내장 함수는 ____ 이다.",
      answer: "Symbol",
      acceptedAnswers: ["Symbol"],
      conceptGroup: "js-symbols",
      explanation: "Symbol은 고유한 심볼 값을 만드는 내장 함수다.",
      sourceExcerptId: "symbol-001",
    },
    {
      questionId: "symbol-fb-002",
      type: "fill_blank",
      prompt: "전역 심볼 레지스트리를 사용할 때는 Symbol.____ 를 쓴다.",
      answer: "for",
      acceptedAnswers: ["for"],
      conceptGroup: "js-symbols",
      explanation: "Symbol.for는 전역 레지스트리 기반으로 심볼을 다룬다.",
      sourceExcerptId: "symbol-004",
    },
    {
      questionId: "symbol-fb-003",
      type: "fill_blank",
      prompt: "심볼 키 프로퍼티는 일반적인 ____ 에서 자동으로 제외될 수 있다.",
      answer: "열거",
      acceptedAnswers: ["열거", "enumeration"],
      conceptGroup: "js-symbols",
      explanation: "심볼 프로퍼티는 기본적인 열거 흐름에서 감춰진다.",
      sourceExcerptId: "symbol-003",
    },
  ],
};
