import type { QuestionPage } from "../types";

export const tryCatch: QuestionPage = {
  sourceId: "try-catch",
  title: "try...catch와 에러 핸들링",
  url: "https://ko.javascript.info/try-catch",
  questions: [
    {
      questionId: "try-catch-yn-001",
      type: "yes_no",
      prompt: "try...catch는 실행 중 발생한 에러를 잡아 프로그램 중단을 막을 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-error-handling",
      explanation: "try 블록에서 발생한 런타임 에러는 catch 블록에서 처리할 수 있다.",
      sourceExcerptId: "try-catch-001",
    },
    {
      questionId: "try-catch-yn-002",
      type: "yes_no",
      prompt: "try...catch는 문법 에러도 코드 실행 전에 항상 잡아준다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-error-handling",
      explanation:
        "try...catch는 실행 가능한 코드의 런타임 에러를 다루며, 파싱 단계 문법 에러는 잡지 못한다.",
      sourceExcerptId: "try-catch-002",
    },
    {
      questionId: "try-catch-yn-003",
      type: "yes_no",
      prompt: "finally 블록은 에러 여부와 관계없이 실행될 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-error-handling",
      explanation:
        "finally는 try가 정상 종료되든 catch로 넘어가든 마지막 정리 작업에 사용할 수 있다.",
      sourceExcerptId: "try-catch-003",
    },
    {
      questionId: "try-catch-mc-001",
      type: "multiple_choice",
      prompt: "에러가 발생할 수 있는 코드를 감싸는 블록은?",
      answer: "try",
      choices: ["try", "catch", "finally", "throw", "Error"],
      conceptGroup: "js-error-handling",
      explanation: "try 블록 안에 에러가 발생할 수 있는 코드를 둔다.",
      sourceExcerptId: "try-catch-001",
    },
    {
      questionId: "try-catch-mc-002",
      type: "multiple_choice",
      prompt: "잡힌 에러를 처리하는 블록은?",
      answer: "catch",
      choices: ["try", "catch", "finally", "class", "extends"],
      conceptGroup: "js-error-handling",
      explanation: "catch 블록은 try에서 발생한 에러를 받아 처리한다.",
      sourceExcerptId: "try-catch-001",
    },
    {
      questionId: "try-catch-mc-003",
      type: "multiple_choice",
      prompt: "성공과 실패 여부와 관계없이 정리 코드를 넣기 좋은 블록은?",
      answer: "finally",
      choices: ["try", "catch", "finally", "throw", "return"],
      conceptGroup: "js-error-handling",
      explanation: "finally는 리소스 정리처럼 마지막에 실행되어야 하는 코드를 두기 좋다.",
      sourceExcerptId: "try-catch-003",
    },
    {
      questionId: "try-catch-fb-001",
      type: "fill_blank",
      prompt: "에러가 발생할 수 있는 코드는 ____ 블록에 넣는다.",
      answer: "try",
      acceptedAnswers: ["try"],
      conceptGroup: "js-error-handling",
      explanation: "try 블록은 에러 감지 대상 코드를 감싼다.",
      sourceExcerptId: "try-catch-001",
    },
    {
      questionId: "try-catch-fb-002",
      type: "fill_blank",
      prompt: "try에서 발생한 에러를 처리하는 블록은 ____ 이다.",
      answer: "catch",
      acceptedAnswers: ["catch"],
      conceptGroup: "js-error-handling",
      explanation: "catch는 try 블록에서 던져진 에러를 받아 처리한다.",
      sourceExcerptId: "try-catch-001",
    },
    {
      questionId: "try-catch-fb-003",
      type: "fill_blank",
      prompt: "에러 여부와 관계없이 마지막에 실행될 수 있는 블록은 ____ 이다.",
      answer: "finally",
      acceptedAnswers: ["finally"],
      conceptGroup: "js-error-handling",
      explanation: "finally는 성공, 실패와 관계없이 정리 작업을 수행할 때 사용한다.",
      sourceExcerptId: "try-catch-003",
    },
  ],
};
