import type { QuestionPage } from "@/content/questions/types";

export const jsTypes: QuestionPage = {
  sourceId: "types",
  title: "자료형",
  url: "https://ko.javascript.info/types",
  questions: [
    {
      questionId: "types-yn-001",
      type: "yes_no",
      prompt: "자바스크립트의 숫자형은 정수와 부동소수점을 같은 자료형으로 다룬다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-types",
      explanation: "자바스크립트의 number 타입은 정수와 부동소수점을 구분하지 않고 함께 표현한다.",
      sourceExcerptId: "types-001",
    },
    {
      questionId: "types-yn-002",
      type: "yes_no",
      prompt: "typeof null의 결과는 null이다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-types",
      explanation: 'typeof null의 결과는 자바스크립트 역사적 이유로 "object"이다.',
      sourceExcerptId: "types-002",
    },
    {
      questionId: "types-yn-003",
      type: "yes_no",
      prompt: "boolean 타입은 true와 false 두 값만 가진다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-types",
      explanation: "boolean 타입은 참과 거짓을 나타내는 true, false 두 값만 가진다.",
      sourceExcerptId: "types-003",
    },
    {
      questionId: "types-mc-001",
      type: "multiple_choice",
      prompt: "문자열을 감쌀 때 사용할 수 없는 것은?",
      answer: "중괄호",
      choices: ["작은따옴표", "큰따옴표", "백틱", "중괄호", "템플릿 리터럴"],
      conceptGroup: "js-types",
      explanation:
        "문자열은 작은따옴표, 큰따옴표, 백틱으로 감쌀 수 있지만 중괄호는 사용할 수 없다.",
      sourceExcerptId: "types-004",
    },
    {
      questionId: "types-mc-002",
      type: "multiple_choice",
      prompt: "값이 존재하지 않음 또는 비어 있음을 의도적으로 나타낼 때 자주 쓰는 값은?",
      answer: "null",
      choices: ["undefined", "NaN", "null", "false", "0"],
      conceptGroup: "js-types",
      explanation:
        "null은 알 수 없거나 비어 있는 값처럼 의도적으로 비어 있음을 나타낼 때 자주 쓴다.",
      sourceExcerptId: "types-005",
    },
    {
      questionId: "types-mc-003",
      type: "multiple_choice",
      prompt: "typeof 연산자의 결과로 올바른 것은?",
      answer: 'typeof "hello" === "string"',
      choices: [
        'typeof "hello" === "string"',
        'typeof 10 === "integer"',
        'typeof true === "bool"',
        'typeof null === "null"',
        'typeof undefined === "empty"',
      ],
      conceptGroup: "js-types",
      explanation: 'typeof "hello"는 "string"을 반환한다.',
      sourceExcerptId: "types-006",
    },
    {
      questionId: "types-fb-001",
      type: "fill_blank",
      prompt: "정의되지 않은 값을 나타내는 특별한 값은 ____ 이다.",
      answer: "undefined",
      acceptedAnswers: ["undefined", '"undefined"', "'undefined'"],
      conceptGroup: "js-types",
      explanation: "undefined는 값이 할당되지 않았거나 정의되지 않은 상태를 나타낸다.",
      sourceExcerptId: "types-007",
    },
    {
      questionId: "types-fb-002",
      type: "fill_blank",
      prompt: "문자열 안에 변수나 표현식을 삽입하기 편한 문법은 ____ 리터럴이다.",
      answer: "템플릿",
      acceptedAnswers: ["템플릿", "template", "template literal", "템플릿 리터럴"],
      conceptGroup: "js-types",
      explanation: "백틱을 사용하는 템플릿 리터럴은 문자열 안에 표현식을 쉽게 넣을 수 있다.",
      sourceExcerptId: "types-008",
    },
    {
      questionId: "types-fb-003",
      type: "fill_blank",
      prompt: "typeof null의 결과는 ____ 이다.",
      answer: "object",
      acceptedAnswers: ["object", '"object"', "'object'"],
      conceptGroup: "js-types",
      explanation: 'typeof null은 오래된 자바스크립트 동작 때문에 "object"를 반환한다.',
      sourceExcerptId: "types-002",
    },
  ],
};
