import type { QuestionPage } from "../types";

export const variables: QuestionPage = {
  sourceId: "variables",
  title: "변수와 상수",
  url: "https://ko.javascript.info/variables",
  questions: [
    {
      questionId: "variables-yn-001",
      type: "yes_no",
      prompt: "let으로 선언한 변수는 값을 다시 할당할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-variables",
      explanation: "let으로 선언한 변수는 재할당할 수 있다.",
      sourceExcerptId: "variables-001",
    },
    {
      questionId: "variables-yn-002",
      type: "yes_no",
      prompt: "const로 선언한 변수는 반드시 선언과 동시에 값을 할당해야 한다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-variables",
      explanation: "const는 선언 시점에 값을 함께 할당해야 한다.",
      sourceExcerptId: "variables-002",
    },
    {
      questionId: "variables-yn-003",
      type: "yes_no",
      prompt: "대문자 상수 이름은 실행 중에 바뀌는 값을 저장할 때 주로 쓴다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-variables",
      explanation: "대문자 상수 이름은 보통 하드코딩된 고정값이나 알려진 상수를 나타낼 때 쓴다.",
      sourceExcerptId: "variables-003",
    },
    {
      questionId: "variables-mc-001",
      type: "multiple_choice",
      prompt: "자바스크립트에서 오래된 변수 선언 방식으로 분류되는 것은?",
      answer: "var",
      choices: ["let", "const", "var", "value", "define"],
      conceptGroup: "js-variables",
      explanation:
        "var는 오래된 변수 선언 방식이고, 현대 자바스크립트에서는 let과 const 사용이 권장된다.",
      sourceExcerptId: "variables-004",
    },
    {
      questionId: "variables-mc-002",
      type: "multiple_choice",
      prompt: "하드코딩된 고정값 상수 이름으로 적절한 예시는?",
      answer: "BIRTHDAY",
      choices: ["birthdayValue", "changeMe", "BIRTHDAY", "currentUserName", "mutableValue"],
      conceptGroup: "js-variables",
      explanation: "하드코딩된 고정값 상수는 보통 대문자와 밑줄 표기법을 사용한다.",
      sourceExcerptId: "variables-003",
    },
    {
      questionId: "variables-mc-003",
      type: "multiple_choice",
      prompt: "좋은 변수명에 대한 설명으로 가장 알맞은 것은?",
      answer: "값의 의미를 드러내야 한다",
      choices: [
        "값의 의미를 드러내야 한다",
        "무조건 한 글자여야 한다",
        "언제나 대문자만 써야 한다",
        "예약어를 써도 괜찮다",
        "숫자로 시작하는 것이 좋다",
      ],
      conceptGroup: "js-variables",
      explanation: "변수명은 역할과 의미를 드러내도록 짓는 것이 좋다.",
      sourceExcerptId: "variables-005",
    },
    {
      questionId: "variables-fb-001",
      type: "fill_blank",
      prompt: "값을 바꿀 수 있는 변수를 선언할 때는 ____ 을 사용한다.",
      answer: "let",
      acceptedAnswers: ["let", '"let"', "'let'"],
      conceptGroup: "js-variables",
      explanation: "재할당이 가능한 변수는 let으로 선언한다.",
      sourceExcerptId: "variables-001",
    },
    {
      questionId: "variables-fb-002",
      type: "fill_blank",
      prompt: "재할당할 수 없는 변수를 선언할 때는 ____ 를 사용한다.",
      answer: "const",
      acceptedAnswers: ["const", '"const"', "'const'"],
      conceptGroup: "js-variables",
      explanation: "변하지 않는 값은 const로 선언한다.",
      sourceExcerptId: "variables-002",
    },
    {
      questionId: "variables-fb-003",
      type: "multiple_choice",
      prompt: "전부 대문자인 상수 이름은 주로 어떤 값에 사용하는가?",
      answer: "하드코딩된 고정값",
      choices: [
        "실행 중 계속 바뀌는 값",
        "const로 선언한 모든 값",
        "하드코딩된 고정값",
        "사용자 입력으로 정해지는 값",
        "객체 프로퍼티 이름",
      ],
      conceptGroup: "js-variables",
      explanation: "대문자 상수 이름은 하드코딩된 고정값을 나타낼 때 자주 사용한다.",
      sourceExcerptId: "variables-003",
    },
  ],
};
