import type { QuestionPage } from "@/content/questions/types";

export const weakMapWeakSet: QuestionPage = {
  sourceId: "weakmap-weakset",
  title: "WeakMap과 WeakSet",
  url: "https://ko.javascript.info/weakmap-weakset",
  questions: [
    {
      questionId: "weakmap-weakset-yn-001",
      type: "yes_no",
      prompt: "WeakMap의 키는 객체여야 한다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-weakmap-weakset",
      explanation: "WeakMap은 객체만 키로 받을 수 있다.",
      sourceExcerptId: "weakmap-weakset-001",
    },
    {
      questionId: "weakmap-weakset-yn-002",
      type: "yes_no",
      prompt: "WeakSet은 객체만 저장할 수 있다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-weakmap-weakset",
      explanation: "WeakSet 역시 객체만 저장할 수 있다.",
      sourceExcerptId: "weakmap-weakset-002",
    },
    {
      questionId: "weakmap-weakset-yn-003",
      type: "yes_no",
      prompt: "WeakMap은 전체 요소를 for...of로 순회할 수 있다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-weakmap-weakset",
      explanation: "WeakMap과 WeakSet은 iterable이 아니며 전체 순회를 지원하지 않는다.",
      sourceExcerptId: "weakmap-weakset-003",
    },
    {
      questionId: "weakmap-weakset-mc-001",
      type: "multiple_choice",
      prompt: "WeakMap에 없는 기능은?",
      answer: "전체 키 순회",
      choices: ["set", "get", "has", "delete", "전체 키 순회"],
      conceptGroup: "js-weakmap-weakset",
      explanation: "WeakMap은 iterable이 아니므로 전체 키 순회를 제공하지 않는다.",
      sourceExcerptId: "weakmap-weakset-003",
    },
    {
      questionId: "weakmap-weakset-mc-002",
      type: "multiple_choice",
      prompt: "객체가 더 이상 참조되지 않을 때 관련 데이터도 함께 사라질 수 있는 구조는?",
      answer: "WeakMap",
      choices: ["Map", "Array", "WeakMap", "Set", "Object"],
      conceptGroup: "js-weakmap-weakset",
      explanation: "WeakMap은 약한 참조 특성 덕분에 객체 생명주기와 함께 데이터가 정리될 수 있다.",
      sourceExcerptId: "weakmap-weakset-004",
    },
    {
      questionId: "weakmap-weakset-mc-003",
      type: "multiple_choice",
      prompt: "WeakSet에 저장할 수 있는 값으로 맞는 것은?",
      answer: "객체",
      choices: ["문자열", "숫자", "객체", "boolean", "null"],
      conceptGroup: "js-weakmap-weakset",
      explanation: "WeakSet은 객체만 저장할 수 있다.",
      sourceExcerptId: "weakmap-weakset-002",
    },
    {
      questionId: "weakmap-weakset-fb-001",
      type: "fill_blank",
      prompt: "약한 참조 기반의 키-값 저장소는 ____ 이다.",
      answer: "WeakMap",
      acceptedAnswers: ["WeakMap"],
      conceptGroup: "js-weakmap-weakset",
      explanation: "WeakMap은 객체 키를 약한 참조로 관리하는 키-값 저장소다.",
      sourceExcerptId: "weakmap-weakset-001",
    },
    {
      questionId: "weakmap-weakset-fb-002",
      type: "fill_blank",
      prompt: "객체만 저장할 수 있는 약한 참조 집합은 ____ 이다.",
      answer: "WeakSet",
      acceptedAnswers: ["WeakSet"],
      conceptGroup: "js-weakmap-weakset",
      explanation: "WeakSet은 객체만 저장하는 약한 참조 집합이다.",
      sourceExcerptId: "weakmap-weakset-002",
    },
    {
      questionId: "weakmap-weakset-fb-003",
      type: "fill_blank",
      prompt: "WeakMap과 WeakSet은 전체 요소를 ____ 할 수 없다.",
      answer: "순회",
      acceptedAnswers: ["순회", "iterate"],
      conceptGroup: "js-weakmap-weakset",
      explanation: "WeakMap과 WeakSet은 iterable이 아니라 전체 순회를 제공하지 않는다.",
      sourceExcerptId: "weakmap-weakset-003",
    },
  ],
};
