import type { QuestionPage } from "@/content/questions/types";

export const whileFor: QuestionPage = {
  sourceId: "while-for",
  title: "while과 for 반복문",
  url: "https://ko.javascript.info/while-for",
  questions: [
    {
      questionId: "while-for-yn-001",
      type: "yes_no",
      prompt: "while 반복문은 조건이 truthy인 동안 반복을 계속한다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-loops",
      explanation: "while은 조건식이 참으로 평가되는 동안 계속 실행된다.",
      sourceExcerptId: "while-for-001",
    },
    {
      questionId: "while-for-yn-002",
      type: "yes_no",
      prompt: "for 문의 세 부분(초기화, 조건, 증감)은 모두 생략할 수 없다.",
      answer: false,
      acceptedAnswers: ["아니오", "false"],
      conceptGroup: "js-loops",
      explanation: "for의 각 부분은 필요에 따라 생략할 수 있다.",
      sourceExcerptId: "while-for-002",
    },
    {
      questionId: "while-for-yn-003",
      type: "yes_no",
      prompt: "break는 반복문을 즉시 종료할 때 사용한다.",
      answer: true,
      acceptedAnswers: ["예", "true"],
      conceptGroup: "js-loops",
      explanation: "break는 현재 반복문 전체를 즉시 빠져나간다.",
      sourceExcerptId: "while-for-003",
    },
    {
      questionId: "while-for-mc-001",
      type: "multiple_choice",
      prompt: "반복문의 현재 회차를 건너뛰고 다음 반복으로 넘어가게 하는 키워드는?",
      answer: "continue",
      choices: ["break", "continue", "return", "skip", "next"],
      conceptGroup: "js-loops",
      explanation: "continue는 현재 반복만 건너뛰고 다음 반복으로 진행한다.",
      sourceExcerptId: "while-for-004",
    },
    {
      questionId: "while-for-mc-002",
      type: "multiple_choice",
      prompt: "무한 루프를 만들 때 자주 쓰는 표현은?",
      answer: "while (true)",
      choices: ["while (true)", "for (false)", "if (true)", "loop {}", "repeat (1)"],
      conceptGroup: "js-loops",
      explanation: "while (true)는 대표적인 무한 루프 표현이다.",
      sourceExcerptId: "while-for-005",
    },
    {
      questionId: "while-for-mc-003",
      type: "multiple_choice",
      prompt: "for (let i = 0; i < 3; i++) 에서 조건식은?",
      answer: "i < 3",
      choices: ["let i = 0", "i < 3", "i++", "3", "for"],
      conceptGroup: "js-loops",
      explanation: "두 번째 자리에 오는 식이 반복 계속 여부를 결정하는 조건식이다.",
      sourceExcerptId: "while-for-002",
    },
    {
      questionId: "while-for-fb-001",
      type: "fill_blank",
      prompt: "현재 반복을 완전히 끝내고 반복문 밖으로 나가려면 ____ 를 사용한다.",
      answer: "break",
      acceptedAnswers: ["break"],
      conceptGroup: "js-loops",
      explanation: "break는 반복문 전체를 종료한다.",
      sourceExcerptId: "while-for-003",
    },
    {
      questionId: "while-for-fb-002",
      type: "fill_blank",
      prompt: "현재 반복만 건너뛰고 다음 반복으로 넘어가려면 ____ 를 사용한다.",
      answer: "continue",
      acceptedAnswers: ["continue"],
      conceptGroup: "js-loops",
      explanation: "continue는 현재 회차만 건너뛴다.",
      sourceExcerptId: "while-for-004",
    },
    {
      questionId: "while-for-fb-003",
      type: "fill_blank",
      prompt: "조건이 참인 동안 반복을 계속하는 기본 반복문은 ____ 문이다.",
      answer: "while",
      acceptedAnswers: ["while"],
      conceptGroup: "js-loops",
      explanation: "while 문은 가장 기본적인 조건 기반 반복문이다.",
      sourceExcerptId: "while-for-001",
    },
  ],
};
